import {build} from 'esbuild';
import assert from 'node:assert/strict';
import React from 'react';
import {renderToString} from 'react-dom/server';
await build({stdin:{resolveDir:process.cwd(),contents:`export * as UI from './app/shot-direction-editor';`},bundle:true,platform:'node',format:'esm',outfile:'work/tests/acting-task-ui.mjs',external:['react','react-dom'],banner:{js:`import {createRequire} from 'node:module';const require=createRequire(import.meta.url);`}});
const {UI}=await import('../work/tests/acting-task-ui.mjs');
const originalFetch=globalThis.fetch;globalThis.fetch=()=>{throw Error('SSR must not make network calls')};
let changes=0;
const onChange=()=>{changes++;throw Error('SSR must not edit or generate')};
const html=(component,props)=>renderToString(React.createElement(component,props));
const text=value=>value.replace(/<[^>]*>/g,'');
try{
  const performance={characterId:'hero',character:'Вера',objective:'Убедиться в успехе',subtext:'Ждёт похвалы, но осознаёт угрозу',visibleAction:'Увидев тревожное сообщение, задерживает взгляд; брови сходятся, сомкнутые губы напрягаются.',emotionStart:'Уверенность',emotionEnd:'Тревога'};
  const direction={framingStart:'close-up',framingEnd:'close-up',cameraMovement:{type:'static',description:'Статичная камера'},performance:[performance]};
  const before=structuredClone(direction);
  const summary=html(UI.ShotDirectionSummary,{direction,duration:5});
  const headings=[...summary.matchAll(/<summary[^>]*>([\s\S]*?)<\/summary>/g)].map(v=>text(v[1]));
  assert(headings.includes('Актёрская задача: Вера · Уверенность → Тревога'),'The emotional arc is visible before expanding the acting details');
  for(const field of ['objective','subtext','visibleAction','emotionStart','emotionEnd'])assert(text(summary).includes(performance[field]),field+' is shown in the actual summary');
  const editor=html(UI.ShotDirectionEditor,{direction,duration:5,onChange,disabled:true});
  assert(editor.includes('<fieldset disabled=""'),'Pending/read-only state disables the whole editor');
  for(const label of ['Чего добивается','Подтекст','Наблюдаемое действие','Эмоция в начале','Эмоция в конце'])assert(text(editor).includes(label),label);
  for(const field of ['objective','subtext','visibleAction','emotionStart','emotionEnd'])assert(text(editor).includes(performance[field]),field+' remains editable/displayed');
  assert(text(editor).includes('Все пять полей передаются в видеопромпт.'));
  assert(text(editor).includes('Подтекст объясняет игру, но не становится репликой или закадровым голосом.'));
  assert(text(editor).includes('начало → событие → реакция → состояние в конце'));
  const incomplete=html(UI.ShotDirectionSummary,{direction:{performance:[{...performance,emotionStart:'',emotionEnd:''}]},duration:5});
  assert(text(incomplete).includes('начальная эмоция не задана → конечная эмоция не задана'),'Missing emotions must be visible instead of silently invented');
  const legacy=html(UI.ShotDirectionSummary,{});
  assert(text(legacy).includes('Используются текстовые описания плана'));
  assert(!text(legacy).includes('Актёрская задача:'),'Legacy plans do not gain made-up actor tasks');
  const edited=UI.patchShotDirection(direction,{performance:[{...performance,subtext:'Новое понимание события'}]});
  assert.equal(edited.performance[0].subtext,'Новое понимание события');
  assert.equal(edited.performance[0].emotionStart,performance.emotionStart);
  assert.deepEqual(edited.cameraMovement,direction.cameraMovement);
  assert.deepEqual(direction,before,'Rendering and local editing preserve the saved actor task');
  assert.equal(changes,0);
  console.log('PASS actual actor editor/summary: emotional arc visible while collapsed; five fields and speech distinction; empty/legacy states; immutable local updates; SSR sends no requests.');
}finally{globalThis.fetch=originalFetch;}
