import {build} from 'esbuild';
import A from 'node:assert/strict';
import React from 'react';
import {renderToString} from 'react-dom/server';
await build({stdin:{resolveDir:process.cwd(),contents:`export * as D from './lib/domain';export * as Q from './lib/audio-qc';export {mediaReviewPrompt} from './lib/media-review';export {AudioQcEditor} from './app/audio-qc-editor';`},bundle:true,platform:'node',format:'esm',outfile:'work/tests/audio-qc.mjs',external:['react','react-dom','@ffmpeg/ffmpeg']});
const {D,Q,mediaReviewPrompt,AudioQcEditor}=await import('../work/tests/audio-qc.mjs');
const p=D.newProject('Звуковой контроль'),film=p.items.find(i=>i.stage===8),v=D.makeVariant(p,film,{kind:'video',assetId:D.id(),duration:6});film.variants.push(v);film.selectedId=v.id;
const before=structuredClone(p),source=Q.makeAudioQcSource(p,film.id,v.id);A.deepEqual(p,before);A.throws(()=>Q.makeAudioQcSource(p,p.items[0].id,v.id),/Выберите/);A.throws(()=>Q.makeAudioQcSource(p,film.id,D.id()),/Выберите/);
const probe={format:{duration:'6'},streams:[{codec_type:'video',duration:'6'},{codec_type:'audio',duration:'6',sample_rate:'44100',channels:2}]},logs=['[astats] Overall','[astats] Peak level dB: -0.50','[astats] RMS level dB: -38.00','[astats] Number of samples: 264600','[silencedetect] silence_start: 0','[silencedetect] silence_end: 1 | silence_duration: 1','[silencedetect] silence_start: 5'];
const measurement=Q.parseAudioQcMeasurement(probe,logs);A.equal(measurement.seconds,6);A.equal(measurement.audioSeconds,6);A.equal(measurement.peakDb,-.5);A.deepEqual(measurement.silence,[{start:0,end:1,duration:1},{start:5,end:6,duration:1}]);A(measurement.issues.some(i=>i.criterion==='Запас по пику'));A(measurement.issues.some(i=>i.criterion==='Средний уровень'));A(measurement.limitations.some(v=>v.includes('не true-peak')));A(measurement.issues.every(i=>!i.evidence.includes('Клиппинг подтверждён')));
const report=Q.audioQcReportSchema.parse({schemaVersion:1,id:D.id(),created:new Date().toISOString(),source,settings:Q.audioQcSettingsSchema.parse({}),measurement,evidence:Q.audioQcEvidence(logs)});A.deepEqual(Q.assertAudioQcReportSource(p,report),report);
const unchanged=structuredClone(p);unchanged.revision+=20;unchanged.jobs.push({id:D.id(),status:'polling'});A.deepEqual(Q.makeAudioQcSource(unchanged,film.id,v.id),source,'Unrelated polling never invalidates fixed file evidence');
for(const key of ['projectId','itemId','variantId','assetId','signature']){const foreign=structuredClone(report);foreign.source[key]=D.id();A.throws(()=>Q.assertAudioQcReportSource(p,foreign),/изменился|Выберите/,key);}
const changed=structuredClone(p);changed.items.find(i=>i.id===film.id).variants[0].assetId=D.id();A.throws(()=>Q.assertAudioQcReportSource(changed,report),/изменился/);changed.audioQc=[report];A.equal(Q.audioQcPromptContext(changed,changed.items.find(i=>i.id===film.id),changed.items.find(i=>i.id===film.id).variants[0]),undefined);
const broken=structuredClone(report);broken.measurement.silence[0].end=20;broken.measurement.silence[0].duration=20;A.throws(()=>Q.assertAudioQcReportSource(p,broken),/Интервал/);A.equal(Q.audioQcReportSchema.safeParse({...report,measurement:{...measurement,peakDb:Infinity}}).success,false);A.throws(()=>Q.audioQcProbeInfo({format:{duration:'601'},streams:probe.streams}),/всего более длинного фильма/);A.throws(()=>Q.parseAudioQcMeasurement(probe,[]),/полную статистику/);
p.audioQc=[report];const stored=structuredClone(p),context=Q.audioQcPromptContext(p,film,v);A.equal(context.kind,'technical-audio-qc');A(context.interpretation.includes('Не утверждай, что слышал речь'));A.equal(context.measurement.peakDb,-.5);A.deepEqual(p,stored);A(mediaReviewPrompt(p,film,v,[],'film').includes('technical-audio-qc'),'Editor receives actual measurements, not a claim of hearing the soundtrack');
const absent=Q.parseAudioQcMeasurement({format:{duration:6},streams:[{codec_type:'video'}]},[]);A.equal(absent.hasAudio,false);A(absent.issues.some(i=>i.criterion==='Аудиодорожка'));const silent=Q.parseAudioQcMeasurement(probe,['Peak level dB: -inf','RMS level dB: -inf','Number of samples: 264600','silence_start: 0']);A.equal(silent.peakDb,null);A.equal(silent.rmsDb,null);A(silent.issues.some(i=>i.criterion==='Отсутствие сигнала'));
let calls=0;const html=renderToString(React.createElement(AudioQcEditor,{p,itemId:film.id,variantId:v.id,busy:false,onSave:async()=>{calls++;},loadAsset:async()=>{calls++;throw Error('No read on render');}}));A(html.includes('Проверить звук файла'));A(html.includes('-0.50'));A.equal(calls,0);A.deepEqual(p,stored);
console.log('PASS audio QC: actual-source isolation, stable frozen identity, bounded schemas, peak/RMS/silence evidence, absent/zero audio, honest limits, matching-file editor context, legacy no-op and SSR without processing/paid calls.');
