import {build} from 'esbuild';
import assert from 'node:assert/strict';
await build({stdin:{resolveDir:process.cwd(),contents:`export * as W from './lib/background-work';export * as D from './lib/domain';`},bundle:true,platform:'node',format:'esm',outfile:'work/tests/background-work.mjs'});
const {W,D}=await import('../work/tests/background-work.mjs');
const p=D.newProject('Фоновый фильм'),other=D.newProject('Другой владелец');
const job=(purpose,status='queued')=>({id:D.id(),itemId:D.id(),batchId:D.id(),model:'grok-imagine-image-2.0',kind:'image',purpose,status,created:'2026-10-01T10:00:00Z',estimate:'1',actual:null,refs:[]});
p.jobs=[job(undefined),job('voice-design'),job('media-review'),job(undefined,'unknown'),job(undefined,'failed')];p.jobs[1].voiceWorkflow={provider:'elevenlabs'};other.jobs=[job(undefined)];
const store=new Map([[p.id,p],[other.id,other]]),owners=new Map([[p.id,'owner-a'],[other.id,'owner-b']]),calls=[],releases=[],tickTime=Date.parse('2026-10-01T12:00:00Z');
const execute=async(owner,id,jobId,kind)=>{assert.equal(owner,owners.get(id));calls.push({owner,id,jobId,kind});const j=store.get(id).jobs.find(j=>j.id===jobId);j.status='pending';await new Promise(resolve=>releases.push(resolve));j.status='done';return structuredClone(store.get(id));};
const worker=W.createBackgroundWorker({listProjects:async()=>[...owners].map(([id,owner])=>({id,owner})),loadProject:async(owner,id)=>{assert.equal(owner,owners.get(id));return structuredClone(store.get(id));},executeMediaJob:(owner,id,jobId,action)=>execute(owner,id,jobId,action??'media'),executeVoiceJob:(owner,id,jobId)=>execute(owner,id,jobId,'voice'),runDirectorStep:async()=>{throw Error('Unexpected director call');},now:()=>tickTime},{maxFlights:8});
const first=worker.tickAll();await new Promise(resolve=>setImmediate(resolve));assert.equal(calls.length,4);assert(calls.some(c=>c.kind==='voice'));assert(calls.some(c=>c.owner==='owner-b'));assert(!calls.some(c=>['unknown','failed'].includes(p.jobs.find(j=>j.id===c.jobId)?.status)));
const second=worker.tickAll();await new Promise(resolve=>setImmediate(resolve));assert.equal(calls.length,4,'Overlapping Node intervals do not duplicate an in-flight job');for(const release of releases)release();await Promise.all([first,second]);assert.equal(worker.inFlightCount(),0);await worker.tickAll();assert.equal(calls.length,4,'Done/failed/unknown jobs never become queued automatically');
let invoked=0,promise;assert.equal(W.scheduleBackgroundWork(null,async()=>invoked++),false);assert.equal(invoked,0);assert(W.scheduleBackgroundWork({waitUntil:p=>{promise=p;}},async()=>invoked++));await promise;assert.equal(invoked,1);
let caught;assert(W.scheduleBackgroundWork({waitUntil:p=>{promise=p;}},async()=>{throw Error('Owned persisted error');},e=>caught=e));await promise;assert.match(caught.message,/persisted/);
const watchdog=structuredClone(p);watchdog.jobs=[{...job(undefined,'dispatching'),started:'2026-10-01T10:00:00Z'}];const actions=[];const watchWorker=W.createBackgroundWorker({listProjects:async()=>[],loadProject:async()=>watchdog,executeMediaJob:async(_,__,id,action)=>{actions.push(action);return watchdog;},executeVoiceJob:async()=>{throw Error('Unexpected voice');},runDirectorStep:async()=>watchdog,now:()=>tickTime});await watchWorker.tickProject('owner',watchdog.id);assert.deepEqual(actions,['check-wait']);
const secret='0123456789abcdef0123456789abcdef';assert(await W.workerSecretMatches(secret,secret));assert(!await W.workerSecretMatches(secret,'wrong'));assert(!await W.workerSecretMatches(undefined,secret));assert(!await W.workerSecretMatches('short','short'));assert(!await W.workerSecretMatches(secret,'x'.repeat(1000)));
assert.throws(()=>W.createBackgroundWorker({}, {maxFlights:0}));
// A cancelled hosted event can strand its JS promise. Lease expiry only drops
// the local flight; the persisted dispatching status still prohibits resubmit.
let clock=tickTime,finishOld;const leaseProject=D.newProject('Cancelled event');leaseProject.jobs=[job(undefined)];let submits=0;
const leased=W.createBackgroundWorker({...adaptersForLease(),now:()=>clock},{flightLeaseMs:35_000});
function adaptersForLease(){return {listProjects:async()=>[],loadProject:async()=>structuredClone(leaseProject),executeVoiceJob:async()=>leaseProject,runDirectorStep:async()=>leaseProject,executeMediaJob:async(_,__,id)=>{submits++;const j=leaseProject.jobs.find(j=>j.id===id);j.status='dispatching';j.started=new Date(clock).toISOString();if(submits===1)await new Promise(r=>finishOld=r);else j.status='done';return leaseProject;}};}
const orphan=leased.tickProject('owner',leaseProject.id);await new Promise(r=>setImmediate(r));assert.equal(submits,1);
clock+=35_000;leaseProject.jobs.push(job(undefined));await leased.tickProject('owner',leaseProject.id);assert.equal(submits,2,'Unrelated queued job can advance after orphan expiry');assert.equal(leaseProject.jobs[0].status,'dispatching','Paid request with no receipt is never silently reset');
finishOld();await orphan;assert.equal(leased.inFlightCount(),0);
console.log('PASS background engine: trusted database owners, media/voice routing, overlapping ticks without duplicate calls, no unknown/failed retry, watchdog-only expiry, waitUntil/no-context behavior and constant-time secret digest check. Mock executors only.');
