import {build} from 'esbuild';
import {strict as assert} from 'node:assert';
await build({entryPoints:['lib/domain.ts','lib/characters.ts','lib/character-removal.ts','lib/style-approval.ts','lib/approval-blockers.ts','app/api/projects/[id]/route.ts','app/api/projects/[id]/generate/route.ts'],bundle:true,platform:'node',format:'esm',outdir:'work/tests/character-removal',outbase:'.',outExtension:{'.js':'.mjs'},plugins:[{name:'mock',setup(b){b.onResolve({filter:/^@\/lib\/server$/},()=>({path:'server',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:`export const api=fn=>async(req,ctx)=>{try{return await fn(req,ctx)}catch(e){return Response.json({error:e.message},{status:400})}};export const owner=async()=> 'owner';export const loadProject=async()=>structuredClone(globalThis.state);export const saveProject=async(_,p,rev)=>{if(rev!==state.revision)throw new Error('revision');p.revision++;globalThis.state=structuredClone(p);return p};export const getKey=async()=> 'test';export const asset=async(_,id)=>({id,mime:'image/png',size:100});`}));}}]});
const root='../work/tests/character-removal/',D=await import(root+'lib/domain.mjs'),C=await import(root+'lib/characters.mjs'),R=await import(root+'lib/character-removal.mjs'),S=await import(root+'lib/style-approval.mjs'),B=await import(root+'lib/approval-blockers.mjs');
const api=await import(root+'app/api/projects/[id]/route.mjs'),G=await import(root+'app/api/projects/[id]/generate/route.mjs');
const p=D.newProject('Стиль и герои');
for(const item of p.items.filter(i=>i.stage<=3)){D.addVariant(p,item.id,{text:'Утверждённая основа'});D.approve(p,item.id);}
const legacy=p.items[1],style=p.items[2],styleId=style.approvedId;
const hero={id:D.id(),stage:1,title:'Петя',character:{name:'Петя',appearance:'Рыжий мальчик',description:'Смелый',instructions:'',refs:[]},variants:[]};p.items.push(hero);
assert(!D.stageReady(p,2));assert.match(S.styleReapprovalReason(p,style.id,styleId),/все нужные карточки героев/);
assert.throws(()=>S.reapproveStyle(p,style.id,styleId));
D.addVariant(p,hero.id,{kind:'image',assetId:D.id(),character:hero.character});D.approve(p,hero.id);
assert(D.stageReady(p,2));assert(!D.isApproved(p,style));assert.equal(S.styleReapprovalReason(p,style.id,styleId),'');
const before=structuredClone(style),history={id:D.id(),itemId:style.id,status:'done',deps:style.variants[0].deps,actual:'25',refs:[],model:'old',prompt:'old'};p.jobs.push(history);
S.reapproveStyle(p,style.id,styleId);assert.equal(style.variants.length,1);assert.equal(style.approvedId,styleId);assert.equal(D.chosen(style).text,before.variants[0].text);assert.equal(history.deps,before.variants[0].deps);assert.equal(history.actual,'25');assert(D.isApproved(p,style));assert(!D.isApproved(p,p.items[3]));
const newSelected=D.makeVariant(p,style,{text:'Другой стиль'});style.variants.push(newSelected);style.selectedId=newSelected.id;assert.throws(()=>S.reapproveStyle(p,style.id,styleId),/Выберите/);style.selectedId=styleId;
const active=structuredClone(p);active.jobs.push({id:D.id(),itemId:hero.id,status:'queued',refs:[],actual:null});assert.throws(()=>R.removeCharacter(active,hero.id),/текущих генераций/);assert.throws(()=>S.reapproveStyle(active,style.id,styleId));
const dependent=structuredClone(p);dependent.jobs.push({id:D.id(),itemId:p.items[5].id,status:'saving',refs:[],actual:null});assert.throws(()=>R.removeCharacter(dependent,hero.id),/текущих генераций/);
const beforeRemoval=structuredClone(p);R.removeCharacter(p,legacy.id);assert(!D.participates(p,legacy));assert(!D.isApproved(p,legacy));assert(legacy.variants.length);assert.equal(p.jobs.length,beforeRemoval.jobs.length);assert(!D.dependencies(p,2).includes(legacy.id));assert(!B.approvalBlockers(p,3).some(b=>b.itemId===legacy.id));
S.reapproveStyle(p,style.id,styleId);assert(D.isApproved(p,style));assert.equal(style.variants.length,2,'Reapproval does not create a version');
assert.equal(C.approvedCharacters(p).length,1);const assetId=D.chosen(hero).assetId;R.removeCharacter(p,hero.id);assert.equal(C.approvedCharacters(p).length,0);assert(!D.promptFor(p,p.items[4],'Сценарий').includes('Рыжий мальчик'));assert.equal(D.chosen(hero).assetId,assetId,'Files and variants are retained');
assert.throws(()=>D.addVariant(p,hero.id,{text:'new'}),/восстановите/);assert.throws(()=>D.approve(p,hero.id),/восстановите/);
R.restoreCharacter(p,hero.id);assert(!hero.removedAt);assert.equal(hero.approvedId,undefined);assert(!D.stageReady(p,2));assert.equal(D.chosen(hero).assetId,assetId);
globalThis.state=structuredClone(beforeRemoval);const ctx={params:Promise.resolve({id:p.id})};const req=b=>new Request('http://localhost',{method:'PATCH',body:JSON.stringify(b)});
let response=await api.PATCH(req({revision:state.revision,action:'removeCharacter',itemId:hero.id}),ctx);assert.equal(response.status,200);assert(state.items.find(i=>i.id===hero.id).removedAt);
response=await api.PATCH(req({revision:state.revision,action:'renameItem',itemId:hero.id,data:{title:'Недоступно'}}),ctx);assert.equal(response.status,400);
response=await G.POST(req({revision:state.revision,batchId:D.id(),itemId:hero.id,models:['grok-imagine-image-2.0'],count:1,prompt:'test',refs:[],dialogue:'',voiceId:'',estimates:{}}),ctx);assert.equal(response.status,400);assert.equal(state.jobs.length,beforeRemoval.jobs.length);
response=await api.PATCH(req({revision:state.revision,action:'restoreCharacter',itemId:hero.id}),ctx);assert.equal(response.status,200);assert.equal(state.items.find(i=>i.id===hero.id).approvedId,undefined);
const empty={id:D.id(),stage:1,title:'Новый герой',variants:[]};state.items.push(empty);
state.jobs.push({id:D.id(),itemId:empty.id,status:'queued',refs:[],actual:null});
response=await api.PATCH(req({revision:state.revision,action:'removeEmpty',itemId:empty.id}),ctx);assert.equal(response.status,400);assert(!state.items.find(i=>i.id===empty.id).removedAt);
state.jobs.at(-1).status='cancelled';
response=await api.PATCH(req({revision:state.revision,action:'removeEmpty',itemId:empty.id}),ctx);assert.equal(response.status,200);assert(state.items.find(i=>i.id===empty.id).removedAt);assert.equal(state.jobs.at(-1).itemId,empty.id);
console.log('PASS style and hero removal: unchanged variant IDs and files, director-only reapproval, missing-hero gates, legacy and individual removal, active-job protection, reference/context exclusion, preserved receipts, restoration without approval and real route guards. No paid calls.');
