import {build} from 'esbuild';
import A from 'node:assert/strict';
import React from 'react';
import {renderToString} from 'react-dom/server';
const server=`
export class HttpError extends Error{constructor(message,status=400){super(message);this.status=status;}}
export const api=fn=>async(req,ctx)=>{try{return await fn(req,ctx)}catch(e){return Response.json({error:e.message},{status:e.status??400})}};
export const owner=async req=>{if(req.headers.get('test-user')!=='owner')throw new HttpError('Unauthorized',401);return 'owner'};
export const loadProject=async(user,id)=>{if(user!=='owner'||id!==globalThis.soundState.id)throw new HttpError('Not found',404);return structuredClone(globalThis.soundState)};
export const saveProject=async(user,p,revision)=>{if(revision!==soundState.revision)throw new HttpError('Revision',409);if(globalThis.soundConflict){globalThis.soundConflict=false;throw new HttpError('CAS',409)}p.revision++;globalThis.soundState=structuredClone(p);return p};
export const mutate=async(user,id,fn)=>{for(let n=0;n<5;n++){const p=await loadProject(user,id);fn(p);try{return await saveProject(user,p,p.revision)}catch(e){if(e.status!==409||n===4)throw e}}};
export const getKey=async()=>{if(globalThis.soundMissingKey)throw Error('No key');return globalThis.soundSecret};
export const asset=async(user,id,p)=>{const a=globalThis.soundAssets.get(id);if(!a||a.owner!==user||a.projectId!==p.id)throw new HttpError('Foreign asset',404);return a};
export const storeAsset=async(user,id,name,mime,bytes,projectId)=>{if(globalThis.soundFailStore){globalThis.soundFailStore=false;throw Error('Storage failure')}globalThis.soundAssets.set(id,{id,owner:user,projectId,mime,bytes:new Uint8Array(bytes)});return id};
export const runtime={FILES:{async put(key,bytes){globalThis.soundFiles.set(key,new Uint8Array(bytes))},async get(key){const bytes=globalThis.soundFiles.get(key);return bytes?{async arrayBuffer(){return bytes.slice().buffer}}:null}}};
`;
await build({stdin:{resolveDir:process.cwd(),contents:`export * as D from './lib/domain';export * as S from './lib/soundscape';export * as R from './lib/soundscape-runner';export {projectAssetIds} from './lib/project-assets';export {POST} from './app/api/projects/[id]/soundscape/route';export {SoundscapeEditor} from './app/soundscape-editor';`},bundle:true,platform:'node',format:'esm',outfile:'work/tests/soundscape.mjs',external:['react','react-dom','@ffmpeg/ffmpeg'],plugins:[{name:'mock-server',setup(b){b.onResolve({filter:/^(?:@\/lib|\.)\/server$/},()=>({path:'server',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},()=>({contents:server}));}}]});
const {D,S,R,POST,SoundscapeEditor,projectAssetIds}=await import('../work/tests/soundscape.mjs');
let groups=0;async function test(name,fn){await fn();groups++;console.log('PASS soundscape:',name);}
function setup(){globalThis.soundState=D.newProject('Звуковая атмосфера');globalThis.soundState.limit=null;globalThis.soundAssets=new Map();globalThis.soundFiles=new Map();globalThis.soundCalls=[];globalThis.soundSecret='sound-private-secret';globalThis.soundConflict=false;globalThis.soundFailStore=false;globalThis.soundMissingKey=false;globalThis.soundHold=null;globalThis.soundRelease=null;globalThis.soundTransportError=false;globalThis.soundEmpty=false;}
const request=(action,data,revision=soundState.revision,user='owner',pid=soundState.id)=>POST(new Request('http://local',{method:'POST',headers:{'test-user':user},body:JSON.stringify({revision,action,data})}),{params:Promise.resolve({id:pid})});
const ok=async(action,data,revision)=>{const response=await request(action,data,revision);A.equal(response.status,200,await response.clone().text());return response.json();};
const input={name:'Тихое болото',kind:'ambience',scope:{type:'film'},settings:{loop:true,volume:.5,speechVolume:.05,fadeIn:0,fadeOut:0}};
const generation={prompt:'Gentle marsh ambience, reeds rustling and soft water, no speech or music.',duration:8,loop:true,influence:.7,count:1};
globalThis.fetch=async(url,options)=>{soundCalls.push({url,body:JSON.parse(options.body)});A(soundState.jobs.some(j=>j.purpose==='soundscape'&&j.status==='dispatching'));A.equal(options.headers['xi-api-key'],soundSecret);if(soundHold)await soundHold;if(soundTransportError)throw Error('Uncertain '+soundSecret);return new Response(soundEmpty?new Uint8Array():new Uint8Array([73,68,51]),{headers:{'content-type':'audio/mpeg','request-id':'sound-receipt-'+soundCalls.length,'character-cost':'320'}});};
setup();
await test('legacy read and SSR are optional, schema checks source scope and no playback/generation on view',async()=>{
 const p=structuredClone(soundState),before=structuredClone(p);A.deepEqual(S.readSoundscape(p),{enabled:false,layers:[]});A.deepEqual(S.buildSoundscapeMix(p,{seconds:6,clips:[]}),[]);A.deepEqual(p,before);let submits=0;
 const html=renderToString(React.createElement(SoundscapeEditor,{p,busy:false,submit:async()=>{submits++},upload:async()=>{throw Error('No upload')}}));A(html.includes('Атмосфера и звуковые эффекты'));A.equal(submits,0);A.equal(soundCalls.length,0);A.deepEqual(p,before);
 A.throws(()=>S.saveSoundLayer(p,{...input,scope:{type:'plan',itemId:D.id()}}),/План/);A.equal(S.soundSettingsSchema.safeParse({volume:.1,speechVolume:.2}).success,false);A.equal(S.soundGenerationSchema.safeParse({...generation,duration:31}).success,false);
});
await test('ownership/revision/foreign uploaded file checks run before snapshot mutation',async()=>{
 const before=structuredClone(soundState);A.equal((await request('saveLayer',{layer:input},-1)).status,409);A.equal((await request('saveLayer',{layer:input},0,'other')).status,401);A.equal((await request('saveLayer',{layer:input},0,'owner',D.id())).status,404);A.deepEqual(soundState,before);
 await ok('saveLayer',{layer:input});const layer=soundState.soundscape.layers[0],assetId=D.id();soundAssets.set(assetId,{owner:'owner',projectId:D.id(),mime:'audio/mpeg'});const saved=structuredClone(soundState);A.equal((await request('addVariant',{layerId:layer.id,assetId,seconds:2})).status,404);A.deepEqual(soundState,saved);
 soundAssets.set(assetId,{owner:'owner',projectId:soundState.id,mime:'audio/mpeg'});await ok('addVariant',{layerId:layer.id,assetId,description:'My ambience'});const v=soundState.soundscape.layers[0].variants[0];A.equal(v.seconds,undefined);A.equal(soundState.soundscape.layers[0].selectedId,undefined);await ok('choose',{layerId:layer.id,variantId:v.id});A.equal((await request('approve',{layerId:layer.id})).status,400);await ok('approve',{layerId:layer.id,seconds:2});A(S.soundLayerApproved(soundState.soundscape.layers[0]));
});
await test('sound job payload is frozen, every generation billed as a distinct attempt, no implicit selection/approval',async()=>{
 setup();await ok('saveLayer',{layer:input});const layer=soundState.soundscape.layers[0],batchId=D.id();await ok('generate',{batchId,layerId:layer.id,generation:{...generation,count:2}});A.equal(soundState.jobs.length,2);A.equal(soundCalls.length,0);await ok('generate',{batchId,layerId:layer.id,generation},0);A.equal(soundState.jobs.length,2);soundState.soundscape.layers[0].promptNotes='Changed after queue';
 for(const j of [...soundState.jobs])await ok('advance',{jobId:j.id});A.equal(soundCalls.length,2);A(soundCalls.every(c=>c.url==='https://api.elevenlabs.io/v1/sound-generation?output_format=mp3_44100_128'));A(soundCalls.every(c=>c.body.model_id==='eleven_text_to_sound_v2'&&c.body.text===generation.prompt&&c.body.duration_seconds===8&&c.body.loop===true&&c.body.prompt_influence===.7));A.equal(soundState.soundscape.layers[0].variants.length,2);A.equal(soundState.soundscape.layers[0].selectedId,undefined);A.equal(soundState.soundscape.layers[0].approvedId,undefined);A(soundState.jobs.every(j=>j.actual===null&&j.usage.characterCost===320&&j.requestId));A(!JSON.stringify(soundState).includes(soundSecret));await ok('advance',{jobId:soundState.jobs[0].id});A.equal(soundCalls.length,2);
});
await test('global queue slot and concurrent CAS claims admit at most one actual remote request',async()=>{
 setup();await ok('saveLayer',{layer:input});await ok('generate',{batchId:D.id(),layerId:soundState.soundscape.layers[0].id,generation});const job=soundState.jobs[0];soundState.queueSettings={concurrency:1,providerLimits:{}};soundState.jobs.push({...structuredClone(job),id:D.id(),itemId:soundState.items[0].id,purpose:undefined,model:'speech-2.8-hd',status:'dispatching'});await ok('advance',{jobId:job.id});A.equal(soundCalls.length,0);A.equal(soundState.jobs[0].status,'queued');soundState.jobs[1].status='done';
 soundHold=new Promise(resolve=>soundRelease=resolve);const flights=[R.runSoundscapeStep('owner',soundState.id,job.id),R.runSoundscapeStep('owner',soundState.id,job.id)];await new Promise(r=>setTimeout(r,5));A.equal(soundCalls.length,1);soundRelease();await Promise.all(flights);A.equal(soundCalls.length,1);A.equal(soundState.jobs[0].status,'done');
});
await test('unknown never retries; manual separate-series authorization does not resend the unknown job',async()=>{
 setup();await ok('saveLayer',{layer:input});const layerId=soundState.soundscape.layers[0].id;await ok('generate',{batchId:D.id(),layerId,generation});soundTransportError=true;await ok('advance',{jobId:soundState.jobs[0].id});const unknownId=soundState.jobs[0].id;A.equal(soundState.jobs[0].status,'unknown');A.equal(soundState.jobs[0].actual,null);A(!JSON.stringify(soundState).includes(soundSecret));await ok('advance',{jobId:unknownId});A.equal(soundCalls.length,1);A.equal((await request('generate',{batchId:D.id(),layerId,generation})).status,400);await ok('allowNewSeries',{jobId:unknownId});await ok('generate',{batchId:D.id(),layerId,generation});A.equal(soundState.jobs.length,2);A.equal(soundState.jobs[0].status,'unknown');A.equal(soundCalls.length,1);
});
await test('file storage recovery reuses staged bytes and a late result remains unselected/unapproved',async()=>{
 setup();await ok('saveLayer',{layer:input});await ok('generate',{batchId:D.id(),layerId:soundState.soundscape.layers[0].id,generation});const jobId=soundState.jobs[0].id;soundFailStore=true;await ok('advance',{jobId});A.equal(soundState.jobs[0].status,'saving');A.equal(soundState.jobs[0].requestId,'sound-receipt-1');await ok('advance',{jobId});A.equal(soundCalls.length,1);A.equal(soundState.jobs[0].status,'done');
 setup();await ok('saveLayer',{layer:input});await ok('generate',{batchId:D.id(),layerId:soundState.soundscape.layers[0].id,generation});const lateId=soundState.jobs[0].id;soundHold=new Promise(resolve=>soundRelease=resolve);const flight=R.runSoundscapeStep('owner',soundState.id,lateId);await new Promise(r=>setTimeout(r,5));await ok('stop',{jobId:lateId});soundRelease();await flight;A.equal(soundState.jobs[0].soundInput.late,true);A.equal(soundState.soundscape.layers[0].variants.length,1);A.equal(soundState.soundscape.layers[0].selectedId,undefined);A.equal(soundState.soundscape.layers[0].approvedId,undefined);
});
await test('malformed paid response retains provider billing units; missing-key and budget failures do not dispatch',async()=>{
 setup();await ok('saveLayer',{layer:input});await ok('generate',{batchId:D.id(),layerId:soundState.soundscape.layers[0].id,generation});soundEmpty=true;await ok('advance',{jobId:soundState.jobs[0].id});A.equal(soundState.jobs[0].status,'failed');A.equal(soundState.jobs[0].usage.characterCost,320);A.equal(soundState.jobs[0].actual,null);await ok('advance',{jobId:soundState.jobs[0].id});A.equal(soundCalls.length,1);
 setup();await ok('saveLayer',{layer:input});soundMissingKey=true;const before=structuredClone(soundState);A.equal((await request('generate',{batchId:D.id(),layerId:soundState.soundscape.layers[0].id,generation})).status,400);A.deepEqual(soundState,before);A.equal(soundCalls.length,0);soundMissingKey=false;soundState.limit='100';A.equal((await request('generate',{batchId:D.id(),layerId:soundState.soundscape.layers[0].id,generation})).status,400);A.equal(soundState.jobs.length,0);
});
await test('actual timeline anchors film/plan/scene layers and conflicts are explanatory, restore never approves',async()=>{
 setup();const p=soundState,plan={id:D.id(),stage:5,title:'План',variants:[],sourceShot:{scriptId:'script',title:'План',shotId:'shot'}},video={...plan,id:D.id(),stage:7};p.items.push(plan,video);
 const layer=S.saveSoundLayer(p,{...input,scope:{type:'plan',itemId:plan.id},settings:{loop:true,offset:.5,volume:.5,speechVolume:.05,fadeIn:0,fadeOut:0}});const v={id:D.id(),assetId:D.id(),mime:'audio/mpeg',model:'Uploaded',created:D.now(),prompt:'',seconds:1};layer.variants.push(v);S.chooseSoundVariant(p,layer.id,v.id);S.approveSoundLayer(p,layer.id);S.soundscape(p).enabled=true;
 const timeline={seconds:6,clips:[{itemId:video.id,shotId:'shot',sceneId:'scene',offset:2,duration:3}]},mix=S.buildSoundscapeMix(p,timeline);A.equal(mix[0].start,2.5);A.equal(mix[0].duration,2.5);A.equal(p.seconds,50,'Initial brief target never constrains sound montage');A(S.soundscapeFilter(mix,[{offset:3,duration:1}],2).filter.includes('[2:a]'));A.throws(()=>S.buildSoundscapeMix(p,timeline,{[v.assetId]:1.3}),/длительность файла изменилась/);
 layer.settings.duration=3;S.approveSoundLayer(p,layer.id);A.throws(()=>S.buildSoundscapeMix(p,timeline),/осталось 2.50/);layer.settings.duration=null;S.approveSoundLayer(p,layer.id);S.removeSoundVariant(p,layer.id,v.id);A.equal(layer.approvedId,undefined);A(projectAssetIds(p).has(v.assetId));A(!projectAssetIds(p).has(layer.id));A(!projectAssetIds(p).has(plan.id));S.removeSoundVariant(p,layer.id,v.id,true);A.equal(layer.selectedId,undefined);A.equal(layer.approvedId,undefined);
 const layer2=S.saveSoundLayer(p,{...input,name:'Сцена',scope:{type:'film'}});layer2.variants.push({...v,id:D.id(),seconds:2});soundAssets.set(v.assetId,{owner:'owner',projectId:p.id,mime:'audio/mpeg'});S.chooseSoundVariant(p,layer2.id,layer2.variants[0].id);await ok('approveReady',{measurements:[{layerId:layer2.id,variantId:layer2.selectedId,seconds:2}]});A.equal(soundState.soundscape.layers.find(l=>l.id===layer2.id).approvedId,layer2.selectedId);
});
console.log(`PASS ${groups} soundscape pure/UI/real-route/provider/runner mock groups. No paid requests.`);
