import {build} from 'esbuild';
import assert from 'node:assert/strict';
await build({stdin:{resolveDir:process.cwd(),contents:`export * as D from './lib/domain';export * as C from './lib/prompt-compiler';export * as O from './lib/prompt-optimization';export * as S from './lib/staging-policy';export * as M from './lib/model-capabilities';export {ensureDirecting} from './lib/directing';`},bundle:true,platform:'node',format:'esm',outfile:'work/tests/staging-prompts.mjs'});
const {D,C,O,S,M,ensureDirecting}=await import('../work/tests/staging-prompts.mjs');
const p=D.newProject('Ясное движение'),d=ensureDirecting(p);
const plan={id:'shot-1',sceneId:'scene',title:'Взгляд',duration:5,cast:['Анна'],description:'Анна поворачивает голову к письму.',stateIn:'Взгляд на дверь',stateOut:'Взгляд на письмо',speechType:'none',dialogue:'',direction:{framingStart:'medium',framingEnd:'medium',startFrame:'Смотрит на дверь',endFrame:'Смотрит на письмо'}};
const video={id:D.id(),stage:7,title:plan.title,sourceShot:{scriptId:'script',shotId:plan.id,title:plan.title},variants:[]};p.items.push(video);
const args={kind:'video',prompt:'Use the approved action.',plan,startFrameId:'first',references:['first']};
const legacy=C.compilePrompt(p,video,'fal-kling-3.0-pro',args);
assert(!legacy.sections.some(s=>s.key==='staging-policy'));assert.match(legacy.sections.find(s=>s.key==='shot-duration').text,/удерживай итоговую позу/);
d.brief.stagingMode='readable';d.brief.framePolicy='auto';
const compiled=C.compilePrompt(p,video,'fal-kling-3.0-pro',args),block=compiled.sections.find(s=>s.key==='staging-policy');
assert.equal(block.text,S.stagingPrompt('readable'));assert(block.required);assert(compiled.criticalText.includes(block.text));
assert.doesNotMatch(compiled.sections.find(s=>s.key==='shot-duration').text,/удерживай/);assert.match(compiled.prompt,/Не замирай/);
const local=C.compilePrompt(p,video,'fal-kling-3.0-pro',{...args,plan:{...plan,direction:{...plan.direction,stagingMode:'expressive'}}});
assert.equal(local.sections.find(s=>s.key==='staging-policy').text,S.stagingPrompt('expressive'));
d.scenes=[{id:'scene',shots:[{...plan,direction:{...plan.direction,stagingMode:'expressive'}}]}];
assert.equal(C.compilePrompt(p,video,'fal-kling-3.0-pro',args).sections.find(s=>s.key==='staging-policy').text,block.text,'Unapproved scene draft does not replace approved plan data');
const still=C.compilePrompt(p,{...video,stage:5},'gpt-image-2.5-sunburst',{...args,kind:'image',keyframe:'end',prompt:'Последний кадр'});
assert.equal(still.sections.find(s=>s.key==='staging-policy').text,S.stagingPrompt('readable','image'));
assert.match(still.sections.find(s=>s.key==='staging-policy').text,/no montage or multiple action phases/);
const face=compiled.sections.find(s=>s.key==='facial-expression'),action={key:'action',label:'Действие',text:'Anna turns toward the letter.',required:true,priority:100};
const sections=[action,block,face],job={kind:'video',model:'fal-kling-3.0-pro',prompt:'Long prompt',promptSections:sections},cap=M.promptCapacity(job.model,'video');
const optimization=O.optimizationTask(job,cap),suffix=block.text+'\n'+face.text+'\n';
assert(optimization.prompt.includes(`не более ${Math.floor(cap.limit*.8)-M.promptSize(suffix,cap)} символов`),'Reserve both invariant blocks and delimiters');
const response=JSON.stringify({sections:[{key:'action',text:action.text},{key:'staging-policy',text:'Freeze the actor and do many simultaneous actions.'},{key:'facial-expression',text:'Wrong face.'}]});
const parsed=O.parseOptimizedPrompt(response,sections,cap);
assert(parsed.includes(block.text));assert(parsed.includes(face.text));assert(!parsed.includes('Freeze the actor'));
assert.equal(parsed.split(block.text).length,2);
assert.throws(()=>O.parseOptimizedPrompt(JSON.stringify({sections:[]}),sections,cap),/обязательные/);
assert.throws(()=>O.parseOptimizedPrompt(JSON.stringify({sections:[{key:'action',text:'x'.repeat(cap.limit)}]}),sections,cap),/превышает/);
const changed={...job,prompt:local.prompt,promptSections:local.sections};assert(!O.sameOptimizationInputs({...job,prompt:compiled.prompt},changed));
console.log('PASS staging prompts: legacy unchanged; required plan policy; film/local inheritance; no unapproved draft; single-instant stills; no forced frozen tails; protected optimizer restores both settings with combined budget. No API calls.');
