import {build} from 'esbuild';
import {strict as assert} from 'node:assert';
await build({entryPoints:['lib/voices.ts'],bundle:true,format:'esm',platform:'node',outfile:'work/tests/voices.mjs'});
const {voiceCatalog,isRussianVoice}=await import('../work/tests/voices.mjs');
const calls=[];const original=globalThis.fetch;
globalThis.fetch=async(url,init)=>{calls.push({url,init});return Response.json({base_resp:{status_code:0},system_voice:[{voice_id:'English_Friendly',voice_name:'Friendly',description:['Friendly voice']},{voice_id:'Russian_Calm',voice_name:'Calm',description:['Calm Russian voice']}],voice_cloning:[{voice_id:'custom'}],voice_generation:[{voice_id:'design',description:['Created voice']}]});};
const mm=await voiceCatalog('minimax','test-key');assert.equal(mm.voices.length,1);assert.equal(mm.voices[0].id,'Russian_Calm');assert.equal(calls[0].init.headers.Authorization,'Bearer test-key');assert.deepEqual(JSON.parse(calls[0].init.body),{voice_type:'all'});assert.equal(calls[0].init.redirect,'manual');assert.equal(mm.nextCursor,'');
const expandedMM=await voiceCatalog('minimax','test-key','','all');assert.equal(expandedMM.voices.length,4);
assert.equal(expandedMM.voices.find(v=>v.id==='custom').russian,false);assert.equal(expandedMM.voices.find(v=>v.id==='Russian_Calm').russian,true);
globalThis.fetch=async(url,init)=>{calls.push({url,init});return Response.json({voices:[{voice_id:'v1',name:'Name',labels:{gender:'female',description:'soft',language:'ru'}},{voice_id:'v1',name:'Duplicate',description:'Warm',verified_languages:[{language:'ru'}]},{voice_id:'english',labels:{language:'en'}},{voice_id:'unknown',name:'Русское имя без указанного языка'}],has_more:true,next_page_token:'page & 2'});};
const el=await voiceCatalog('elevenlabs','test-key');assert.equal(el.voices.length,1);assert.equal(el.nextCursor,'page & 2');assert.equal(calls.at(-1).init.headers['xi-api-key'],'test-key');
const expandedEL=await voiceCatalog('elevenlabs','test-key','','all');assert.equal(expandedEL.voices.length,3);assert(expandedEL.voices.some(v=>v.id==='unknown'&&!v.russian));
globalThis.fetch=async(url,init)=>{calls.push({url,init});return Response.json({voices:[],has_more:false})};await voiceCatalog('elevenlabs','test-key',el.nextCursor);assert(calls.at(-1).url.includes('page%20%26%202'));
globalThis.fetch=async()=>Response.json({base_resp:{status_code:1004,status_msg:'secret test-key'}});await assert.rejects(()=>voiceCatalog('minimax','test-key'),e=>!e.message.includes('test-key'));
globalThis.fetch=async()=>new Response('secret test-key',{status:401});await assert.rejects(()=>voiceCatalog('minimax','test-key'),e=>e.message.includes('401')&&!e.message.includes('test-key'));
globalThis.fetch=async()=>new Response(null,{status:302,headers:{location:'https://wrong.example'}});await assert.rejects(()=>voiceCatalog('elevenlabs','test-key'),/302/);
globalThis.fetch=async()=>Response.json({voices:[],has_more:true,next_page_token:'same'});await assert.rejects(()=>voiceCatalog('elevenlabs','test-key','same'),/страницу/);
globalThis.fetch=original;
assert(isRussianVoice({language:'ru-RU'},'minimax'));assert(isRussianVoice({labels:{language:'Russian'}},'elevenlabs'));assert(isRussianVoice({verified_languages:[{language:'en'},{language:'ru'}]},'elevenlabs'));
assert(!isRussianVoice({voice_id:'Belarusian_voice'},'minimax'));assert(!isRussianVoice({description:'Not Russian',language:'en'},'elevenlabs'));assert(!isRussianVoice({voice_id:'custom'},'minimax'));
console.log('PASS Russian-only voice catalogs: language metadata, MiniMax IDs, unknown/foreign exclusion, pagination, deduplication and safe errors. No paid requests.');
