import {build} from 'esbuild';
import {strict as A} from 'node:assert';
const server=`
export class HttpError extends Error{constructor(message,status=400){super(message);this.status=status;}}
export async function owner(){if(globalThis.voiceUnauthorized)throw new HttpError('Войдите',401);return 'owner';}
export async function loadProject(user,id){if(user!=='owner'||id!==globalThis.voiceState.id)throw new HttpError('Проект не найден',404);return structuredClone(globalThis.voiceState);}
export async function saveProject(user,p,rev){if(user!=='owner'||p.id!==globalThis.voiceState.id)throw new HttpError('Проект не найден',404);if(globalThis.voiceConflict){globalThis.voiceConflict=false;globalThis.voiceState.revision++;throw new HttpError('Проект изменился',409);}if(rev!==globalThis.voiceState.revision)throw new HttpError('Проект изменился',409);p.revision=rev+1;globalThis.voiceState=structuredClone(p);return p;}
export async function mutate(user,id,fn){for(let n=0;n<5;n++){const p=await loadProject(user,id),rev=p.revision;fn(p);try{return await saveProject(user,p,rev);}catch(e){if(e.status!==409||n===4)throw e;}}}
export async function getKey(){globalThis.voiceKeyReads++;return globalThis.voiceSecret;}
export async function storeAsset(user,id,name,mime,bytes,projectId){if(globalThis.voiceFailStore){globalThis.voiceFailStore=false;throw Error('Файл не сохранился');}if(user!=='owner'||projectId!==globalThis.voiceState.id)throw Error('Ownership');globalThis.voiceAssets.set(id,{mime,bytes:new Uint8Array(bytes),projectId});return id;}
export const runtime={FILES:{async put(key,bytes){globalThis.voiceFiles.set(key,new Uint8Array(bytes));},async get(key){const bytes=globalThis.voiceFiles.get(key);return bytes?{async arrayBuffer(){return bytes.slice().buffer;}}:null;}}};
export function api(fn){return async(req,ctx)=>{try{return await fn(req,ctx);}catch(e){return Response.json({error:e.message},{status:e.status??400});}}}
`;
const providers=`export async function generate(j){globalThis.voiceAgentCalls.push(structuredClone(j));return {text:JSON.stringify(globalThis.voiceAgentResult),requestId:'agent-receipt',actual:'37',usage:{inputTokens:7,outputTokens:9}};}`;
await build({stdin:{resolveDir:process.cwd(),contents:`export * as D from './lib/domain';export * as V from './lib/voice-direction';export * as W from './lib/voice-design';export * as R from './lib/voice-design-runner';export {POST} from './app/api/projects/[id]/voice-design/route';`},bundle:true,platform:'node',format:'esm',outfile:'work/tests/voice-design.mjs',external:['@ffmpeg/ffmpeg'],plugins:[{name:'mock-voice-workflow',setup(b){b.onResolve({filter:/^(?:@\/lib|\.)\/(server|providers)$/},args=>({path:args.path.endsWith('server')?'server':'providers',namespace:'mock'}));b.onLoad({filter:/.*/,namespace:'mock'},args=>({contents:args.path==='server'?server:providers}));}}]});
const {D,V,W,R,POST}=await import('../work/tests/voice-design.mjs');
let groups=0;const pass=s=>{groups++;console.log('PASS voice design: '+s);};
globalThis.voiceSecret='mock-voice-secret-ALWAYS-HIDDEN';
function setup(){globalThis.voiceState=D.newProject('Новые голоса');globalThis.voiceState.limit=null;globalThis.voiceFiles=new Map();globalThis.voiceAssets=new Map();globalThis.voiceCalls=[];globalThis.voiceKeyReads=0;globalThis.voiceAgentCalls=[];globalThis.voiceUnauthorized=false;globalThis.voiceConflict=false;globalThis.voiceFailStore=false;globalThis.voiceHold=null;globalThis.voiceRelease=null;globalThis.voiceRemoteError=null;globalThis.voiceMalformed=false;globalThis.voicePreviewSerial=0;globalThis.voiceAgentResult={delivery:{emotion:'surprised',speed:1.05,intention:'Заметить чудо'},notes:['Поддерживает реакцию']};}
const phrase='Я заметил золотую корону у самой воды. Теперь я осторожно подойду поближе, чтобы не испугать нового друга и понять, что случилось.';
const input={provider:'elevenlabs',name:'Тёплый рассказчик',description:'Тёплый взрослый русский голос с мягкой выразительной дикцией и лёгкой иронией.',previewText:phrase,model:'eleven_ttv_v3',variants:1};
const send=(action,data,revision=voiceState.revision,id=voiceState.id)=>POST(new Request('http://local',{method:'POST',body:JSON.stringify({action,data,revision})}),{params:Promise.resolve({id})});
const ok=async(action,data,rev)=>{const response=await send(action,data,rev);A.equal(response.status,200,await response.clone().text());return response.json();};
globalThis.fetch=async(url,options)=>{
  const body=JSON.parse(options.body);voiceCalls.push({url,body});A(voiceState.jobs.some(j=>j.purpose==='voice-design'&&j.status==='dispatching'),'Every API request must already have a persisted claimed job');
  if(voiceHold)await voiceHold;if(voiceRemoteError)throw Error(voiceRemoteError);
  const requestId='voice-request-'+voiceCalls.length;
  if(url.includes('/voice_design'))return Response.json({voice_id:'mm-designed-'+(++voicePreviewSerial),trial_audio:'aa55bb66',base_resp:{status_code:0,status_msg:'success'}},{headers:{'request-id':requestId}});
  if(url.includes('/design'))return Response.json({previews:voiceMalformed?[{generated_voice_id:'malformed',audio_base_64:'?',media_type:'audio/mpeg'}]:Array.from({length:3},(_,n)=>({generated_voice_id:'eleven-preview-'+n,audio_base_64:'qrvM3Q==',media_type:'audio/mpeg',duration_secs:4+n,language:'ru'})),text:body.text,usage:{cost_in_usd_ticks:'100'}},{headers:{'request-id':requestId}});
  A.equal(url,'https://api.elevenlabs.io/v1/text-to-voice');return Response.json({voice_id:'eleven-saved-voice',name:body.voice_name},{headers:{'request-id':requestId}});
};
setup();
const before=structuredClone(voiceState);let response=await send('design',{batchId:D.id(),input:{...input,previewText:'коротко'}});A.equal(response.status,400);A.deepEqual(voiceState,before);A.equal(voiceCalls.length,0);response=await send('design',{batchId:D.id(),input},-1);A.equal(response.status,409);A.deepEqual(voiceState,before);voiceUnauthorized=true;response=await send('design',{batchId:D.id(),input});A.equal(response.status,401);voiceUnauthorized=false;response=await send('saveDelivery',{itemId:D.id(),delivery:{speed:1}});A.equal(response.status,400);A.deepEqual(voiceState,before);pass('local input, owner/project and revision guards reject before any paid request or canonical mutation');
const batch=D.id();await ok('design',{batchId:batch,input});const design=voiceState.voiceStudio.designs[0],job=W.voiceWorkflowJobs(voiceState)[0];A.equal(job.status,'queued');A.equal(job.actual,null);A.equal(voiceCalls.length,0);await ok('design',{batchId:batch,input},0);A.equal(voiceState.jobs.length,1);await ok('advance',{jobId:job.id});A.equal(voiceCalls.length,1);A.equal(voiceCalls[0].body.model_id,'eleven_ttv_v3');A.equal(voiceCalls[0].body.text,phrase);A.equal(voiceState.voiceStudio.designs[0].previews.length,3);A.equal(voiceAssets.size,3);A.equal(voiceState.voiceStudio.designs[0].selectedPreviewId,undefined);A.equal(voiceState.voiceStudio.profiles.length,0);A.equal(voiceState.jobs[0].actual,'100');A.equal(voiceState.jobs[0].requestId,'voice-request-1');A(!JSON.stringify(voiceState).includes('audio_base_64'));A(!JSON.stringify(voiceState).includes(voiceSecret));await ok('advance',{jobId:job.id});A.equal(voiceCalls.length,1);pass('ElevenLabs exact API payload, persisted multi-preview owned files, actual receipt, no base64 in project, no automatic selection or retry');
const currentDesign=voiceState.voiceStudio.designs[0],preview=currentDesign.previews[1];const approvalBefore=voiceState.items.map(i=>[i.id,i.selectedId,i.approvedId]);await ok('selectPreview',{designId:currentDesign.id,previewId:preview.id});await ok('saveVoice',{batchId:D.id(),designId:currentDesign.id});A.equal(voiceCalls.length,1,'Saving is queued separately');const save=W.voiceWorkflowJobs(voiceState).find(j=>j.voiceWorkflow.input.operation==='save');await ok('selectPreview',{designId:currentDesign.id,previewId:currentDesign.previews[2].id});await ok('advance',{jobId:save.id});A.equal(voiceCalls[1].body.generated_voice_id,preview.generatedVoiceId,'Save pins the actually chosen preview at admission');A.equal(voiceState.voiceStudio.profiles[0].voiceId,'eleven-saved-voice');A.equal(voiceState.voiceStudio.profiles[0].previewAssetId,preview.assetId);A.equal(voiceState.voiceStudio.selectedProfileId,undefined);A.deepEqual(voiceState.items.map(i=>[i.id,i.selectedId,i.approvedId]),approvalBefore);await ok('saveVoice',{batchId:D.id(),designId:currentDesign.id});await ok('advance',{jobId:save.id});A.equal(voiceCalls.length,2);pass('explicit create/save pins chosen preview, persists reusable voice without changing profile choice or film approvals, idempotent success');
setup();const mmInput={...input,provider:'minimax',model:undefined,variants:3,previewText:'Вот она, золотая корона. Я помогу тебе.'};A.equal(W.voiceDesignEstimate(mmInput),(BigInt(mmInput.previewText.length)*300000n).toString());await ok('design',{batchId:D.id(),input:mmInput});A.equal(voiceState.jobs.length,3);for(const j of [...voiceState.jobs])await ok('advance',{jobId:j.id});A.equal(voiceCalls.length,3);A(voiceCalls.every(c=>Object.keys(c.body).sort().join(',')==='preview_text,prompt'));A(voiceState.jobs.every(j=>j.actual===null&&j.status==='done'));const mmDesign=voiceState.voiceStudio.designs[0];A.equal(mmDesign.previews.length,3);await ok('selectPreview',{designId:mmDesign.id,previewId:mmDesign.previews[0].id});await ok('saveVoice',{batchId:D.id(),designId:mmDesign.id});A.equal(voiceCalls.length,3,'MiniMax has no additional create/save endpoint');A.equal(voiceState.voiceStudio.profiles[0].voiceId,'mm-designed-1');pass('MiniMax documented hex preview contract, three separate attempts and server tariff estimates, explicit project save makes no extra API request');
setup();voiceState.limit='1';const limited=structuredClone(voiceState);response=await send('design',{batchId:D.id(),input:mmInput});A.equal(response.status,400);A.deepEqual(voiceState,limited);A.equal(voiceCalls.length,0);pass('aggregate batch budget is validated atomically before queue admission');
setup();await ok('design',{batchId:D.id(),input});const concurrentJob=voiceState.jobs[0].id;voiceHold=new Promise(resolve=>voiceRelease=resolve);const consumers=[R.runVoiceWorkflowStep('owner',voiceState.id,concurrentJob),R.runVoiceWorkflowStep('owner',voiceState.id,concurrentJob)];await new Promise(r=>setTimeout(r,5));A.equal(voiceCalls.length,1);voiceRelease();await Promise.all(consumers);A.equal(voiceCalls.length,1);A.equal(voiceState.jobs[0].status,'done');pass('two concurrent consumers claim with CAS and send one paid request');
setup();await ok('design',{batchId:D.id(),input});voiceRemoteError='connection dropped '+voiceSecret;await ok('advance',{jobId:voiceState.jobs[0].id});A.equal(voiceState.jobs[0].status,'unknown');A.equal(voiceState.jobs[0].actual,null);await ok('advance',{jobId:voiceState.jobs[0].id});A.equal(voiceCalls.length,1);A(!JSON.stringify(voiceState).includes(voiceSecret));pass('uncertain transport outcome is unknown, not zero-cost; repeated advance never resubmits and errors contain no key');
setup();await ok('design',{batchId:D.id(),input});voiceFailStore=true;await ok('advance',{jobId:voiceState.jobs[0].id});A.equal(voiceState.jobs[0].status,'saving');A.equal(voiceState.jobs[0].actual,'100');A.equal(voiceState.jobs[0].requestId,'voice-request-1');await ok('advance',{jobId:voiceState.jobs[0].id});A.equal(voiceState.jobs[0].status,'done');A.equal(voiceAssets.size,3);A.equal(voiceCalls.length,1,'Recovery uses staged private files, never provider regeneration');pass('file-save failure keeps receipt and private staged bytes; explicit recovery stores files with no new paid call');
setup();await ok('design',{batchId:D.id(),input});voiceMalformed=true;await ok('advance',{jobId:voiceState.jobs[0].id});A.equal(voiceState.jobs[0].status,'failed');A.equal(voiceState.jobs[0].actual,'100');A.equal(voiceState.jobs[0].requestId,'voice-request-1');await ok('advance',{jobId:voiceState.jobs[0].id});A.equal(voiceCalls.length,1);pass('malformed successful provider response retains actual receipt/cost and never retries automatically');
setup();await ok('design',{batchId:D.id(),input});const lateJob=voiceState.jobs[0].id;voiceHold=new Promise(resolve=>voiceRelease=resolve);const flight=R.runVoiceWorkflowStep('owner',voiceState.id,lateJob);await new Promise(r=>setTimeout(r,5));await ok('stop',{jobId:lateJob});A.equal(voiceState.jobs[0].status,'unknown');voiceRelease();await flight;A.equal(voiceState.jobs[0].voiceWorkflow.late,true);A.equal(voiceState.voiceStudio.designs[0].previews.length,3);A.equal(voiceState.voiceStudio.profiles.length,0);A.equal(voiceState.voiceStudio.designs[0].selectedPreviewId,undefined);pass('manual stop preserves late previews and receipt without selecting, saving or approving a voice');
setup();const speech=voiceState.items.find(i=>i.stage===6),variant=D.makeVariant(voiceState,speech,{kind:'audio',assetId:D.id(),dialogue:'Я заметил корону.',voiceId:'old-voice',model:'speech-2.8-hd'});speech.variants.push(variant);speech.selectedId=variant.id;speech.approvedId=variant.id;await ok('proposeDelivery',{batchId:D.id(),itemId:speech.id,model:'grok-4.6',instruction:'Передай удивление'});const agent=voiceState.jobs[0],frozen=agent.prompt;voiceState.items.find(i=>i.id===speech.id).variants[0].dialogue='Теперь другой текст.';await ok('advance',{jobId:agent.id});A.equal(voiceAgentCalls[0].prompt,frozen);A.equal(voiceState.voiceStudio.candidates.length,1);A.equal(voiceState.voiceStudio.deliveries[speech.id],undefined);A.equal(voiceState.jobs[0].actual,'37');response=await send('applyDelivery',{candidateId:voiceState.voiceStudio.candidates[0].id});A.equal(response.status,400);voiceState.items.find(i=>i.id===speech.id).variants[0].dialogue='Я заметил корону.';await ok('applyDelivery',{candidateId:voiceState.voiceStudio.candidates[0].id});A.equal(voiceState.voiceStudio.deliveries[speech.id].emotion,'surprised');A.equal(voiceState.items.find(i=>i.id===speech.id).approvedId,variant.id);pass('agent uses frozen full prompt and cost; proposal applies only explicitly to unchanged spoken text, preserving existing audio approval');
setup();await ok('design',{batchId:D.id(),input});await ok('advance',{jobId:voiceState.jobs[0].id});const lateSaveDesign=voiceState.voiceStudio.designs[0];await ok('selectPreview',{designId:lateSaveDesign.id,previewId:lateSaveDesign.previews[0].id});await ok('saveVoice',{batchId:D.id(),designId:lateSaveDesign.id});const lateSave=voiceState.jobs.find(j=>j.voiceWorkflow.input.operation==='save');voiceHold=new Promise(resolve=>voiceRelease=resolve);const saveFlight=R.runVoiceWorkflowStep('owner',voiceState.id,lateSave.id);await new Promise(r=>setTimeout(r,5));await ok('stop',{jobId:lateSave.id});voiceRelease();await saveFlight;A.equal(voiceState.jobs.find(j=>j.id===lateSave.id).voiceWorkflow.savedVoiceId,'eleven-saved-voice');A.equal(voiceState.voiceStudio.profiles.length,0);A.equal(voiceCalls.length,2);await ok('importSavedVoice',{jobId:lateSave.id});A.equal(voiceState.voiceStudio.profiles.length,1);A.equal(voiceState.voiceStudio.selectedProfileId,undefined);await ok('importSavedVoice',{jobId:lateSave.id});await ok('advance',{jobId:lateSave.id});A.equal(voiceState.voiceStudio.profiles.length,1);A.equal(voiceCalls.length,2);pass('late paid create result remains separately importable; explicit repeated import is local and never selects or regenerates');
setup();const malformedSpeech=voiceState.items.find(i=>i.stage===6),malformedVariant=D.makeVariant(voiceState,malformedSpeech,{kind:'audio',assetId:D.id(),dialogue:'Я заметил корону.',voiceId:'old-voice',model:'speech-2.8-hd'});malformedSpeech.variants.push(malformedVariant);malformedSpeech.selectedId=malformedVariant.id;await ok('proposeDelivery',{batchId:D.id(),itemId:malformedSpeech.id,model:'grok-4.6',instruction:'Передай удивление'});voiceAgentResult={delivery:{pauses:[{after:'Не существует',seconds:.4}]},notes:[]};await ok('advance',{jobId:voiceState.jobs[0].id});A.equal(voiceState.jobs[0].status,'failed');A.equal(voiceState.jobs[0].actual,'37');A.equal(voiceState.jobs[0].requestId,'agent-receipt');A(voiceState.jobs[0].output.text.includes('Не существует'));A.equal(V.readVoiceStudio(voiceState).candidates.length,0);await ok('advance',{jobId:voiceState.jobs[0].id});A.equal(voiceAgentCalls.length,1);pass('invalid agent pause keeps the paid receipt and raw answer, admits no candidate and is never automatically retried');
setup();const castingItem=voiceState.items.find(i=>i.stage===6),castingAudio=D.makeVariant(voiceState,castingItem,{kind:'audio',assetId:D.id(),dialogue:'Привет!',voiceId:'old'});castingItem.variants.push(castingAudio);castingItem.selectedId=castingAudio.id;castingItem.approvedId=castingAudio.id;const castingProfile=W.saveVoiceProfile(voiceState,{name:'Персонаж',description:'',provider:'elevenlabs',voiceId:'designed',delivery:{speed:1}});await ok('chooseProfile',{profileId:castingProfile.id});A.deepEqual(voiceState.preferredVoice,{model:'eleven_v3',voiceId:'designed',name:'Персонаж'});await ok('assignProfile',{itemId:castingItem.id,profileId:castingProfile.id});A.equal(voiceState.voiceStudio.castings[castingItem.id],castingProfile.id);const castingSaved=structuredClone(voiceState);response=await send('assignProfile',{itemId:castingItem.id,profileId:D.id()});A.equal(response.status,400);A.deepEqual(voiceState,castingSaved);await ok('removeProfile',{profileId:castingProfile.id});A.equal(voiceState.preferredVoice,undefined);A.equal(voiceState.voiceStudio.castings[castingItem.id],undefined);await ok('restoreProfile',{profileId:castingProfile.id});A.equal(voiceState.voiceStudio.selectedProfileId,undefined);A.equal(voiceState.voiceStudio.castings[castingItem.id],undefined);A.equal(voiceState.items.find(i=>i.id===castingItem.id).approvedId,castingAudio.id);A.equal(voiceCalls.length,0);pass('explicit profile choice updates standard generation defaults, per-plan casting is owned, delete/restore never reassigns or reapproves recordings');
console.log('PASS '+groups+' voice design route/provider/runner groups. All HTTP, provider, files and CAS responses mocked; no paid calls.');
