'use client';
import {useState} from 'react';
import type {Project,Variant} from '../lib/domain';
import type {AnimaticManifest} from '../lib/animatic-manifest';
export function AnimaticTimeline({p,busy,save,jump}:{p:Project;busy:boolean;save:(value:{sound:'silent'|'voices';music:boolean;motion:boolean})=>Promise<unknown>;jump:(id:string)=>void}){
 const value=(p as Project&{animaticSettings?:{sound:'silent'|'voices';music?:boolean;motion?:boolean}}).animaticSettings;
 const [error,setError]=useState('');
 const v=p.animatic?.variants.find(v=>v.id===p.animatic?.selectedId) as (Variant&{animaticManifest?:AnimaticManifest})|undefined,m=v?.animaticManifest;
 async function change(patch:Partial<{sound:'silent'|'voices';music:boolean;motion:boolean}>){setError('');try{await save({sound:value?.sound??'voices',music:value?.music??false,motion:value?.motion??false,...patch});}catch(e){setError((e as Error).message);}}
 return <section className="editor-surface p-5 space-y-4" aria-label="Настройки и состав аниматика"><h2>Просмотр постановки</h2><label>Звук <select disabled={busy} value={value?.sound??'voices'} onChange={e=>void change({sound:e.target.value as 'silent'|'voices'})}><option value="voices">Выбранная озвучка</option><option value="silent">Без речи · сначала проверяем изображение</option></select></label><label className="row"><input type="checkbox" disabled={busy} checked={value?.motion??false} onChange={e=>void change({motion:e.target.checked})}/>Схематическое движение камеры</label><p className="muted">Наезд и панорама показываются как движение по картинке. Начальное и конечное состояния показаны отдельными исходными кадрами. Это предварительная постановка, движения персонажей появятся в видео.</p><label className="row"><input type="checkbox" disabled={busy} checked={value?.music??false} onChange={e=>void change({music:e.target.checked})}/>Добавить утверждённую музыку</label>{error&&<p role="alert">{error}</p>}
 {m?<><h3>Состав выбранного аниматика · {m.seconds.toFixed(2)} сек</h3><p>Для видео сохраняются исходные изображения этого просмотра.</p><div className="space-y-4">{m.clips.map(c=><article className="border rounded p-3" key={c.itemId}><button type="button" onClick={()=>jump(c.itemId)}>{c.title} · {c.offset.toFixed(2)}–{(c.offset+c.duration).toFixed(2)} сек</button><p>{c.direction?.framingStart} → {c.direction?.framingEnd} · {c.direction?.cameraMovement?.type}</p><div className="row wrap">{c.frames.map(f=><figure key={f.role}><img src={'/api/assets/'+f.assetId} alt={`${c.title}: ${f.role==='start'?'начало':f.role==='end'?'окончание':'середина'}`} style={{width:180,aspectRatio:'16/9',objectFit:'contain'}}/><figcaption>{f.role==='start'?'Начало':f.role==='end'?'Окончание':'Середина'} · {f.duration.toFixed(2)} сек</figcaption></figure>)}</div></article>)}</div></>:<p>Соберите новый аниматик, чтобы сохранить его кадры и таймлайн. Прежние файлы доступны в истории.</p>}</section>;
}
