'use client';
import {useRef,useState} from 'react';
import type {Project} from '@/lib/domain';
import {currentAudioQc,makeAudioQcSource,type AudioQcReport} from '@/lib/audio-qc';
import {measureFilmAudio} from '@/lib/audio-qc-browser';
import {Button} from '@/components/ui/button';
export type AudioQcEditorProps={p:Project;itemId:string;variantId:string;busy:boolean;onSave:(report:AudioQcReport)=>Promise<void>;loadAsset?:(assetId:string,signal?:AbortSignal)=>Promise<Blob>};
export function AudioQcEditor({p,itemId,variantId,busy,onSave,loadAsset}:AudioQcEditorProps){
  const [working,setWorking]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');const controller=useRef<AbortController|null>(null),report=currentAudioQc(p,itemId,variantId);
  let sourceIssue='';try{makeAudioQcSource(p,itemId,variantId);}catch(e){sourceIssue=e instanceof Error?e.message:'Выберите готовый фильм.';}
  const run=async()=>{const abort=new AbortController();controller.current=abort;setWorking(true);setError('');try{const result=await measureFilmAudio(p,itemId,variantId,{signal:abort.signal,progress:setProgress,loadAsset});await onSave(result);setProgress('Технический отчёт сохранён. Его измерения доступны монтажному редактору.');}catch(e){setError(abort.signal.aborted?'Проверка остановлена. Файл и утверждения не изменены.':e instanceof Error?e.message:'Не удалось проверить звук.');}finally{setWorking(false);controller.current=null;}};
  return <section aria-label="Техническая проверка звука фильма" className="editor-surface p-4 space-y-3"><h3>Проверка звука готового фильма</h3><p className="text-sm">Локальный FFmpeg измерит дорожку, длительность, peak/RMS и участки тишины. До 10 минут и 256 МиБ. Платная модель не вызывается; реплики, громкость и утверждения не изменяются.</p><Button disabled={busy||working||!!sourceIssue} onClick={run}>Проверить звук файла</Button>{working&&<Button variant="outline" onClick={()=>controller.current?.abort()}>Остановить проверку</Button>}{sourceIssue&&<p className="text-sm">{sourceIssue}</p>}{progress&&<p role="status">{progress}</p>}{error&&<p role="alert">{error}</p>}
  {report&&<div className="space-y-2"><p>Файл {report.measurement.seconds.toFixed(2)} сек · {report.measurement.hasAudio?'аудиодорожка есть':'аудиодорожки нет'}</p>{report.measurement.hasAudio&&<p>Аудио {report.measurement.audioSeconds?.toFixed(2)??'не измерено'} сек · peak {report.measurement.peakDb===null?'−∞':report.measurement.peakDb.toFixed(2)} dBFS · RMS {report.measurement.rmsDb===null?'−∞':report.measurement.rmsDb.toFixed(2)} dBFS</p>}{report.measurement.issues.map((issue,n)=><p key={n}><strong>{issue.criterion}:</strong> {issue.evidence}</p>)}{report.measurement.silence.length>0&&<details><summary>Участки ниже порога · {report.measurement.silence.length}</summary>{report.measurement.silence.map((s,n)=><p key={n}>{s.start.toFixed(2)}–{s.end.toFixed(2)} сек ({s.duration.toFixed(2)} сек)</p>)}</details>}<details><summary>Измерения и пределы проверки</summary>{report.measurement.limitations.map((text,n)=><p key={n}>{text}</p>)}<p>Отчёт относится к этому выбранному файлу. Оценка речи и художественного баланса требует прослушивания.</p><pre className="whitespace-pre-wrap text-xs">{report.evidence.join('\n')}</pre></details></div>}
  </section>;
}
