'use client';
import {useState} from 'react';
import type {Project} from '@/lib/domain';
import {costReport,costReportCsv,formatCost,formatActualCost,COST_DIMENSIONS,COST_DIMENSION_NAMES,type CostDimension} from '@/lib/cost-report';
const STATUS_NAMES={queued:'В очереди',dispatching:'Отправка',pending:'Ожидание результата',saving:'Сохранение',done:'Готово',failed:'Ошибка',unknown:'Исход неизвестен',cancelled:'Отменено'};

export function CostReport({project}:{project:Project}){
  const [dimension,setDimension]=useState<CostDimension>('stage'),report=costReport(project,dimension);
  const download=()=>{const url=URL.createObjectURL(new Blob(['\uFEFF'+costReportCsv(project,dimension)],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`movie-costs-${project.id}-${dimension}.csv`;link.click();URL.revokeObjectURL(url);};
  return <section className="grid gap-4 rounded-xl border p-4" aria-label="Отчёт затрат">
    <div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">Затраты фильма</h3><button type="button" onClick={download} className="rounded border px-3 py-2">Скачать CSV</button></div>
    <p className="text-sm opacity-75">Факт — подтверждённые списания в USD. Резерв и оценки показаны отдельно. Удалённые материалы и архивный журнал включены в расходы.</p>
    <dl className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div><dt className="text-sm opacity-70">Подтверждено</dt><dd>{formatActualCost(report.total)}</dd></div><div><dt className="text-sm opacity-70">В резерве</dt><dd>{formatCost(report.total.reserved)}</dd></div><div><dt className="text-sm opacity-70">Без сверки списания</dt><dd>{report.total.unknown}</dd></div><div><dt className="text-sm opacity-70">Всего попыток</dt><dd>{report.total.attempts}</dd></div></dl>
    {report.total.unknown>0&&<p role="status" className="rounded border p-3 text-sm">Итоговые расходы пока неполные: у {report.total.unknown} попыток нет подтверждённого списания. Проверьте квитанции в журнале или кабинете провайдера.</p>}
    <label className="flex flex-wrap items-center gap-2 text-sm">Группировать по <select value={dimension} onChange={e=>setDimension(e.target.value as CostDimension)} className="rounded border bg-transparent p-2">{COST_DIMENSIONS.map(d=><option key={d} value={d}>{COST_DIMENSION_NAMES[d]}</option>)}</select></label>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{[COST_DIMENSION_NAMES[dimension],'Попыток','Факт','Оценка','Резерв','Без сверки','В архиве'].map(title=><th key={title} className="border-b px-2 py-2">{title}</th>)}</tr></thead><tbody>{report.groups.map(g=><tr key={g.id}><td className="px-2 py-2">{g.label}</td><td className="px-2 py-2">{g.attempts}</td><td className="px-2 py-2">{formatActualCost(g)}</td><td className="px-2 py-2">{formatCost(g.estimate)}</td><td className="px-2 py-2">{formatCost(g.reserved)}</td><td className="px-2 py-2">{g.unknown}</td><td className="px-2 py-2">{g.archived}</td></tr>)}</tbody></table>{report.groups.length===0&&<p className="py-3 text-sm opacity-70">В проекте пока нет платных попыток.</p>}</div>
    <details className="text-sm"><summary className="cursor-pointer">Квитанции и состояния попыток · {report.rows.length}</summary><div className="grid gap-3 pt-3">{report.rows.map(row=><article key={row.jobId} className="grid gap-1 rounded border p-3"><p>{row.model.label} · {row.role.label} · {row.plan.label}{row.archived?' · в архиве':''}</p><p>Факт: {formatCost(row.actual)} · оценка: {formatCost(row.estimate)} · {STATUS_NAMES[row.status]}</p><p className="break-all opacity-70">Попытка: {row.jobId}{row.requestId?` · запрос: ${row.requestId}`:''} · {row.created}</p>{row.actualSource&&<p>Источник: {row.actualSource}</p>}{row.estimatedCredits!=null&&<p>Оценка кредитов провайдера: {row.estimatedCredits}. Это не подтверждённая стоимость в USD.</p>}</article>)}</div></details>
  </section>;
}
