'use client';
import { useState,useEffect,useRef } from 'react';
import { CreativeStrengthControls,SceneCreativeControls,SceneCreativeSettings } from './creative-controls';
import {FacialExpressionControl} from './facial-expression-control';
import {CameraPolicyControl} from './camera-policy-control';
import {CAMERA_POLICY_LABELS} from '@/lib/camera-policy';
import {StagingModeControl,FramePolicyControl} from './staging-policy-controls';
import {STAGING_MODE_LABELS,FRAME_POLICY_LABELS} from '@/lib/staging-policy';
import {FACIAL_EXPRESSION_LABELS} from '@/lib/facial-expression';
import { GENRE_OPTIONS,renderCreativeInstructions } from '@/lib/creative-brief';
import {ShotDirectionEditor,ShotDirectionSummary,directionEditorIssues} from './shot-direction-editor';
import {SceneCausalEditor,SceneCausalSummary,NarrativeBeatSummary,sceneCausalText,sceneCausalIssues} from './emotional-causality-editor';
import {StoryMeaningPanel,MeaningLinks,MeaningSummary} from './story-meaning-panel';
import {MontageOperationPreview} from './montage-solutions';
import {BatchScopeSelector} from './batch-scope-selector';
import {directingReadiness,directingSceneCandidates,directingShotCandidates} from '@/lib/directing-workflow';
import {readableShotDirection} from '@/lib/shot-direction';
import { VersionComparison } from './version-comparison';
import {DirectorExecutionControls,DirectorRunStatus} from './director-execution-controls';
import type {DirectorExecution} from '@/lib/director-reliability';
import {allPlanSetsApproved,planSetApproved} from '@/lib/shot-planning';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import type { Project } from '@/lib/domain';
import { money } from '@/lib/domain';
import { MODELS } from '@/lib/models';
import {runtimeMode,plannedRuntime,runtimeAcceptanceBasis} from '@/lib/runtime-policy';
import { DEFAULT_BRIEF,DIRECTOR_PRESETS,ROLE_NAMES,directorPrompt,directorRunActive,EDITOR_SECTION_NAMES,shotApproved,scenesBasis,type EditorPatch,type Scene,type DirectingShot,type DirectorRole } from '@/lib/directing';

type Props={p:Project;stage:number;busy:boolean;submit:(action:string,data?:unknown)=>Promise<void>;open:(stage:number)=>void;generateScenario?:()=>void};
const F=({label,children}:{label:string;children:React.ReactNode})=><label className="block space-y-2"><span className="text-sm font-medium">{label}</span>{children}</label>;
export function DirectingEditor({p,stage,busy,submit,open,generateScenario}:Props){
  const d=p.directing;
  const [brief,setBriefState]=useState(d?.brief??{...DEFAULT_BRIEF,targetSeconds:Math.max(10,p.seconds)});
  const [briefDirty,setBriefDirty]=useState(false),draftVersion=useRef(0);
  const setBrief=(value:typeof brief)=>{draftVersion.current++;setBriefDirty(true);setBriefState(value);};
  const [order,setOrderState]=useState(p.productionOrder??'voice-first');
  const setOrder=(value:typeof order)=>{draftVersion.current++;setBriefDirty(true);setOrderState(value);};
  const savedBrief=JSON.stringify(d?.brief);useEffect(()=>{if(!briefDirty&&d){setBriefState(d.brief);setOrderState(p.productionOrder??'voice-first');}},[p.id,savedBrief,p.productionOrder,briefDirty]);
  const [model,setModel]=useState(MODELS.find(m=>m.kind==='text'&&m.provider==='openai')!.id);
  const [execution,setExecution]=useState<DirectorExecution>({});
  const [sceneId,setSceneId]=useState(d?.scenes[0]?.id??'');
  const [editing,setEditing]=useState<Scene>();
  const [shotEdit,setShotEdit]=useState<{sceneId:string;shot:DirectingShot}>();
  const [resolution,setResolution]=useState('');
  const [continuityText,setContinuityText]=useState('');
  const [castText,setCastText]=useState('');
  const [selectedSceneIds,setSelectedSceneIds]=useState(d?.scenes.map(s=>s.id)??[]);
  const [selectedShotIds,setSelectedShotIds]=useState<string[]>([]);
  const editScene=(scene:Scene)=>{setEditing(structuredClone(scene));setContinuityText(scene.continuity.map(c=>`${c.character} | ${c.outfit} | ${c.props}`).join('\n'));};
  const editShot=(sceneId:string,shot:DirectingShot)=>{setShotEdit({sceneId,shot:structuredClone(shot)});setCastText(shot.cast.join(', '));};
  const scenes=d?.scenes??[],scene=scenes.find(s=>s.id===sceneId)??scenes[0];
  const readiness=directingReadiness(p),pendingShotIds=readiness.pending.map(row=>row.shotId),readyShotIds=readiness.readyIds;
  const allShotsApproved=scenes.length>0&&scenes.every(s=>s.shots.length>0)&&pendingShotIds.length===0;
  const sceneRows=directingSceneCandidates(p,stage===12?'structure':'plans'),shotRows=directingShotCandidates(p,scene?.id);
  const selectedScenesReady=selectedSceneIds.filter(id=>sceneRows.some(row=>row.id===id&&!row.blocked));
  const allShotRows=directingShotCandidates(p),selectedShotsReady=selectedShotIds.filter(id=>allShotRows.some(row=>row.id===id&&!row.blocked));
  const sceneKey=p.id+':'+scenes.map(s=>s.id).join('|'),shotKey=p.id+':'+scenes.flatMap(s=>s.shots.map(shot=>shot.id)).join('|');
  useEffect(()=>{setSelectedSceneIds(ids=>{const current=ids.filter(id=>scenes.some(s=>s.id===id));return current.length?current:scenes.map(s=>s.id);});},[sceneKey]);
  useEffect(()=>{setSelectedShotIds(ids=>ids.filter(id=>scenes.some(s=>s.shots.some(shot=>shot.id===id))));},[shotKey]);
  const run=d?.runs.at(-1),running=!!run&&directorRunActive(run);
  const locked=busy||running;
  const seconds=plannedRuntime(p),timingAccepted=d?.acceptedRuntime?.basis===runtimeAcceptanceBasis(p);
  const call=(action:string,data?:unknown)=>submit(action,data);
  const generate=(mode:string,extra:Record<string,unknown>={})=>call('run',{model,execution,mode,...extra});
  const selectScene=(id:string,checked:boolean)=>setSelectedSceneIds(ids=>checked?[...new Set([...ids,id])]:ids.filter(v=>v!==id));
  const selectShot=(id:string,checked:boolean)=>setSelectedShotIds(ids=>checked?[...new Set([...ids,id])]:ids.filter(v=>v!==id));
  const roles:{id:DirectorRole;label:string}[]=[{id:'story',label:'Сценарий'},{id:'camera',label:'Оператор'},{id:'art',label:'Художник'},{id:'dialogue',label:'Реплики'},{id:'performance',label:'Актёрская работа'},{id:'scene-expressive-reviewer',label:'Выразительность сцены'}];
  const saveBrief=async()=>{const version=draftVersion.current;await call('brief',{brief,productionOrder:order});if(version===draftVersion.current)setBriefDirty(false);};
  const chooseHistory=async(versionId:string)=>{const v=p.creativeHistory?.find(v=>v.id===versionId),version=draftVersion.current;await call('restoreCreativeVersion',{versionId});if(v&&version===draftVersion.current){setBriefDirty(false);setBriefState(v.snapshot.brief);setOrderState(v.snapshot.productionOrder??'voice-first');}};
  const sceneText=(s:Scene)=>[s.title,`Задача: ${s.purpose}`,`Локация: ${s.location}`,`Конфликт: ${s.conflict}`,`Поворот: ${s.turn}`,`Начало: ${s.stateIn}`,`Конец: ${s.stateOut}`,sceneCausalText(s.causalChain),...s.continuity.map(c=>`${c.character}: ${c.outfit}; ${c.props}`),...s.shots.map(shot=>`${shot.title} · ${shot.duration} сек\n${shot.story}\nОператор: ${shot.cinematography}\nХудожник: ${shot.productionDesign}\nРечь: ${shot.dialogue.speaker}: ${shot.dialogue.text}\nПодача: ${shot.dialogue.delivery}\nНачало: ${shot.stateIn}\nКонец: ${shot.stateOut}${shot.direction?'\n'+readableShotDirection(shot.direction):''}`)].join('\n\n');
  const shotField=(key:keyof DirectingShot,value:unknown)=>setShotEdit(e=>e?{...e,shot:{...e.shot,[key]:value}}:e);
  const patchPreview=(patch:EditorPatch)=>{const target=scenes.find(s=>s.shots.some(v=>v.id===patch.shotId)),shot=target?.shots.find(s=>s.id===patch.shotId);return <details key={patch.id} className="border rounded p-3"><summary>{target?.title} · {shot?.title??'План'} · {EDITOR_SECTION_NAMES[patch.section]} {patch.applied&&'✓ Применено'}</summary><p>{patch.reason}</p><p className="whitespace-pre-wrap"><b>Было:</b> {patch.before||'Пусто'}</p><p className="whitespace-pre-wrap"><b>Предложение:</b> {patch.after||'Пусто'}</p></details>;};
  return <section className="editor-surface p-5 mb-6 space-y-5" aria-label="Команда сценаристов и режиссёров">
    <div className="row spread wrap"><div><div className="eyebrow">РЕЖИССЁРСКАЯ ГРУППА</div><h2>{stage===0?'Творческое задание':stage===12?'Структура сцен':'Проработка всех планов'}</h2></div>
      {stage!==0&&<F label="Модель команды"><select className="rounded border p-2 bg-background" aria-label="Модель режиссёрской группы" value={model} disabled={locked} onChange={e=>{setModel(e.target.value);setExecution({...execution,parallelModels:[]});}}>{MODELS.filter(m=>m.kind==='text'&&['openai','xai','minimax'].includes(m.provider)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></F>}</div>
    <p className="muted">{stage===0?'Сохраните задание → создайте варианты по жанру и режиссёрскому подходу → выберите и утвердите текст в карточках ниже → перейдите к специалистам для дальнейшей доработки. Число вариантов и модель задаются в окне генерации.':'Один вариант по умолчанию. Специалисты работают параллельно; утверждение остаётся за вами. Стоимость каждого вызова — в журнале проекта.'}</p>
    {!!p.creativeHistory?.length&&[12,4].includes(stage)&&<details><summary>Сравнить версии сцен в двух окнах</summary>{stage===4&&<p>Сравнивается выбранная ниже сцена. Выбор переносит только её; остальные сцены и оплаченные материалы сохраняются.</p>}<VersionComparison disabled={locked}
      title={stage===4?`Версии: ${scene?.title??'сцена'}`:'Версии структуры сцен'} selectedId={p.creativeVersionId}
      versions={p.creativeHistory.filter(v=>stage!==4||v.snapshot.scenes.some(s=>s.id===scene?.id)).map(v=>({id:v.id,label:`${new Date(v.created).toLocaleString('ru-RU')} · ${v.reason}`,text:v.snapshot.scenes.filter(s=>stage!==4||s.id===scene?.id).map(sceneText).join('\n\n'),metadata:{origin:v.reason,created:v.created,settings:v.snapshot.brief}}))}
      onChoose={v=>stage===4&&scene?call('restoreSceneVersion',{versionId:v.id,sceneId:scene.id}):chooseHistory(v.id)}
    /></details>}
    {!!p.creativeHistory?.length&&<details><summary>Сохранённые версии задания и сцен · {p.creativeHistory.length}</summary><p className="muted">Возврат создаёт новую ветвь истории. Сгенерированные файлы, расходы, исключённые планы и монтаж остаются в проекте.</p><div className="space-y-3">{[...p.creativeHistory].reverse().map(v=><article key={v.id} className="border rounded p-3"><strong>{v.reason}</strong><small className="block">{new Date(v.created).toLocaleString('ru-RU')} · {v.snapshot.scenes.length} сцен</small><details><summary>Посмотреть содержание</summary><p>{v.snapshot.brief.genre} · {v.snapshot.brief.director}</p>{v.snapshot.scenes.map(s=><div key={s.id}><b>{s.title}</b><p>{s.purpose} · {s.location}</p>{s.shots.map(shot=><p key={shot.id}>{shot.title}: {shot.story}</p>)}</div>)}</details><Button size="sm" variant="outline" disabled={locked||p.creativeVersionId===v.id} onClick={()=>chooseHistory(v.id)}>Вернуться к этой версии</Button></article>)}</div></details>}
    <div className="border rounded p-4 space-y-3"><F label="Режим хронометража"><select className="w-full rounded border p-2 bg-background" disabled={locked} value={runtimeMode(p)} onChange={e=>call('runtimePolicy',{mode:e.target.value})}><option value="free">Свободная длительность — ориентир без ограничения</option><option value="strict">Строгий хронометраж — не более ориентира</option></select></F>
      <p>Желаемая длительность: <b>{d?.brief.targetSeconds??brief.targetSeconds} сек</b>. По планам команды: <b>{seconds.toFixed(2)} сек</b>{seconds>0&&<> · разница {(seconds-(d?.brief.targetSeconds??brief.targetSeconds))>0?'+':''}{(seconds-(d?.brief.targetSeconds??brief.targetSeconds)).toFixed(2)} сек</>}.</p>
      <p className="muted">{runtimeMode(p)==='free'?'Превышение ориентира не блокирует утверждение. Фактическое время уточнится после озвучки и монтажа.':'Сценарий и готовая сборка должны укладываться в предел. Короткий фильм допустим; речь не ускоряется и не обрезается.'}</p>
      {seconds>0&&runtimeMode(p)==='free'&&<Button variant="outline" disabled={locked||timingAccepted||scenes.some(s=>!s.shots.length)} onClick={()=>call('acceptRuntime')}>{timingAccepted?'✓ Расчётная длительность принята':'Принять расчётную длительность'}</Button>}
      {!!d?.issues.some(i=>!i.resolved&&!i.category)&&<p className="muted">Есть замечания прежней проверки. Нажмите «Предложить решения / проверить заново», чтобы редактор оценил их с учётом выбранного режима.</p>}
    </div>
    {stage===0&&<>
      <div className="grid gap-4 md:grid-cols-2">
        <F label="Жанр"><Input list="director-genres" value={brief.genre} onChange={e=>setBrief({...brief,genre:e.target.value})}/><datalist id="director-genres">{GENRE_OPTIONS.map(s=><option key={s} value={s}/>)}</datalist></F>
        <F label="Режиссёрский подход"><select className="w-full rounded border p-2 bg-background" value={brief.director} onChange={e=>setBrief({...brief,director:e.target.value,techniques:DIRECTOR_PRESETS[e.target.value]})}>{Object.keys(DIRECTOR_PRESETS).map(s=><option key={s}>{s}</option>)}</select></F>
        <F label="Аудитория"><Input value={brief.audience} onChange={e=>setBrief({...brief,audience:e.target.value})}/></F>
        <F label="Ориентир длительности, сек"><Input type="number" min={10} max={3600} value={brief.targetSeconds} onChange={e=>setBrief({...brief,targetSeconds:Number(e.target.value)})}/></F>
        <F label="Какое чувство должен вызвать фильм"><Textarea value={brief.effect} onChange={e=>setBrief({...brief,effect:e.target.value})}/></F>
        <F label="Приёмы — можно изменить"><Textarea value={brief.techniques} onChange={e=>setBrief({...brief,techniques:e.target.value})}/></F>
        <F label="Что нельзя менять"><Textarea value={brief.locked} onChange={e=>setBrief({...brief,locked:e.target.value})}/></F>
        <F label="Порядок производства"><select className="w-full rounded border p-2 bg-background" value={order} onChange={e=>setOrder(e.target.value as typeof order)}><option value="voice-first">Сначала голоса и аниматик, затем видео</option><option value="video-first">Сначала видео, затем голоса под его длительность</option></select><small>При озвучке после видео проверяем фактическую длину файлов. Речь не обрезается и не ускоряется.</small></F>
      </div>
      <CreativeStrengthControls value={brief.strengths} disabled={locked} onChange={strengths=>setBrief({...brief,strengths})}/>
      <StagingModeControl value={brief.stagingMode} disabled={locked} onChange={stagingMode=>setBrief({...brief,stagingMode})}/>
      <CameraPolicyControl value={brief.cameraPolicy} disabled={locked} onChange={cameraPolicy=>setBrief({...brief,cameraPolicy})}/>
      <FramePolicyControl value={brief.framePolicy} disabled={locked} onChange={framePolicy=>setBrief({...brief,framePolicy})}/>
      <p className="muted text-sm">Новые настройки применяются к дальнейшей проработке и генерации. Утверждённые материалы и выбранные комплекты кадров сохраняются. Чтобы изменить готовый план, откройте его правки и заново проработайте нужное действие.</p>
      <FacialExpressionControl value={brief.facialExpression} disabled={locked} onChange={facialExpression=>setBrief({...brief,facialExpression})}/>
      <p className="muted text-sm">Мимика применяется при новой проработке актёрской игры и генерации кадров и видео. Готовые материалы сохраняются. В отдельном плане можно выбрать другую манеру.</p>
      <F label="Дополнительные инструкции для сценаристов"><Textarea value={brief.promptNotes??''} onChange={e=>setBrief({...brief,promptNotes:e.target.value})}/></F>
      <label className="row"><input type="checkbox" checked={brief.factual} onChange={e=>setBrief({...brief,factual:e.target.checked})}/>Неигровое кино: сохранять факты, отмечать сведения для проверки</label>
      <div className="row wrap"><Button disabled={locked} onClick={saveBrief}>Сохранить творческое задание</Button>{generateScenario&&<Button disabled={locked||!d||briefDirty} onClick={generateScenario}>Создать варианты по заданию</Button>}<Button variant="outline" disabled={locked||!d||briefDirty||!p.items.some(i=>i.stage===0&&!i.removedAt&&!i.planArchive&&i.variants.some(v=>v.id===i.selectedId&&v.kind==='text'&&!!v.text.trim()))} onClick={()=>open(13)}>Доработать сценарий со специалистами</Button><Button variant="outline" onClick={()=>open(12)}>Перейти к сценам</Button></div>
      {briefDirty&&<p role="status">Есть несохранённые настройки. Сохраните творческое задание перед запуском команды.</p>}
    </>}
    {[0,12,4].includes(stage)&&<StoryMeaningPanel p={p} busy={locked} submit={call} editable={stage===0} onOpenShot={stage===4?(sceneId,shotId)=>{const target=scenes.find(s=>s.id===sceneId),shot=target?.shots.find(s=>s.id===shotId);if(shot){setSceneId(sceneId);editShot(sceneId,shot);}}:undefined}/>}
    {stage===12&&<>
      {!scenes.length&&<Button variant="outline" disabled={locked} onClick={()=>call('importScript')}>Перенести текущий подробный сценарий без генерации</Button>}
      <div className="row wrap"><Button disabled={locked} onClick={()=>generate('scenes',{replaceScenes:!!scenes.length})}>{scenes.length?'Заново разделить сценарий на сцены':'Создать весь этап · разделить на сцены'}</Button><Button variant="outline" disabled={locked} onClick={()=>editScene({id:'new',title:'Новая сцена',purpose:'',location:'',conflict:'',turn:'',stateIn:'',stateOut:'',continuity:[],shots:[]})}>Добавить сцену вручную</Button><Button disabled={locked||!scenes.length} variant="outline" onClick={()=>call('approveScenes')}>{d?.scenesApproved===scenesBasis(p)?'✓ Структура сцен утверждена':'Утвердить структуру сцен'}</Button></div>
      {scenes.length>0&&<><BatchScopeSelector rows={sceneRows} selected={selectedScenesReady} disabled={locked} onChange={setSelectedSceneIds}/><p className="muted">Выбрано сцен: {selectedScenesReady.length}. Для выбранных сцен уточняются задача, действие и состояния; ID и существующие планы сохраняются. Полное повторное разбиение выше создаёт новую структуру.</p><Button variant="outline" disabled={locked||!selectedScenesReady.length} onClick={()=>generate('scenes',{scope:'selected',sceneIds:selectedScenesReady,replaceScenes:true})}>Доработать выбранные сцены · {selectedScenesReady.length}</Button></>}
      {scenes.length>0&&<p className="muted">Повторное разбиение создаёт новую структуру для проработки. Опубликованный сценарий и готовые файлы остаются в истории проекта.</p>}
      {scenes.map((s,n)=><article key={s.id} className="border rounded p-4 space-y-2"><label className="row"><input type="checkbox" checked={selectedScenesReady.includes(s.id)} disabled={locked||!!sceneRows.find(row=>row.id===s.id)?.blocked} onChange={e=>selectScene(s.id,e.target.checked)}/><strong>{n+1}. {s.title}</strong></label>{sceneRows.find(row=>row.id===s.id)?.blocked&&<p role="status" className="muted">{sceneRows.find(row=>row.id===s.id)?.blocked}</p>}<p>{s.purpose}</p><p><b>Локация:</b> {s.location}</p><p><b>Конфликт:</b> {s.conflict} <b>Поворот:</b> {s.turn}</p><p><b>Начало:</b> {s.stateIn} <b>Конец:</b> {s.stateOut}</p>{s.continuity.map((c,n)=><p key={n}><b>{c.character}:</b> {c.outfit} · {c.props}</p>)}<SceneCausalSummary value={s.causalChain}/><MeaningSummary p={p} ids={s.meaningIds}/><div className="row"><Button size="sm" variant="outline" disabled={locked} onClick={()=>editScene(s)}>Правки</Button><Button size="sm" variant="ghost" disabled={locked} onClick={()=>call('removeScene',{sceneId:s.id})}>Удалить сцену</Button></div></article>)}
      <p className="muted">При утверждении структуры локации выделяются и привязываются к сценам автоматически. Их описания, изображения, свет и погода настраиваются на этапе «Образы и локации».</p>
      <Dialog open={!!editing} onOpenChange={value=>{if(!value)setEditing(undefined);}}><DialogContent className="sm:max-w-3xl max-h-[90dvh] overflow-y-auto" aria-describedby={undefined}>
      {editing&&<><DialogHeader><DialogTitle>Правки сцены: {editing.title}</DialogTitle></DialogHeader>{(['title','purpose','location','conflict','turn','stateIn','stateOut'] as const).map((key,n)=><F key={key} label={['Название','Задача сцены','Локация','Конфликт','Поворот','Состояние в начале','Состояние в конце'][n]}><Textarea value={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.value})}/></F>)}
        <SceneCreativeControls brief={brief} value={editing.creativeOverrides} disabled={locked} onChange={creativeOverrides=>setEditing({...editing,creativeOverrides})}/>
        <MeaningLinks p={p} value={editing.meaningIds} onChange={meaningIds=>setEditing({...editing,meaningIds})} disabled={locked}/>
        <SceneCausalEditor value={editing.causalChain} disabled={locked} onChange={causalChain=>setEditing({...editing,causalChain})}/>
        <F label="Постоянные одежда и реквизит — строка на героя: имя | одежда | предметы"><Textarea rows={5} value={continuityText} onChange={e=>setContinuityText(e.target.value)}/></F>
        <div className="row sticky bottom-0 bg-popover py-3"><Button disabled={locked||sceneCausalIssues(editing.causalChain).length>0} onClick={async()=>{await call('saveScene',{scene:{...editing,continuity:continuityText.split('\n').filter(line=>line.trim()).map(line=>{const [character='',outfit='',...props]=line.split('|');return {character:character.trim(),outfit:outfit.trim(),props:props.join('|').trim()};})}});setEditing(undefined);}}>Сохранить сцену</Button><Button variant="ghost" onClick={()=>setEditing(undefined)}>Закрыть</Button></div></>}
      </DialogContent></Dialog>
      <Button variant="outline" onClick={()=>open(2)}>Перейти к визуальному стилю</Button>
    </>}
    {stage===4&&<>
      <div className="rounded border p-4 space-y-2"><p><b>Работа камеры:</b> {d?.brief.cameraPolicy?CAMERA_POLICY_LABELS[d.brief.cameraPolicy]:'Прежняя постановка · политика не задана'}</p><p className="muted text-sm">Оператор выбирает движение, его цель, скорость и смену крупности по этой политике. Для существующих планов нажмите «Доработать: Оператор», затем проверьте и утвердите результат. Камера и крупность сохраняются в промпте видео при сокращении.</p><Button variant="outline" size="sm" onClick={()=>open(0)}>Настроить работу камеры</Button></div>
      <div className="rounded border p-4 space-y-2"><p><b>Мимика героев:</b> {FACIAL_EXPRESSION_LABELS[d?.brief.facialExpression??'auto']}</p><p className="muted text-sm">Для отдельного плана откройте «Правки четырёх частей» → «Мимика этого плана». Задачу и смену эмоций можно уточнить в «Актёрских задачах».</p><Button variant="outline" size="sm" onClick={()=>open(0)}>Настроить мимику для фильма</Button></div>
      <div className="rounded border p-4 space-y-2"><p><b>Постановка фильма:</b> {d?.brief.stagingMode?STAGING_MODE_LABELS[d.brief.stagingMode]:'Прежняя постановка'}</p><p><b>Опорные изображения:</b> {d?.brief.framePolicy?FRAME_POLICY_LABELS[d.brief.framePolicy]:'Прежний подбор кадров'}</p><p className="muted text-sm">Постановку и необходимость точной конечной композиции можно уточнить в правках каждого плана.</p><Button variant="outline" size="sm" onClick={()=>open(0)}>Настроить постановку фильма</Button></div>
      <Button variant="outline" onClick={()=>open(14)}>Открыть набор планов и плотность монтажа</Button>
      <DirectorExecutionControls model={model} value={execution} disabled={locked} onChange={setExecution}/>
      {d?.shotPlanning&&!allPlanSetsApproved(p)&&<p role="status">Сначала утвердите изменённые наборы на этапе «Планы сцен».</p>}
      {!d?.scenes.length?<p>Для работы команды сначала подготовьте и утвердите <Button variant="link" onClick={()=>open(12)}>структуру сцен</Button>. Прежний способ создания сценария остаётся ниже.</p>:<>
        <BatchScopeSelector rows={sceneRows} selected={selectedScenesReady} disabled={locked} onChange={setSelectedSceneIds}/><div className="flex flex-wrap gap-3">{scenes.map(s=><label key={s.id} className="row"><input type="checkbox" checked={selectedScenesReady.includes(s.id)} disabled={locked||!!sceneRows.find(row=>row.id===s.id)?.blocked} onChange={e=>selectScene(s.id,e.target.checked)}/>{s.title}</label>)}</div>
        <div className="row wrap"><Button disabled={locked||d.scenesApproved!==scenesBasis(p)||!selectedScenesReady.length||!!d.shotPlanning&&scenes.filter(s=>selectedScenesReady.includes(s.id)).some(s=>!planSetApproved(p,s))||scenes.filter(s=>selectedScenesReady.includes(s.id)).some(s=>!s.shots.length)} onClick={()=>generate('develop',{scope:'selected',sceneIds:selectedScenesReady})}>Проработать выбранные сцены и специалистов · {selectedScenesReady.length}</Button><Button variant="outline" disabled={locked||!scenes.some(s=>s.shots.length)} onClick={()=>generate('editor')}>Проверить весь фильм редактором</Button></div>
        <p className="muted">Выбрано {selectedScenesReady.length} сцен: подробные задания идут группами до трёх планов, затем выполняются проверки. Для отдельных существующих планов используйте набор ниже — соседние планы сохранятся. Расход зависит от токенов и сохраняется в журнале.</p>
        <p className="muted">После режиссёра сцены оператор, художник, автор реплик и специалист по актёрской работе работают параллельно. Затем рецензент оценивает выразительность каждой сцены, а редактор — фильм целиком. Четыре части плана утверждаются одним решением.</p>
        <F label="Сцена"><select className="w-full rounded border p-2 bg-background" value={scene?.id??''} onChange={e=>setSceneId(e.target.value)}>{scenes.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></F>
        {scene&&<><SceneCausalSummary value={scene.causalChain}/><SceneCreativeSettings key={scene.id} brief={d.brief} value={scene.creativeOverrides} disabled={locked} save={creativeOverrides=>call('saveScene',{scene:{...scene,creativeOverrides}})}/><details><summary>Инструкции для специалистов этой сцены</summary><pre className="whitespace-pre-wrap text-sm">{renderCreativeInstructions(d.brief,scene.creativeOverrides,'scene')||JSON.stringify(d.brief,null,2)}</pre></details><p><b>Постоянные образы:</b> {scene.continuity.map(c=>`${c.character}: ${c.outfit}; ${c.props}`).join(' · ')}</p>
          {!!scene.shots.length&&<><h3>Набор существующих планов</h3><BatchScopeSelector rows={shotRows} selected={selectedShotsReady.filter(id=>scene.shots.some(s=>s.id===id))} disabled={locked} onChange={ids=>setSelectedShotIds(previous=>[...previous.filter(id=>!scene.shots.some(s=>s.id===id)),...ids])}/><Button variant="outline" disabled={locked||d.scenesApproved!==scenesBasis(p)||!selectedShotsReady.length||!!d.shotPlanning&&scenes.filter(s=>s.shots.some(shot=>selectedShotsReady.includes(shot.id))).some(s=>!planSetApproved(p,s))} onClick={()=>generate('develop',{scope:'selected',shotIds:selectedShotsReady})}>Проработать выбранные планы и специалистов · {selectedShotsReady.length}</Button><p className="muted">Выбрано {selectedShotsReady.length} планов в {scenes.filter(s=>s.shots.some(shot=>selectedShotsReady.includes(shot.id))).length} сценах. История и специалисты меняют только эти планы с прежними ID; редактор проверяет весь фильм. «Оставшиеся» — неполные планы, «Требуют внимания» — неполные, конфликтные или с устаревшим утверждением.</p></>}
          <div className="row wrap">{roles.map(r=><Button key={r.id} size="sm" variant="outline" disabled={locked||!scene.shots.length||!!d.shotPlanning&&!planSetApproved(p,scene)} onClick={()=>{const ids=selectedShotsReady.filter(id=>scene.shots.some(s=>s.id===id));return generate('role',{sceneId:scene.id,role:r.id,...(ids.length?{scope:'selected',shotIds:ids}:{})});}}>Доработать: {r.label}</Button>)}</div>
          {scene.shots.map((s,n)=><article className="border rounded p-4 space-y-3" key={s.id}><div className="row spread"><label className="row"><input type="checkbox" checked={selectedShotsReady.includes(s.id)} disabled={locked||!!shotRows.find(row=>row.id===s.id)?.blocked} onChange={e=>selectShot(s.id,e.target.checked)}/><strong>{n+1}. {s.title} · {s.duration} сек</strong></label><span>{shotApproved(scene,s,p)?'✓ Утверждён':'На рассмотрении'}</span></div>{shotRows.find(row=>row.id===s.id)?.blocked&&<p role="status" className="muted">{shotRows.find(row=>row.id===s.id)?.blocked}</p>}
            <Tabs defaultValue="story"><TabsList className="flex flex-wrap h-auto"><TabsTrigger value="story">Сценарий</TabsTrigger><TabsTrigger value="camera">Оператор</TabsTrigger><TabsTrigger value="art">Художник</TabsTrigger><TabsTrigger value="dialogue">Реплики и звук</TabsTrigger></TabsList>
              <TabsContent value="story"><p className="whitespace-pre-wrap">{s.story}</p><p>В начале: {s.stateIn}</p><p>В конце: {s.stateOut}</p><NarrativeBeatSummary value={s.direction?.narrativeBeat}/><MeaningSummary p={p} ids={s.meaningIds}/><p>Изменения одежды / предметов: {s.continuityChanges||'Нет'}</p></TabsContent>
              <TabsContent value="camera"><p className="whitespace-pre-wrap">{s.cinematography}</p><ShotDirectionSummary direction={s.direction} duration={s.duration}/></TabsContent><TabsContent value="art"><p className="whitespace-pre-wrap">{s.productionDesign}</p></TabsContent><TabsContent value="dialogue"><p>{s.dialogue.speechType==='none'?'Без речи':s.dialogue.speechType==='voiceover'?'За кадром':'В кадре'} · {s.dialogue.speaker}</p><p className="whitespace-pre-wrap">{s.dialogue.text}</p><p className="muted">{s.dialogue.delivery}</p></TabsContent>
            </Tabs><div className="row wrap"><Button size="sm" variant="outline" disabled={locked} onClick={()=>editShot(scene.id,s)}>Правки четырёх частей</Button><Button size="sm" disabled={locked||!readyShotIds.includes(s.id)} onClick={()=>call('approveShots',{ids:[s.id]})}>Утвердить план</Button></div>
          </article>)}
        </>}
        {shotEdit&&<div className="border rounded p-4 space-y-3"><h3>Правки плана</h3><div className="grid gap-3 md:grid-cols-2"><F label="Название"><Input value={shotEdit.shot.title} onChange={e=>shotField('title',e.target.value)}/></F><F label="Секунды (ориентир)"><Input type="number" min={.5} max={60} step={.1} value={shotEdit.shot.duration} onChange={e=>shotField('duration',Number(e.target.value))}/></F></div>
          <F label="Участники через запятую"><Input value={castText} onChange={e=>setCastText(e.target.value)}/></F>
          {(['story','stateIn','stateOut','cinematography','productionDesign','continuityChanges'] as const).map((key,n)=><F key={key} label={['Сценарий','Начальное состояние','Конечное состояние','Операторская работа','Художественное решение','Обоснованные изменения одежды / реквизита'][n]}><Textarea rows={4} value={shotEdit.shot[key]} onChange={e=>shotField(key,e.target.value)}/></F>)}
          <F label="Режим речи"><select className="rounded border p-2 bg-background" value={shotEdit.shot.dialogue.speechType} onChange={e=>shotField('dialogue',{...shotEdit.shot.dialogue,speechType:e.target.value,...(e.target.value==='none'?{text:'',speaker:''}:{})})}><option value="none">Без речи</option><option value="voiceover">Закадровый голос</option><option value="character">Герой в кадре</option></select></F>
          {(['speaker','text','delivery'] as const).map((key,n)=><F key={key} label={['Говорящий','Только произносимые слова','Подача, паузы и звуки'][n]}><Textarea value={shotEdit.shot.dialogue[key]} onChange={e=>shotField('dialogue',{...shotEdit.shot.dialogue,[key]:e.target.value})}/></F>)}
          <MeaningLinks p={p} value={shotEdit.shot.meaningIds} onChange={ids=>shotField('meaningIds',ids)} disabled={locked}/>
          <ShotDirectionEditor direction={shotEdit.shot.direction} duration={shotEdit.shot.duration} inheritedFacialExpression={d?.brief.facialExpression} inheritedStagingMode={d?.brief.stagingMode} disabled={locked} onChange={value=>shotField('direction',value)}/>
          <div className="row"><Button disabled={locked||directionEditorIssues(shotEdit.shot.direction,shotEdit.shot.duration).some(i=>i.severity==='conflict')} onClick={async()=>{await call('saveShot',{...shotEdit,shot:{...shotEdit.shot,cast:castText.split(',').map(s=>s.trim()).filter(Boolean)}});setShotEdit(undefined);}}>Сохранить план</Button><Button variant="ghost" onClick={()=>setShotEdit(undefined)}>Закрыть</Button></div>
        </div>}
        <p role="status">Готовы к утверждению: {readyShotIds.length}. Неполные: {readiness.incomplete.length}. С конфликтами: {readiness.conflicts.length}.</p>
        {(readiness.incomplete.length>0||readiness.conflicts.length>0)&&<details><summary>Какие планы требуют заполнения или решения конфликтов</summary>{readiness.pending.filter(row=>row.missing.length||row.conflicts.length).map(row=><div key={row.shotId} className="border rounded p-3"><b>{row.title}</b>{row.missing.length>0&&<p>Заполните: {row.missing.join(', ')}.</p>}{row.conflicts.map((message,n)=><p key={n}>{message}</p>)}<Button size="sm" variant="outline" disabled={locked} onClick={()=>{const target=scenes.find(s=>s.id===row.sceneId)!,shot=target.shots.find(s=>s.id===row.shotId)!;setSceneId(target.id);editShot(target.id,shot);}}>Открыть план</Button></div>)}</details>}
        <div className="row wrap"><Button variant="outline" disabled={locked||!readyShotIds.length} onClick={()=>{if(readyShotIds.length)return call('approveShots',{ids:readyShotIds});}}>{allShotsApproved?'✓ Все планы утверждены':readyShotIds.length?`Утвердить все готовые планы · ${readyShotIds.length}`:'Нет готовых планов для утверждения'}</Button><Button disabled={locked||!allShotsApproved||!!d.shotPlanning&&!allPlanSetsApproved(p)} onClick={()=>call('publish',{model})}>Подготовить промпты и применить сценарий</Button></div>
      </>}
    </>}
    {!!d?.issues.length&&<div className="space-y-3"><h3>Проверка редактора</h3>
      <p className="muted">Редактор предлагает готовые изменения. Применение решений не запускает платную генерацию. После правок повторите проверку фильма и утвердите обновлённые планы.</p>
      <div className="row wrap"><Button variant="outline" disabled={locked} onClick={()=>generate('editor')}>Предложить решения / проверить заново</Button><Button disabled={locked||!d.patches.some(p=>!p.applied)&&!d.montageOperations?.some(op=>!op.applied)} onClick={()=>call('applyAllSolutions')}>Применить все предложенные решения</Button></div>
      {d.issues.map(i=>{const patches=d.patches.filter(p=>p.issueId===i.id||p.relatedIssueIds?.includes(i.id)),operations=(d.montageOperations??[]).filter(op=>op.issueId===i.id||op.relatedIssueIds?.includes(i.id));return <div key={i.id} className="border rounded p-3 space-y-3"><p>{i.resolved?'✓':i.severity==='conflict'?'Конфликт':'Замечание'}: {i.message}</p>{i.solution&&<p><b>Решение редактора:</b> {i.solution}</p>}{patches.map(patchPreview)}{operations.map(op=><MontageOperationPreview key={op.id} p={p} operation={op}/>)}{[...patches,...operations].some(p=>!p.applied)&&<Button size="sm" disabled={locked} onClick={()=>call('applySolution',{issueId:i.id})}>Применить решение</Button>}{!i.resolved&&!patches.length&&!operations.length&&<p className="muted">Готовая правка не приложена. Нажмите «Предложить решения / проверить заново» — это новый запрос к выбранной модели. Если нужен ваш творческий выбор, редактор объяснит его.</p>}{i.resolution&&<small>{i.resolution}</small>}{!i.resolved&&<details><summary>Решить вручную</summary><F label="Как решено замечание"><Input value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Как вы исправили план или почему оставляете его"/></F><Button size="sm" variant="outline" disabled={locked||!resolution.trim()} onClick={()=>call('resolveIssue',{issueId:i.id,resolution})}>Зафиксировать решение</Button></details>}</div>;})}</div>}
    {!!d?.patches.some(p=>!p.issueId)&&<div className="space-y-3"><h3>Другие предложенные правки</h3>{d.patches.filter(p=>!p.issueId).map(patch=><div key={patch.id}>{patchPreview(patch)}<Button size="sm" disabled={locked||patch.applied} onClick={()=>call('applyPatch',{patchId:patch.id})}>Применить правку</Button></div>)}</div>}
    {!!d?.montageOperations?.length&&<div className="space-y-3"><h3>Монтажные решения</h3><p className="muted">Можно изменить время, исключить, переставить или объединить соседние планы. Несовместимые решения выбирайте отдельно. Файлы и расходы сохраняются.</p><Button disabled={locked||!d.montageOperations.some(op=>!op.applied)} onClick={()=>call('applyAllMontageOperations')}>Применить все монтажные решения</Button>{d.montageOperations.map(op=><div key={op.id} className="space-y-2"><MontageOperationPreview p={p} operation={op}/><Button size="sm" disabled={locked||op.applied} onClick={()=>call('applyMontageOperation',{operationId:op.id})}>Применить это монтажное решение</Button></div>)}</div>}
    {(stage!==0||run?.tasks.some(t=>t.role==='story-meaning'))&&<DirectorRunStatus p={p} run={run} busy={busy} submit={call}/>}
  </section>;
}
