'use client';
import { useState,useEffect,useRef } from 'react';
import { CreativeStrengthControls,SceneCreativeControls,SceneCreativeSettings } from './creative-controls';
import { GENRE_OPTIONS,renderCreativeInstructions } from '@/lib/creative-brief';
import { ScriptWorkflowEditor } from './script-workflow-editor';
import {SceneLocationEditor} from './world-editor';
import {ShotDirectionEditor,ShotDirectionSummary,directionEditorIssues} from './shot-direction-editor';
import {MontageOperationPreview} from './montage-solutions';
import {readableShotDirection} from '@/lib/shot-direction';
import { VersionComparison } from './version-comparison';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import type { Project } from '@/lib/domain';
import { money } from '@/lib/domain';
import { MODELS } from '@/lib/models';
import {runtimeMode,plannedRuntime,runtimeAcceptanceBasis} from '@/lib/runtime-policy';
import { DEFAULT_BRIEF,DIRECTOR_PRESETS,ROLE_NAMES,directorPrompt,directorRunActive,EDITOR_SECTION_NAMES,shotApproved,scenesBasis,type EditorPatch,type Scene,type DirectingShot,type DirectorRole } from '@/lib/directing';

type Props={p:Project;stage:number;busy:boolean;submit:(action:string,data?:unknown)=>Promise<void>;open:(stage:number)=>void};
const F=({label,children}:{label:string;children:React.ReactNode})=><label className="block space-y-2"><span className="text-sm font-medium">{label}</span>{children}</label>;
export function DirectingEditor({p,stage,busy,submit,open}:Props){
  const d=p.directing;
  const [brief,setBriefState]=useState(d?.brief??{...DEFAULT_BRIEF,targetSeconds:Math.max(10,p.seconds)});
  const briefDirty=useRef(false);const setBrief=(value:typeof brief)=>{briefDirty.current=true;setBriefState(value);};
  const savedBrief=JSON.stringify(d?.brief);useEffect(()=>{if(!briefDirty.current&&d)setBriefState(d.brief);},[p.id,savedBrief]);
  const [order,setOrder]=useState(p.productionOrder??'voice-first');
  const [model,setModel]=useState(MODELS.find(m=>m.kind==='text'&&m.provider==='openai')!.id);
  const [sceneId,setSceneId]=useState(d?.scenes[0]?.id??'');
  const [editing,setEditing]=useState<Scene>();
  const [shotEdit,setShotEdit]=useState<{sceneId:string;shot:DirectingShot}>();
  const [resolution,setResolution]=useState('');
  const [continuityText,setContinuityText]=useState('');
  const [castText,setCastText]=useState('');
  const editScene=(scene:Scene)=>{setEditing(structuredClone(scene));setContinuityText(scene.continuity.map(c=>`${c.character} | ${c.outfit} | ${c.props}`).join('\n'));};
  const editShot=(sceneId:string,shot:DirectingShot)=>{setShotEdit({sceneId,shot:structuredClone(shot)});setCastText(shot.cast.join(', '));};
  const scenes=d?.scenes??[],scene=scenes.find(s=>s.id===sceneId)??scenes[0];
  const pendingShotIds=scenes.flatMap(s=>s.shots.filter(shot=>!shotApproved(s,shot,p)).map(shot=>shot.id));
  const allShotsApproved=scenes.length>0&&scenes.every(s=>s.shots.length>0)&&pendingShotIds.length===0;
  const run=d?.runs.at(-1),running=!!run&&directorRunActive(run);
  const locked=busy||running;
  const seconds=plannedRuntime(p),timingAccepted=d?.acceptedRuntime?.basis===runtimeAcceptanceBasis(p);
  const call=(action:string,data?:unknown)=>submit(action,data);
  const generate=(mode:string,extra:Record<string,unknown>={})=>call('run',{model,mode,...extra});
  const roles:{id:DirectorRole;label:string}[]=[{id:'story',label:'Сценарий'},{id:'camera',label:'Оператор'},{id:'art',label:'Художник'},{id:'dialogue',label:'Реплики'},{id:'performance',label:'Актёрская работа'},{id:'scene-expressive-reviewer',label:'Выразительность сцены'}];
  const chooseHistory=async(versionId:string)=>{const v=p.creativeHistory?.find(v=>v.id===versionId);await call('restoreCreativeVersion',{versionId});if(v){briefDirty.current=false;setBriefState(v.snapshot.brief);setOrder(v.snapshot.productionOrder??'voice-first');}};
  const sceneText=(s:Scene)=>[s.title,`Задача: ${s.purpose}`,`Локация: ${s.location}`,`Конфликт: ${s.conflict}`,`Поворот: ${s.turn}`,`Начало: ${s.stateIn}`,`Конец: ${s.stateOut}`,...s.continuity.map(c=>`${c.character}: ${c.outfit}; ${c.props}`),...s.shots.map(shot=>`${shot.title} · ${shot.duration} сек\n${shot.story}\nОператор: ${shot.cinematography}\nХудожник: ${shot.productionDesign}\nРечь: ${shot.dialogue.speaker}: ${shot.dialogue.text}\nПодача: ${shot.dialogue.delivery}\nНачало: ${shot.stateIn}\nКонец: ${shot.stateOut}${shot.direction?'\n'+readableShotDirection(shot.direction):''}`)].join('\n\n');
  const shotField=(key:keyof DirectingShot,value:unknown)=>setShotEdit(e=>e?{...e,shot:{...e.shot,[key]:value}}:e);
  const patchPreview=(patch:EditorPatch)=>{const target=scenes.find(s=>s.shots.some(v=>v.id===patch.shotId)),shot=target?.shots.find(s=>s.id===patch.shotId);return <details key={patch.id} className="border rounded p-3"><summary>{target?.title} · {shot?.title??'План'} · {EDITOR_SECTION_NAMES[patch.section]} {patch.applied&&'✓ Применено'}</summary><p>{patch.reason}</p><p className="whitespace-pre-wrap"><b>Было:</b> {patch.before||'Пусто'}</p><p className="whitespace-pre-wrap"><b>Предложение:</b> {patch.after||'Пусто'}</p></details>;};
  return <section className="editor-surface p-5 mb-6 space-y-5" aria-label="Команда сценаристов и режиссёров">
    <div className="row spread wrap"><div><div className="eyebrow">РЕЖИССЁРСКАЯ ГРУППА</div><h2>{stage===0?'Творческое задание и рецензия':stage===12?'Структура сцен':'Проработка всех планов'}</h2></div>
      <F label="Модель команды"><select className="rounded border p-2 bg-background" aria-label="Модель режиссёрской группы" value={model} disabled={locked} onChange={e=>setModel(e.target.value)}>{MODELS.filter(m=>m.kind==='text'&&['openai','xai','minimax'].includes(m.provider)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></F></div>
    <p className="muted">Один вариант по умолчанию. Специалисты работают параллельно; утверждение остаётся за вами. Стоимость каждого вызова — в журнале проекта.</p>
    {!!p.creativeHistory?.length&&[12,4].includes(stage)&&<details><summary>Сравнить версии сцен в двух окнах</summary>{stage===4&&<p>Сравнивается выбранная ниже сцена. Выбор переносит только её; остальные сцены и оплаченные материалы сохраняются.</p>}<VersionComparison disabled={locked}
      title={stage===4?`Версии: ${scene?.title??'сцена'}`:'Версии структуры сцен'} selectedId={p.creativeVersionId}
      versions={p.creativeHistory.filter(v=>stage!==4||v.snapshot.scenes.some(s=>s.id===scene?.id)).map(v=>({id:v.id,label:`${new Date(v.created).toLocaleString('ru-RU')} · ${v.reason}`,text:v.snapshot.scenes.filter(s=>stage!==4||s.id===scene?.id).map(sceneText).join('\n\n'),metadata:{origin:v.reason,created:v.created,settings:v.snapshot.brief}}))}
      onChoose={v=>stage===4&&scene?call('restoreSceneVersion',{versionId:v.id,sceneId:scene.id}):chooseHistory(v.id)}
    /></details>}
    {!!p.creativeHistory?.length&&<details><summary>Сохранённые версии задания и сцен · {p.creativeHistory.length}</summary><p className="muted">Возврат создаёт новую ветвь истории. Сгенерированные файлы, расходы, исключённые планы и монтаж остаются в проекте.</p><div className="space-y-3">{[...p.creativeHistory].reverse().map(v=><article key={v.id} className="border rounded p-3"><strong>{v.reason}</strong><small className="block">{new Date(v.created).toLocaleString('ru-RU')} · {v.snapshot.scenes.length} сцен</small><details><summary>Посмотреть содержание</summary><p>{v.snapshot.brief.genre} · {v.snapshot.brief.director}</p>{v.snapshot.scenes.map(s=><div key={s.id}><b>{s.title}</b><p>{s.purpose} · {s.location}</p>{s.shots.map(shot=><p key={shot.id}>{shot.title}: {shot.story}</p>)}</div>)}</details><Button size="sm" variant="outline" disabled={locked||p.creativeVersionId===v.id} onClick={()=>chooseHistory(v.id)}>Вернуться к этой версии</Button></article>)}</div></details>}
    <div className="border rounded p-4 space-y-3"><F label="Режим хронометража"><select className="w-full rounded border p-2 bg-background" disabled={locked} value={runtimeMode(p)} onChange={e=>call('runtimePolicy',{mode:e.target.value})}><option value="free">Свободная длительность — ориентир без ограничения</option><option value="strict">Строгий хронометраж — не более ориентира</option></select></F>
      <p>Желаемая длительность: <b>{d?.brief.targetSeconds??brief.targetSeconds} сек</b>. По планам команды: <b>{seconds.toFixed(2)} сек</b>{seconds>0&&<> · разница {(seconds-(d?.brief.targetSeconds??brief.targetSeconds))>0?'+':''}{(seconds-(d?.brief.targetSeconds??brief.targetSeconds)).toFixed(2)} сек</>}.</p>
      <p className="muted">{runtimeMode(p)==='free'?'Превышение ориентира не блокирует утверждение. Фактическое время уточнится после озвучки и монтажа.':'Сценарий и готовая сборка должны укладываться в предел. Короткий фильм допустим; речь не ускоряется и не обрезается.'}</p>
      {seconds>0&&runtimeMode(p)==='free'&&<Button variant="outline" disabled={locked||timingAccepted||scenes.some(s=>!s.shots.length)} onClick={()=>call('acceptRuntime')}>{timingAccepted?'✓ Расчётная длительность принята':'Принять расчётную длительность'}</Button>}
      {!!d?.issues.some(i=>!i.resolved&&!i.category)&&<p className="muted">Есть замечания прежней проверки. Нажмите «Предложить решения / проверить заново», чтобы редактор оценил их с учётом выбранного режима.</p>}
    </div>
    {stage===0&&<>
      <div className="grid gap-4 md:grid-cols-2">
        <F label="Жанр"><Input list="director-genres" value={brief.genre} onChange={e=>setBrief({...brief,genre:e.target.value})}/><datalist id="director-genres">{GENRE_OPTIONS.map(s=><option key={s} value={s}/>)}</datalist></F>
        <F label="Режиссёрский подход"><select className="w-full rounded border p-2 bg-background" value={brief.director} onChange={e=>setBrief({...brief,director:e.target.value,techniques:DIRECTOR_PRESETS[e.target.value]})}>{Object.keys(DIRECTOR_PRESETS).map(s=><option key={s}>{s}</option>)}</select></F>
        <F label="Аудитория"><Input value={brief.audience} onChange={e=>setBrief({...brief,audience:e.target.value})}/></F>
        <F label="Ориентир длительности, сек"><Input type="number" min={10} max={3600} value={brief.targetSeconds} onChange={e=>setBrief({...brief,targetSeconds:Number(e.target.value)})}/></F>
        <F label="Какое чувство должен вызвать фильм"><Textarea value={brief.effect} onChange={e=>setBrief({...brief,effect:e.target.value})}/></F>
        <F label="Приёмы — можно изменить"><Textarea value={brief.techniques} onChange={e=>setBrief({...brief,techniques:e.target.value})}/></F>
        <F label="Что нельзя менять"><Textarea value={brief.locked} onChange={e=>setBrief({...brief,locked:e.target.value})}/></F>
        <F label="Порядок производства"><select className="w-full rounded border p-2 bg-background" value={order} onChange={e=>setOrder(e.target.value as typeof order)}><option value="voice-first">Сначала голоса и аниматик, затем видео</option><option value="video-first">Сначала видео, затем голоса под его длительность</option></select><small>При озвучке после видео проверяем фактическую длину файлов. Речь не обрезается и не ускоряется.</small></F>
      </div>
      <CreativeStrengthControls value={brief.strengths} disabled={locked} onChange={strengths=>setBrief({...brief,strengths})}/>
      <F label="Дополнительные инструкции для сценаристов"><Textarea value={brief.promptNotes??''} onChange={e=>setBrief({...brief,promptNotes:e.target.value})}/></F>
      <details><summary>Промпт рецензента по текущим настройкам</summary><p className="muted">Ниже полный запрос без отправки. Сохраните задание перед запуском. Редактируйте приёмы и дополнительные инструкции выше.</p><pre className="whitespace-pre-wrap max-h-96 overflow-auto text-sm">{directorPrompt({...p,directing:{...(d??{scenes:[],runs:[],issues:[],patches:[]}),brief}}, {id:'preview',created:'',basis:'',model,mode:'critic',tasks:[],sceneIds:[]},{id:'preview',role:'critic',requires:[]})}</pre></details>
      <label className="row"><input type="checkbox" checked={brief.factual} onChange={e=>setBrief({...brief,factual:e.target.checked})}/>Неигровое кино: сохранять факты, отмечать сведения для проверки</label>
      <div className="row wrap"><Button disabled={locked} onClick={async()=>{await call('brief',{brief,productionOrder:order});briefDirty.current=false;}}>Сохранить творческое задание</Button><Button variant="outline" disabled={locked||!d||briefDirty.current} onClick={()=>generate('critic')}>Рецензия сценария</Button><Button variant="outline" onClick={()=>open(12)}>Перейти к сценам</Button></div>
      {briefDirty.current&&<p role="status">Есть несохранённые настройки. Сохраните творческое задание перед запуском команды.</p>}
      <ScriptWorkflowEditor p={p} model={model} busy={busy||briefDirty.current} submit={call}/>
      {d?.critic&&<div className="space-y-3"><h3>Рецензия</h3><p className="whitespace-pre-wrap">{d.critic.review}</p>{d.critic.alternatives.map((a,index)=><details key={index}><summary>{a.title}</summary><p className="whitespace-pre-wrap">{a.text}</p><Button disabled={locked} variant="outline" onClick={()=>call('useAlternative',{index})}>Добавить как вариант сценария</Button></details>)}</div>}
    </>}
    {stage===12&&<>
      {!scenes.length&&<Button variant="outline" disabled={locked} onClick={()=>call('importScript')}>Перенести текущий подробный сценарий без генерации</Button>}
      <div className="row wrap"><Button disabled={locked} onClick={()=>generate('scenes',{replaceScenes:!!scenes.length})}>{scenes.length?'Заново разделить сценарий на сцены':'Создать весь этап · разделить на сцены'}</Button><Button variant="outline" disabled={locked} onClick={()=>editScene({id:'new',title:'Новая сцена',purpose:'',location:'',conflict:'',turn:'',stateIn:'',stateOut:'',continuity:[],shots:[]})}>Добавить сцену вручную</Button><Button disabled={locked||!scenes.length} variant="outline" onClick={()=>call('approveScenes')}>{d?.scenesApproved===scenesBasis(p)?'✓ Структура сцен утверждена':'Утвердить структуру сцен'}</Button></div>
      {scenes.length>0&&<p className="muted">Повторное разбиение создаёт новую структуру для проработки. Опубликованный сценарий и готовые файлы остаются в истории проекта.</p>}
      {scenes.map((s,n)=><article key={s.id} className="border rounded p-4 space-y-2"><strong>{n+1}. {s.title}</strong><p>{s.purpose}</p><p><b>Локация:</b> {s.location}</p><p><b>Конфликт:</b> {s.conflict} <b>Поворот:</b> {s.turn}</p><p><b>Начало:</b> {s.stateIn} <b>Конец:</b> {s.stateOut}</p>{s.continuity.map((c,n)=><p key={n}><b>{c.character}:</b> {c.outfit} · {c.props}</p>)}<div className="row"><Button size="sm" variant="outline" disabled={locked} onClick={()=>editScene(s)}>Правки</Button><Button size="sm" variant="ghost" disabled={locked} onClick={()=>call('removeScene',{sceneId:s.id})}>Удалить сцену</Button></div></article>)}
      {scenes.map(s=><SceneLocationEditor key={p.id+':'+s.id} p={p} scene={s} busy={locked} onSave={(_sceneId,data)=>call('saveScene',{scene:{...s,...data}})}/>)}
      <Dialog open={!!editing} onOpenChange={value=>{if(!value)setEditing(undefined);}}><DialogContent className="sm:max-w-3xl max-h-[90dvh] overflow-y-auto" aria-describedby={undefined}>
      {editing&&<><DialogHeader><DialogTitle>Правки сцены: {editing.title}</DialogTitle></DialogHeader>{(['title','purpose','location','conflict','turn','stateIn','stateOut'] as const).map((key,n)=><F key={key} label={['Название','Задача сцены','Локация','Конфликт','Поворот','Состояние в начале','Состояние в конце'][n]}><Textarea value={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.value})}/></F>)}
        <SceneCreativeControls brief={brief} value={editing.creativeOverrides} disabled={locked} onChange={creativeOverrides=>setEditing({...editing,creativeOverrides})}/>
        <F label="Постоянные одежда и реквизит — строка на героя: имя | одежда | предметы"><Textarea rows={5} value={continuityText} onChange={e=>setContinuityText(e.target.value)}/></F>
        <div className="row sticky bottom-0 bg-popover py-3"><Button disabled={locked} onClick={async()=>{await call('saveScene',{scene:{...editing,continuity:continuityText.split('\n').filter(line=>line.trim()).map(line=>{const [character='',outfit='',...props]=line.split('|');return {character:character.trim(),outfit:outfit.trim(),props:props.join('|').trim()};})}});setEditing(undefined);}}>Сохранить сцену</Button><Button variant="ghost" onClick={()=>setEditing(undefined)}>Закрыть</Button></div></>}
      </DialogContent></Dialog>
      <Button variant="outline" onClick={()=>open(2)}>Перейти к визуальному стилю</Button>
    </>}
    {stage===4&&<>
      {!d?.scenes.length?<p>Для работы команды сначала подготовьте и утвердите <Button variant="link" onClick={()=>open(12)}>структуру сцен</Button>. Прежний способ создания сценария остаётся ниже.</p>:<>
        <div className="row wrap"><Button disabled={locked||d.scenesApproved!==scenesBasis(p)} onClick={()=>generate('develop')}>Создать весь этап · все сцены и специалисты</Button><Button variant="outline" disabled={locked||!scenes.some(s=>s.shots.length)} onClick={()=>generate('editor')}>Проверить весь фильм редактором</Button></div>
        <p className="muted">После режиссёра сцены оператор, художник, автор реплик и специалист по актёрской работе работают параллельно. Затем рецензент оценивает выразительность каждой сцены, а редактор — фильм целиком. Четыре части плана утверждаются одним решением.</p>
        <F label="Сцена"><select className="w-full rounded border p-2 bg-background" value={scene?.id??''} onChange={e=>setSceneId(e.target.value)}>{scenes.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></F>
        {scene&&<><SceneCreativeSettings key={scene.id} brief={d.brief} value={scene.creativeOverrides} disabled={locked} save={creativeOverrides=>call('saveScene',{scene:{...scene,creativeOverrides}})}/><details><summary>Инструкции для специалистов этой сцены</summary><pre className="whitespace-pre-wrap text-sm">{renderCreativeInstructions(d.brief,scene.creativeOverrides,'scene')||JSON.stringify(d.brief,null,2)}</pre></details><p><b>Постоянные образы:</b> {scene.continuity.map(c=>`${c.character}: ${c.outfit}; ${c.props}`).join(' · ')}</p><div className="row wrap">{roles.map(r=><Button key={r.id} size="sm" variant="outline" disabled={locked||(r.id!=='story'&&!scene.shots.length)} onClick={()=>generate('role',{sceneId:scene.id,role:r.id})}>Доработать: {r.label}</Button>)}</div>
          {scene.shots.map((s,n)=><article className="border rounded p-4 space-y-3" key={s.id}><div className="row spread"><strong>{n+1}. {s.title} · {s.duration} сек</strong><span>{shotApproved(scene,s,p)?'✓ Утверждён':'На рассмотрении'}</span></div>
            <Tabs defaultValue="story"><TabsList className="flex flex-wrap h-auto"><TabsTrigger value="story">Сценарий</TabsTrigger><TabsTrigger value="camera">Оператор</TabsTrigger><TabsTrigger value="art">Художник</TabsTrigger><TabsTrigger value="dialogue">Реплики и звук</TabsTrigger></TabsList>
              <TabsContent value="story"><p className="whitespace-pre-wrap">{s.story}</p><p>В начале: {s.stateIn}</p><p>В конце: {s.stateOut}</p><p>Изменения одежды / предметов: {s.continuityChanges||'Нет'}</p></TabsContent>
              <TabsContent value="camera"><p className="whitespace-pre-wrap">{s.cinematography}</p><ShotDirectionSummary direction={s.direction} duration={s.duration}/></TabsContent><TabsContent value="art"><p className="whitespace-pre-wrap">{s.productionDesign}</p></TabsContent><TabsContent value="dialogue"><p>{s.dialogue.speechType==='none'?'Без речи':s.dialogue.speechType==='voiceover'?'За кадром':'В кадре'} · {s.dialogue.speaker}</p><p className="whitespace-pre-wrap">{s.dialogue.text}</p><p className="muted">{s.dialogue.delivery}</p></TabsContent>
            </Tabs><div className="row wrap"><Button size="sm" variant="outline" disabled={locked} onClick={()=>editShot(scene.id,s)}>Правки четырёх частей</Button><Button size="sm" disabled={locked||shotApproved(scene,s,p)} onClick={()=>call('approveShots',{ids:[s.id]})}>Утвердить план</Button></div>
          </article>)}
        </>}
        {shotEdit&&<div className="border rounded p-4 space-y-3"><h3>Правки плана</h3><div className="grid gap-3 md:grid-cols-2"><F label="Название"><Input value={shotEdit.shot.title} onChange={e=>shotField('title',e.target.value)}/></F><F label="Секунды (ориентир)"><Input type="number" min={.5} max={60} step={.1} value={shotEdit.shot.duration} onChange={e=>shotField('duration',Number(e.target.value))}/></F></div>
          <F label="Участники через запятую"><Input value={castText} onChange={e=>setCastText(e.target.value)}/></F>
          {(['story','stateIn','stateOut','cinematography','productionDesign','continuityChanges'] as const).map((key,n)=><F key={key} label={['Сценарий','Начальное состояние','Конечное состояние','Операторская работа','Художественное решение','Обоснованные изменения одежды / реквизита'][n]}><Textarea rows={4} value={shotEdit.shot[key]} onChange={e=>shotField(key,e.target.value)}/></F>)}
          <F label="Режим речи"><select className="rounded border p-2 bg-background" value={shotEdit.shot.dialogue.speechType} onChange={e=>shotField('dialogue',{...shotEdit.shot.dialogue,speechType:e.target.value,...(e.target.value==='none'?{text:'',speaker:''}:{})})}><option value="none">Без речи</option><option value="voiceover">Закадровый голос</option><option value="character">Герой в кадре</option></select></F>
          {(['speaker','text','delivery'] as const).map((key,n)=><F key={key} label={['Говорящий','Только произносимые слова','Подача, паузы и звуки'][n]}><Textarea value={shotEdit.shot.dialogue[key]} onChange={e=>shotField('dialogue',{...shotEdit.shot.dialogue,[key]:e.target.value})}/></F>)}
          <ShotDirectionEditor direction={shotEdit.shot.direction} duration={shotEdit.shot.duration} disabled={locked} onChange={value=>shotField('direction',value)}/>
          <div className="row"><Button disabled={locked||directionEditorIssues(shotEdit.shot.direction,shotEdit.shot.duration).some(i=>i.severity==='conflict')} onClick={async()=>{await call('saveShot',{...shotEdit,shot:{...shotEdit.shot,cast:castText.split(',').map(s=>s.trim()).filter(Boolean)}});setShotEdit(undefined);}}>Сохранить план</Button><Button variant="ghost" onClick={()=>setShotEdit(undefined)}>Закрыть</Button></div>
        </div>}
        <div className="row wrap"><Button variant="outline" disabled={locked||!pendingShotIds.length} onClick={()=>{if(pendingShotIds.length)return call('approveShots',{ids:pendingShotIds});}}>{allShotsApproved?'✓ Все планы утверждены':pendingShotIds.length?'Утвердить все готовые планы':'Нет планов для утверждения'}</Button><Button disabled={locked||!allShotsApproved} onClick={()=>call('publish',{model})}>Подготовить промпты и применить сценарий</Button></div>
      </>}
    </>}
    {!!d?.issues.length&&<div className="space-y-3"><h3>Проверка редактора</h3>
      <p className="muted">Редактор предлагает готовые изменения. Применение решений не запускает платную генерацию. После правок повторите проверку фильма и утвердите обновлённые планы.</p>
      <div className="row wrap"><Button variant="outline" disabled={locked} onClick={()=>generate('editor')}>Предложить решения / проверить заново</Button><Button disabled={locked||!d.patches.some(p=>!p.applied)&&!d.montageOperations?.some(op=>!op.applied)} onClick={()=>call('applyAllSolutions')}>Применить все предложенные решения</Button></div>
      {d.issues.map(i=>{const patches=d.patches.filter(p=>p.issueId===i.id||p.relatedIssueIds?.includes(i.id)),operations=(d.montageOperations??[]).filter(op=>op.issueId===i.id||op.relatedIssueIds?.includes(i.id));return <div key={i.id} className="border rounded p-3 space-y-3"><p>{i.resolved?'✓':i.severity==='conflict'?'Конфликт':'Замечание'}: {i.message}</p>{i.solution&&<p><b>Решение редактора:</b> {i.solution}</p>}{patches.map(patchPreview)}{operations.map(op=><MontageOperationPreview key={op.id} p={p} operation={op}/>)}{[...patches,...operations].some(p=>!p.applied)&&<Button size="sm" disabled={locked} onClick={()=>call('applySolution',{issueId:i.id})}>Применить решение</Button>}{!i.resolved&&!patches.length&&!operations.length&&<p className="muted">Готовая правка не приложена. Нажмите «Предложить решения / проверить заново» — это новый запрос к выбранной модели. Если нужен ваш творческий выбор, редактор объяснит его.</p>}{i.resolution&&<small>{i.resolution}</small>}{!i.resolved&&<details><summary>Решить вручную</summary><F label="Как решено замечание"><Input value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Как вы исправили план или почему оставляете его"/></F><Button size="sm" variant="outline" disabled={locked||!resolution.trim()} onClick={()=>call('resolveIssue',{issueId:i.id,resolution})}>Зафиксировать решение</Button></details>}</div>;})}</div>}
    {!!d?.patches.some(p=>!p.issueId)&&<div className="space-y-3"><h3>Другие предложенные правки</h3>{d.patches.filter(p=>!p.issueId).map(patch=><div key={patch.id}>{patchPreview(patch)}<Button size="sm" disabled={locked||patch.applied} onClick={()=>call('applyPatch',{patchId:patch.id})}>Применить правку</Button></div>)}</div>}
    {!!d?.montageOperations?.length&&<div className="space-y-3"><h3>Монтажные решения</h3><p className="muted">Можно изменить время, исключить, переставить или объединить соседние планы. Несовместимые решения выбирайте отдельно. Файлы и расходы сохраняются.</p><Button disabled={locked||!d.montageOperations.some(op=>!op.applied)} onClick={()=>call('applyAllMontageOperations')}>Применить все монтажные решения</Button>{d.montageOperations.map(op=><div key={op.id} className="space-y-2"><MontageOperationPreview p={p} operation={op}/><Button size="sm" disabled={locked||op.applied} onClick={()=>call('applyMontageOperation',{operationId:op.id})}>Применить это монтажное решение</Button></div>)}</div>}
    {run&&<details open={running}><summary>Работа команды · {run.tasks.filter(t=>t.applied).length}/{run.tasks.length}</summary><p className="muted">На этом сайте оставьте студию открытой. Сохранённая очередь продолжается при возвращении. В самостоятельной серверной версии обработка работает в фоне.</p>
      <div className="space-y-2">{run.tasks.map(t=>{const job=p.jobs.find(j=>j.id===t.jobId);return <div key={t.id} className="border rounded p-3"><b>{ROLE_NAMES[t.role]}</b> {scenes.find(s=>s.id===t.sceneId)?.title} · {t.error?'Требует внимания':t.applied?'Готово':job?'В работе':t.requires.some(id=>run.tasks.find(v=>v.id===id)?.error)?'Ожидает решения по предыдущему шагу':'Ожидает'}{job&&<small> · расход: {money(job.actual)}</small>}{t.error&&<p role="alert">{t.error}</p>}{t.error&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>call('retry',{runId:run.id,taskId:t.id,acknowledgeCost:true})}>{job?.status==='unknown'?'Повторить с возможным повторным списанием':'Повторить только это задание'}</Button>}</div>;})}</div>
      {!run.stopped&&<Button className="mt-3" variant="outline" disabled={busy} onClick={()=>call('stop',{runId:run.id})}>Остановить дальнейшую проработку</Button>}
    </details>}
  </section>;
}
