'use client';
import {MODELS} from '@/lib/models';
import type {DirectorExecution} from '@/lib/director-reliability';
import type {Project} from '@/lib/domain';
import {money} from '@/lib/domain';
import {ROLE_NAMES,directorRunActive,type DirectorRun} from '@/lib/directing';
import {Button} from '@/components/ui/button';
const textModels=MODELS.filter(m=>m.kind==='text'&&['openai','xai','minimax'].includes(m.provider));
export function DirectorExecutionControls({model,value,disabled,onChange}:{model:string;value:DirectorExecution;disabled:boolean;onChange:(value:DirectorExecution)=>void}){const secondary=value.parallelModels?.find(id=>id!==model)??'';return <details className="border rounded p-3"><summary>Параллельные модели и резерв</summary><div className="grid gap-3 md:grid-cols-2 mt-3"><label>Дополнительная модель команды<select className="w-full border rounded p-2 bg-background" aria-label="Дополнительная модель команды" disabled={disabled} value={secondary} onChange={e=>onChange({...value,parallelModels:e.target.value?[model,e.target.value]:[]})}><option value="">Одна модель</option>{textModels.filter(m=>m.id!==model).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Резервная модель<select className="w-full border rounded p-2 bg-background" aria-label="Резервная модель команды" disabled={disabled} value={value.fallbackModel??''} onChange={e=>onChange({...value,fallbackModel:e.target.value||undefined})}><option value="">Без автоматического резерва</option>{textModels.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div><p className="muted mt-3">Независимые задачи распределяются между моделями. Для подробных заданий — до трёх планов в запросе, с учётом соседей. Число одновременных запросов задаётся в журнале, в настройках очереди. Проверки сцены и фильма выполняются после специалистов.</p><p className="muted">Резерв делает максимум одну дополнительную оплачиваемую попытку при неправильном формате, неполном ответе или HTTP 429. Расход каждой попытки сохраняется отдельно. Неизвестный исход, ошибки ключа, баланс и запреты по содержимому требуют вашего решения.</p></details>;}
export function DirectorRunStatus({p,run,busy,submit}:{p:Project;run?:DirectorRun;busy:boolean;submit:(action:string,data?:unknown)=>Promise<void>}){if(!run)return null;const active=directorRunActive(run);return <details open={active||run.tasks.some(t=>t.error)}><summary>Работа команды · {run.tasks.filter(t=>t.applied).length}/{run.tasks.length}</summary>{run.queueIssue&&<p role="alert">{run.queueIssue}</p>}<p className="muted">На этом сайте оставьте студию открытой. В самостоятельной серверной версии очередь работает в фоне.</p><div className="space-y-2">{run.tasks.map(t=>{const job=p.jobs.find(j=>j.id===t.jobId),history=p.jobs.filter(j=>t.previousJobIds?.includes(j.id));return <div key={t.id} className="border rounded p-3"><b>{ROLE_NAMES[t.role]}</b> · {p.directing?.scenes.find(s=>s.id===t.sceneId)?.title} {t.shotIds?.length?`· ${t.shotIds.length} плана`:t.shotId?'· 1 план':''} · {t.applied?'Готово':t.error?'Требует внимания':job?'В работе':'Ожидает'}{job&&<small> · {MODELS.find(m=>m.id===job.model)?.name??job.model} · расход {money(job.actual)}</small>}{t.fallbackFromJobId&&<p className="muted">Резервная попытка. Предыдущие списания: {history.map(j=>money(j.actual)).join(', ')}.</p>}{t.error&&<><p role="alert" className="whitespace-pre-wrap">{t.error}</p><div className="row wrap">{job?.status==='failed'&&job.output?.text&&!run.stopped&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>submit('repairSavedAnswer',{runId:run.id,taskId:t.id})}>Исправить формат сохранённого ответа · без генерации</Button>}<Button size="sm" variant="outline" disabled={busy} onClick={()=>submit('retry',{runId:run.id,taskId:t.id,acknowledgeCost:true})}>{job?.status==='unknown'?'Повторить с возможным повторным списанием':'Повторить только это задание'}</Button></div></>}</div>;})}</div>{!run.stopped&&active&&<Button className="mt-3" variant="outline" disabled={busy} onClick={()=>submit('stop',{runId:run.id})}>Остановить дальнейшую проработку</Button>}</details>;}
