'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {MODELS} from '@/lib/models';
import {id,type Project} from '@/lib/domain';
import {directorRunActive,scenesBasis} from '@/lib/directing';
import {PLAN_POLICIES,planningScene,planningPolicy,planningInputBasis,planSetApproved,allPlanSetsApproved,type PlanPolicy,type PlanSketch} from '@/lib/shot-planning';
import {FRAMINGS,FRAMING_NAMES} from '@/lib/shot-direction';
import {DirectorExecutionControls,DirectorRunStatus} from './director-execution-controls';
import type {DirectorExecution} from '@/lib/director-reliability';
import {VersionComparison} from './version-comparison';
const describe=(cards:PlanSketch[])=>cards.map((c,n)=>`${n+1}. ${c.title} · ${c.duration} сек · ${FRAMING_NAMES[c.framing]}\nЗадача: ${c.purpose}\n${c.action}\nУчастники: ${c.cast.join(', ')}\nНачало: ${c.stateIn}\nКонец: ${c.stateOut}\nРечь: ${c.speechType} · ${c.speaker}: ${c.text}\nСтык: ${c.transition}`).join('\n\n');
export function ShotPlanningEditor({p,busy,submit,open}:{p:Project;busy:boolean;submit:(action:string,data?:unknown)=>Promise<void>;open:(stage:number)=>void}){const scenes=p.directing?.scenes??[];const [sceneId,setSceneId]=useState(scenes[0]?.id??''),[selected,setSelected]=useState(scenes.map(s=>s.id)),[edit,setEdit]=useState<PlanSketch>(),[mergeError,setMergeError]=useState(''),[mergeIds,setMergeIds]=useState<string[]>([]);const [model,setModel]=useState(MODELS.find(m=>m.kind==='text'&&m.provider==='openai')!.id),[execution,setExecution]=useState<DirectorExecution>({});const scene=scenes.find(s=>s.id===sceneId)??scenes[0],state=p.directing?.shotPlanning,row=scene&&planningScene(p,scene),run=p.directing?.runs.filter(r=>r.mode==='plan-shots').at(-1);const readyScenes=scenes.filter(s=>planningScene(p,s).cards.length);const locked=busy||!!p.directing?.runs.some(directorRunActive),structureReady=!!scenes.length&&p.directing?.scenesApproved===scenesBasis(p);const call=submit;
  const save=(cards:PlanSketch[])=>call('savePlanCards',{sceneId:scene!.id,cards});const move=(index:number,offset:number)=>{const cards=[...row!.cards];[cards[index],cards[index+offset]]=[cards[index+offset],cards[index]];return save(cards);};
  const merge=()=>{const indices=row!.cards.map((c,n)=>mergeIds.includes(c.id)?n:-1).filter(n=>n>=0);if(indices.length<2||indices.some((n,k)=>k>0&&n!==indices[k-1]+1))throw Error('Выберите соседние планы.');const parts=indices.map(n=>row!.cards[n]),spoken=parts.filter(c=>c.speechType!=='none');if(spoken.some(c=>c.speechType!==spoken[0].speechType||c.speaker!==spoken[0].speaker))throw Error('Для разных говорящих оставьте отдельные планы.');const first=parts[0],last=parts.at(-1)!;const combined:PlanSketch={...first,title:first.title+' / '+last.title,action:parts.map(c=>c.action).join('\n'),purpose:parts.map(c=>c.purpose).join('; '),duration:parts.reduce((n,c)=>n+c.duration,0),cast:[...new Set(parts.flatMap(c=>c.cast))],stateOut:last.stateOut,transition:last.transition,speechType:spoken[0]?.speechType??'none',speaker:spoken[0]?.speaker??'',text:spoken.map(c=>c.text).join(' ')};setEdit(combined);};
  return <section className="editor-surface p-5 space-y-5" aria-label="Планы сцен"><h2>Сначала выберите монтажный набор</h2><p className="muted">Выберите плотность монтажа, создайте короткие варианты, уберите повторы и утвердите набор. Затем команда подробно проработает сценарий, оператора, художника и реплики. Генерация нового варианта сохраняет прежний до вашего выбора.</p>{!structureReady&&<p role="status">Сначала подготовьте и утвердите <Button variant="link" onClick={()=>open(12)}>структуру сцен</Button>.</p>}
    <div className="grid gap-4 md:grid-cols-2"><label>Плотность монтажа фильма<select className="w-full border rounded p-2 bg-background" aria-label="Плотность монтажа фильма" value={state?.policy??'balanced'} disabled={locked} onChange={e=>call('planPolicy',{policy:e.target.value})}>{Object.entries(PLAN_POLICIES).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><label>Модель монтажного плана<select className="w-full border rounded p-2 bg-background" aria-label="Модель монтажного плана" value={model} disabled={locked} onChange={e=>{setModel(e.target.value);setExecution({...execution,parallelModels:[]});}}>{MODELS.filter(m=>m.kind==='text'&&['openai','xai','minimax'].includes(m.provider)).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div><p className="muted">Экономичный — необходимые события и реакции; обычный — сбалансированное покрытие; подробный — дополнительные детали, точки зрения и паузы. Число планов не фиксируется, длинный перегруженный клип не считается экономией.</p><DirectorExecutionControls model={model} value={execution} disabled={locked} onChange={setExecution}/>
    <div className="flex flex-wrap gap-3">{scenes.map(s=><label className="row" key={s.id}><input type="checkbox" disabled={locked} checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/>{s.title}</label>)}</div><div className="row wrap"><Button disabled={locked||!structureReady||!scenes.length} onClick={()=>call('run',{model,execution,mode:'plan-shots',scope:'all'})}>Создать планы всех сцен</Button><Button variant="outline" disabled={locked||!structureReady||!selected.length} onClick={()=>call('run',{model,execution,mode:'plan-shots',scope:'selected',sceneIds:selected})}>Создать выбранные сцены · {selected.length}</Button></div><p className="muted">Один текстовый запрос на сцену. Разные сцены могут создаваться параллельно в пределах очереди. Выбирайте варианты отдельно для каждой сцены.</p>
    {scene&&row&&<><label>Сцена<select className="w-full border rounded p-2 bg-background" value={scene.id} onChange={e=>{setSceneId(e.target.value);setMergeIds([]);setEdit(undefined);}}>{scenes.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><label>Плотность этой сцены<select className="w-full border rounded p-2 bg-background" aria-label="Плотность этой сцены" value={planningPolicy(p,scene.id)} disabled={locked} onChange={e=>call('planPolicy',{policy:e.target.value as PlanPolicy,sceneId:scene.id})}>{Object.entries(PLAN_POLICIES).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>
      <VersionComparison title="Сравнить варианты монтажного плана" disabled={locked} versions={[{id:'current',label:'Текущий набор · '+scene.title,text:describe(row.cards)},...(state?.proposals.filter(v=>v.sceneId===scene.id)??[]).map(v=>({id:v.id,label:`${PLAN_POLICIES[v.policy]} · ${MODELS.find(m=>m.id===v.model)?.name??v.model} · ${new Date(v.created).toLocaleString('ru')}`,text:describe(v.cards)}))]} renderActions={version=>version.id!=='current'&&<Button disabled={locked||state?.proposals.find(v=>v.id===version.id)?.basis!==planningInputBasis(p,scene)} onClick={()=>call('choosePlanSet',{proposalId:version.id})}>Выбрать этот набор для сцены</Button>}/>
      <h3>{scene.title} · {row.cards.length} планов · {row.cards.reduce((n,c)=>n+c.duration,0).toFixed(1)} сек · {planSetApproved(p,scene)?'✓ Набор утверждён':'На рассмотрении'}</h3>{row.cards.map((c,n)=><article className="border rounded p-4 space-y-2" key={c.id}><div className="row spread wrap"><label className="row"><input type="checkbox" disabled={locked} checked={mergeIds.includes(c.id)} onChange={e=>setMergeIds(e.target.checked?[...mergeIds,c.id]:mergeIds.filter(id=>id!==c.id))}/><b>{n+1}. {c.title}</b></label><span>{c.duration} сек · {FRAMING_NAMES[c.framing]}</span></div><p>{c.action}</p><p className="muted">Зачем: {c.purpose} · Герои: {c.cast.join(', ')||'нет'} · {c.speechType==='none'?'Без речи':c.speechType==='character'?`Реплика ${c.speaker}`:'За кадром'}</p>{c.text&&<p>{c.text}</p>}<p className="muted">Стык: {c.transition||'Уточняется при подробной проработке'}</p><div className="row wrap"><Button size="sm" variant="outline" disabled={locked} onClick={()=>{setMergeIds([]);setEdit(structuredClone(c));}}>Правки</Button><Button size="sm" variant="outline" disabled={locked||n===0} onClick={()=>move(n,-1)}>↑</Button><Button size="sm" variant="outline" disabled={locked||n===row.cards.length-1} onClick={()=>move(n,1)}>↓</Button><Button size="sm" variant="ghost" disabled={locked||row.cards.length===1} onClick={()=>save(row.cards.filter(v=>v.id!==c.id))}>Исключить план</Button></div></article>)}<div className="row wrap"><Button variant="outline" disabled={locked} onClick={()=>{setMergeIds([]);setEdit({id:id(),title:'Новый план',duration:5,cast:[],action:'',purpose:'',framing:'medium',stateIn:'',stateOut:'',speechType:'none',speaker:'',text:'',transition:''});}}>Добавить план</Button><Button variant="outline" disabled={locked||mergeIds.length<2||mergeIds.some((id,k)=>k>0&&Math.abs(row.cards.findIndex(c=>c.id===id)-row.cards.findIndex(c=>c.id===mergeIds[k-1]))!==1)} onClick={()=>{try{setMergeError('');merge();}catch(e){setMergeError((e as Error).message);}}}>Объединить выбранные — проверить текст</Button><Button disabled={locked||!structureReady||!row.cards.length} onClick={()=>call('approvePlanSets',{sceneIds:[scene.id]})}>Утвердить набор этой сцены</Button></div>
      {mergeError&&<p role="alert">{mergeError}</p>}{edit&&<div className="border rounded p-4 space-y-3"><h3>Правки короткого плана</h3><label>Название<Input value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><div className="grid gap-3 md:grid-cols-2"><label>Длительность, сек<Input type="number" min={.5} max={60} step={.1} value={edit.duration} onChange={e=>setEdit({...edit,duration:Number(e.target.value)})}/></label><label>Крупность<select className="w-full border rounded p-2 bg-background" value={edit.framing} onChange={e=>setEdit({...edit,framing:e.target.value as PlanSketch['framing']})}>{FRAMINGS.map(f=><option key={f} value={f}>{FRAMING_NAMES[f]}</option>)}</select></label></div><label>Участники через запятую<Input value={edit.cast.join(', ')} onChange={e=>setEdit({...edit,cast:e.target.value.split(',').map(s=>s.trim()).filter(Boolean)})}/></label>{(['action','purpose','stateIn','stateOut','transition'] as const).map((key,n)=><label key={key} className="block">{['Действие','Задача плана','Начальное состояние','Конечное состояние','Монтажный стык'][n]}<Textarea value={edit[key]} onChange={e=>setEdit({...edit,[key]:e.target.value})}/></label>)}<label>Тип речи<select className="w-full border rounded p-2 bg-background" value={edit.speechType} onChange={e=>setEdit({...edit,speechType:e.target.value as PlanSketch['speechType'],...(e.target.value==='none'?{speaker:'',text:''}:{})})}><option value="none">Без речи</option><option value="voiceover">За кадром</option><option value="character">Герой в кадре</option></select></label><label>Говорящий<Input value={edit.speaker} onChange={e=>setEdit({...edit,speaker:e.target.value})}/></label><label>Произносимый текст<Textarea value={edit.text} onChange={e=>setEdit({...edit,text:e.target.value})}/></label><div className="row"><Button disabled={locked||!edit.action.trim()||!edit.purpose.trim()||edit.duration>60||edit.title.length>100} onClick={async()=>{const cards=row.cards.some(c=>c.id===edit.id)?row.cards.map(c=>c.id===edit.id?edit:c).filter(c=>!mergeIds.includes(c.id)||c.id===edit.id):[...row.cards,edit];await save(cards);setEdit(undefined);setMergeIds([]);}}>Сохранить план</Button><Button variant="ghost" onClick={()=>setEdit(undefined)}>Закрыть</Button></div></div>}
      {!!row.archive.length&&<details><summary>Исключённые планы · {row.archive.length}</summary>{row.archive.filter(c=>!row.cards.some(v=>v.id===c.card.id)).map((entry,n)=><div key={entry.card.id+':'+n} className="row spread"><span>{entry.card.title}</span><Button size="sm" variant="outline" disabled={locked} onClick={()=>call('restorePlanCard',{sceneId:scene.id,shotId:entry.card.id})}>Восстановить</Button></div>)}</details>}
    </>}
    <div className="row wrap"><Button disabled={locked||!structureReady||!readyScenes.length} onClick={()=>call('approvePlanSets',{sceneIds:readyScenes.map(s=>s.id)})}>Утвердить все готовые наборы</Button><Button variant="outline" disabled={!allPlanSetsApproved(p)} onClick={()=>open(4)}>Перейти к подробной проработке</Button></div><DirectorRunStatus p={p} run={run} busy={busy} submit={submit}/>
  </section>;
}
