'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {money,type Project} from '@/lib/domain';
import {readSoundscape,soundLayerSchema,soundLayerIssue,soundLayerApproved,soundJobs,soundscapeSuggestions,SOUND_KINDS,SOUND_KIND_NAMES,type SoundLayer,type SoundSettings,type SoundScope,type SoundscapeProject} from '@/lib/soundscape';

export type SoundscapeEditorProps={p:Project;busy:boolean;submit:(action:string,data:Record<string,unknown>)=>Promise<void>;upload:(file:File)=>Promise<string>};
const Field=({label,children}:{label:string;children:ReactNode})=><label className="block space-y-1"><span className="text-sm">{label}</span>{children}</label>;
const errorText=(e:unknown)=>e instanceof Error?e.message:'Не удалось сохранить звуковой слой.';
type Measurement={layerId:string;variantId:string;seconds:number};
const measuredLayer=(layer:SoundLayer,measurements:Record<string,Measurement>):SoundLayer=>({...layer,variants:layer.variants.map(v=>measurements[v.id]?{...v,seconds:measurements[v.id].seconds}:v)});
function ScopeField({p,value,onChange,disabled}:{p:Project;value:SoundScope;onChange:(scope:SoundScope)=>void;disabled:boolean}){
  const plans=p.items.filter(i=>i.stage===(p.items.some(i=>i.stage===7&&!i.removedAt&&!i.planArchive)?7:5)&&!i.removedAt&&!i.excludedAt&&!i.planArchive);
  const current=value.type==='film'?'film':value.type==='plan'?'plan:'+value.itemId:'scene:'+value.sceneId;
  return <Field label="Где звучит слой"><select aria-label="Область звукового слоя" className="rounded border p-2 bg-background w-full" value={current} disabled={disabled} onChange={e=>{const v=e.target.value;if(v==='film')onChange({type:'film'});else if(v.startsWith('plan:'))onChange({type:'plan',itemId:v.slice(5)});else onChange({type:'scene',sceneId:v.slice(6)});}}><option value="film">Весь фильм</option>{p.directing?.scenes.map(s=><option key={s.id} value={'scene:'+s.id}>{s.title}</option>)}{plans.map(i=><option key={i.id} value={'plan:'+i.id}>{i.title}</option>)}{value.type==='plan'&&!plans.some(i=>i.id===value.itemId)&&<option value={current}>План из раскадровки · сохранённая область</option>}</select></Field>;
}
function LayerEditor({p,layer,locked,execute,upload,measurements,onMeasure}:{p:Project;layer:SoundLayer;locked:boolean;execute:(a:string,d:Record<string,unknown>,message?:string)=>Promise<void>;upload:(file:File)=>Promise<string>;measurements:Record<string,Measurement>;onMeasure:(value:Measurement)=>void}){
  const [name,setName]=useState(layer.name),[scope,setScope]=useState(layer.scope),[settings,setSettings]=useState(layer.settings),[prompt,setPrompt]=useState((layer.promptNotes??layer.name).slice(0,450)),[duration,setDuration]=useState(8),[count,setCount]=useState(1),[influence,setInfluence]=useState(.5),[batchId,setBatchId]=useState(()=>crypto.randomUUID()),[uploading,setUploading]=useState(false),[uploadError,setUploadError]=useState('');
  const canonical=JSON.stringify({name:layer.name,scope:layer.scope,settings:layer.settings});useEffect(()=>{const value=JSON.parse(canonical);setName(value.name);setScope(value.scope);setSettings(value.settings);},[canonical]);
  const patch=(value:Partial<SoundSettings>)=>setSettings({...settings,...value}),disabled=locked||uploading;
  const measured=measuredLayer(layer,measurements);
  const changed=JSON.stringify({name,scope,settings})!==canonical;
  const uploadFile=async(file:File)=>{setUploading(true);setUploadError('');try{const assetId=await upload(file);await execute('addVariant',{layerId:layer.id,assetId,description:file.name},'Звук добавлен. Прослушайте и выберите вариант.');}catch(e){setUploadError(errorText(e));}finally{setUploading(false);}};
  return <article className="editor-surface p-5 space-y-4">
    <div className="flex gap-3 justify-between"><h3>{SOUND_KIND_NAMES[layer.kind]} · {layer.name}</h3><Button variant="ghost" disabled={disabled} onClick={()=>execute('removeLayer',{layerId:layer.id},'Слой удалён из рабочего списка.')}>Удалить слой</Button></div>
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Название"><Input value={name} maxLength={120} disabled={disabled} onChange={e=>setName(e.target.value)}/></Field><ScopeField p={p} value={scope} onChange={setScope} disabled={disabled}/></div>
    <div className="flex flex-wrap gap-4"><label><input type="checkbox" checked={settings.enabled} disabled={disabled} onChange={e=>patch({enabled:e.target.checked})}/> Использовать слой</label><label><input type="checkbox" checked={settings.loop} disabled={disabled} onChange={e=>patch({loop:e.target.checked})}/> Повторять файл</label><label><input type="checkbox" checked={settings.duckSpeech} disabled={disabled} onChange={e=>patch({duckSpeech:e.target.checked})}/> Приглушать во время речи</label></div>
    <div className="grid gap-3 sm:grid-cols-3">{([{key:'offset',label:'Начало в плане/области, сек'},{key:'trim',label:'Начало в исходном файле, сек'},{key:'duration',label:'Длительность слоя, сек (пусто — автоматически)'},{key:'volume',label:'Обычная громкость, 0–2'},{key:'speechVolume',label:'Громкость во время речи, 0–2'},{key:'fadeIn',label:'Плавное появление, сек'},{key:'fadeOut',label:'Плавное затухание, сек'}] as const).map(({key,label})=><Field label={label} key={key}><Input aria-label={label} type="number" min={0} max={['volume','speechVolume'].includes(key)?2:key.startsWith('fade')?10:3600} step={.05} value={settings[key]??''} disabled={disabled} onChange={e=>patch({[key]:key==='duration'&&!e.target.value?null:Number(e.target.value)})}/></Field>)}</div>
    <Button variant="outline" disabled={disabled||!changed} onClick={()=>execute('saveLayer',{layerId:layer.id,layer:{name,kind:layer.kind,scope,settings,promptNotes:layer.promptNotes}},'Настройки сохранены. Просмотрите и утвердите слой для нового монтажа.')}>Сохранить настройки слоя</Button>
    {uploadError&&<p role="alert">{uploadError}</p>}<Field label="Загрузить свой звук"><input aria-label={`Загрузить звук ${layer.name}`} type="file" accept="audio/*" disabled={disabled} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadFile(file);e.target.value='';}}/></Field>
    <div className="grid gap-3 md:grid-cols-2">{layer.variants.filter(v=>!v.removedAt).slice().reverse().map(v=><section className="border rounded p-3 space-y-2" key={v.id}><h4>{v.model} · {new Date(v.created).toLocaleString('ru-RU')}{layer.selectedId===v.id?' · ✓ выбран':''}</h4><audio controls preload="metadata" src={'/api/assets/'+v.assetId} onLoadedMetadata={e=>{const seconds=e.currentTarget.duration;if(Number.isFinite(seconds)&&seconds>0)onMeasure({layerId:layer.id,variantId:v.id,seconds});}} onPlay={e=>{e.currentTarget.closest('section[aria-label]')?.querySelectorAll('audio').forEach(a=>{if(a!==e.currentTarget)a.pause();});}}/><p>{(measurements[v.id]?.seconds??v.seconds)?`${(measurements[v.id]?.seconds??v.seconds)!.toFixed(2)} сек`:'Длительность проверяется по аудиофайлу'}</p><details><summary>Описание генерации</summary><p>{v.prompt}</p></details><div className="flex gap-2"><Button disabled={disabled} variant={layer.selectedId===v.id?'secondary':'outline'} onClick={()=>execute('choose',{layerId:layer.id,variantId:v.id},'Вариант звука выбран для слоя.')}>{layer.selectedId===v.id?'✓ Выбран':'Выбрать'}</Button><Button variant="ghost" disabled={disabled} onClick={()=>execute('removeVariant',{layerId:layer.id,variantId:v.id},'Вариант удалён из рабочего списка.')}>Удалить</Button></div></section>)}</div>
    {soundLayerIssue(measured)&&<p className="text-sm">{soundLayerIssue(measured)}</p>}<Button disabled={disabled||changed||!!soundLayerIssue(measured)||soundLayerApproved(measured)} onClick={()=>execute('approve',{layerId:layer.id,seconds:measurements[layer.selectedId??'']?.seconds},'Выбранный файл и настройки звукового слоя утверждены.')}>{soundLayerApproved(measured)?'✓ Звуковой слой утверждён':'Утвердить звуковой слой'}</Button>
    <details><summary>Создать звук с ИИ · ElevenLabs Sound Effects v2</summary><div className="space-y-3 mt-3"><Field label={`Описание звука · ${prompt.length}/450`}><Textarea value={prompt} maxLength={450} disabled={disabled} onChange={e=>{setPrompt(e.target.value);setBatchId(crypto.randomUUID());}}/></Field><div className="grid gap-3 sm:grid-cols-3"><Field label="Длительность пробы, сек"><Input type="number" min={.5} max={30} step={.5} value={duration} disabled={disabled} onChange={e=>{setDuration(Number(e.target.value));setBatchId(crypto.randomUUID());}}/></Field><Field label="Количество попыток"><Input type="number" min={1} max={4} value={count} disabled={disabled} onChange={e=>{setCount(Number(e.target.value));setBatchId(crypto.randomUUID());}}/></Field><Field label={`Следование описанию · ${influence}`}><input type="range" min={0} max={1} step={.1} value={influence} disabled={disabled} onChange={e=>{setInfluence(Number(e.target.value));setBatchId(crypto.randomUUID());}}/></Field></div><p className="text-sm">Стоимость зависит от тарифа аккаунта. Каждый вариант — отдельная попытка; единицы, подтверждённые провайдером, сохраняются в журнале. Зацикленную пробу можно повторять в монтаже дольше 30 секунд.</p><Button disabled={disabled||!prompt.trim()||duration<.5||duration>30||!Number.isInteger(count)||count<1||count>4} onClick={()=>execute('generate',{batchId,layerId:layer.id,generation:{prompt,duration,loop:settings.loop,influence,count}},'Проба звука добавлена в очередь. Выбор и утверждение будут отдельными действиями.')}>Создать варианты звука</Button></div></details>
    {layer.variants.some(v=>v.removedAt)&&<details><summary>Удалённые варианты</summary>{layer.variants.filter(v=>v.removedAt).map(v=><p key={v.id}>{v.model}<Button disabled={disabled} variant="ghost" onClick={()=>execute('restoreVariant',{layerId:layer.id,variantId:v.id},'Вариант восстановлен без выбора и утверждения.')}>Восстановить</Button></p>)}</details>}
  </article>;
}
/** Optional sound layers; viewing/playing stored sounds never creates a generation. */
export function SoundscapeEditor({p,busy,submit,upload}:SoundscapeEditorProps){
  const s=readSoundscape(p as SoundscapeProject),jobs=soundJobs(p),suggestions=soundscapeSuggestions(p);
  const [working,setWorking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[name,setName]=useState('Звуковая атмосфера'),[kind,setKind]=useState<SoundLayer['kind']>('ambience'),[scope,setScope]=useState<SoundScope>({type:'film'});
  const [measurements,setMeasurements]=useState<Record<string,Measurement>>({});
  const onMeasure=(value:Measurement)=>setMeasurements(previous=>Math.abs((previous[value.variantId]?.seconds??0)-value.seconds)>.001?{...previous,[value.variantId]:value}:previous);
  const locked=busy||working,execute=async(action:string,data:Record<string,unknown>,message='')=>{setWorking(true);setError('');setNotice('');try{await submit(action,data);if(message)setNotice(message);}catch(e){setError(errorText(e));}finally{setWorking(false);}};
  const layerInput=(description?:string,offset=0,loop=kind==='ambience')=>soundLayerSchema.parse({name,kind,scope,settings:{loop,offset,volume:kind==='ambience'?.25:.7,speechVolume:kind==='ambience'?.06:.25},promptNotes:description});
  return <section aria-label="Атмосфера и звуковые эффекты" className="space-y-5">
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <div className="editor-surface p-5 space-y-4"><h2>Атмосфера и звуковые эффекты</h2><p>Отдельные дорожки окружения, действий и звуковых акцентов. Утверждённые слои добавляются при итоговой сборке с плавным приглушением во время речи.</p><label><input type="checkbox" checked={s.enabled} disabled={locked} onChange={e=>execute('enable',{enabled:e.target.checked},'Использование звуковых слоёв изменено.')}/> Использовать звуковые слои при сборке</label>
      <div className="grid gap-3 sm:grid-cols-3"><Field label="Название нового слоя"><Input value={name} maxLength={120} disabled={locked} onChange={e=>setName(e.target.value)}/></Field><Field label="Тип"><select className="rounded border p-2 bg-background" value={kind} disabled={locked} onChange={e=>setKind(e.target.value as typeof kind)}>{SOUND_KINDS.map(v=><option value={v} key={v}>{SOUND_KIND_NAMES[v]}</option>)}</select></Field><ScopeField p={p} value={scope} onChange={setScope} disabled={locked}/></div><Button disabled={locked||!name.trim()} onClick={()=>execute('saveLayer',{layer:layerInput()},'Звуковой слой создан. Загрузите файл или создайте звук с ИИ.')}>Добавить звуковой слой</Button>
      <Button variant="outline" disabled={locked||!s.layers.some(l=>{const v=measuredLayer(l,measurements);return !v.removedAt&&v.settings.enabled&&v.selectedId&&!soundLayerIssue(v)&&!soundLayerApproved(v);})} onClick={()=>execute('approveReady',{measurements:Object.values(measurements).filter(m=>s.layers.some(l=>!l.removedAt&&l.settings.enabled&&l.id===m.layerId&&l.selectedId===m.variantId))},'Выбранные готовые звуковые слои утверждены.')}>Утвердить выбранные готовые слои</Button>
      {suggestions.length>0&&<details><summary>Звуки, прописанные в подробном сценарии · {suggestions.length}</summary><div className="space-y-2 mt-2">{suggestions.map((v,n)=><article className="border rounded p-3" key={n}><p>{v.name} · на {v.offset} сек</p><p>{v.description}</p><Button disabled={locked} variant="outline" onClick={()=>execute('saveLayer',{layer:{name:v.name.slice(0,120),kind:v.kind,scope:v.scope,promptNotes:v.description.slice(0,2000),settings:{loop:v.loop,offset:v.offset,volume:v.kind==='ambience'?.25:.7,speechVolume:v.kind==='ambience'?.06:.25}}},'Описание из сценария добавлено как слой. Генерация не запускалась.')}>Добавить описание как слой</Button></article>)}</div></details>}
    </div>
    {s.layers.filter(l=>!l.removedAt).map(l=><LayerEditor key={p.id+':'+l.id} p={p} layer={l} locked={locked} execute={execute} upload={upload} measurements={measurements} onMeasure={onMeasure}/>)}
    {jobs.length>0&&<div className="editor-surface p-5 space-y-3"><h3>Попытки создания звука</h3>{jobs.slice().reverse().map(j=><article key={j.id} className="border rounded p-3 space-y-2"><p>{j.brief} · {j.status} · {j.actual===null?'Стоимость уточняется':money(j.actual)}</p>{j.usage!==undefined&&<details><summary>Единицы, подтверждённые API</summary><pre>{JSON.stringify(j.usage,null,2)}</pre></details>}{j.error&&<p role="alert">{j.error}</p>}<div className="flex gap-2">{['queued','saving'].includes(j.status)&&<Button disabled={locked} variant="outline" onClick={()=>execute('advance',{jobId:j.id},'Состояние попытки обновлено.')}>{j.status==='saving'?'Повторить сохранение файла':'Запустить эту попытку'}</Button>}{['queued','dispatching'].includes(j.status)&&<Button disabled={locked} variant="ghost" onClick={()=>execute('stop',{jobId:j.id},'Ожидание остановлено; платный запрос не повторяется.')}>Остановить ожидание</Button>}{j.status==='unknown'&&!j.newSeriesAllowedAt&&<Button disabled={locked} variant="outline" onClick={()=>execute('allowNewSeries',{jobId:j.id},'Новая отдельная серия разрешена. Исход предыдущего платного запроса остаётся неизвестным.')}>Разрешить новую отдельную серию</Button>}</div><details><summary>Фактический запрос</summary><pre className="whitespace-pre-wrap text-xs">{j.prompt}</pre></details></article>)}</div>}
    {s.layers.some(l=>l.removedAt)&&<details><summary>Удалённые звуковые слои</summary>{s.layers.filter(l=>l.removedAt).map(l=><p key={l.id}>{l.name}<Button disabled={locked} variant="ghost" onClick={()=>execute('restoreLayer',{layerId:l.id},'Слой восстановлен. Выбор и утверждение выполняются отдельно.')}>Восстановить</Button></p>)}</details>}
  </section>;
}
