'use client';
import {useEffect,useState,type ReactNode} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {chosen,money,type Project} from '@/lib/domain';
import {MODELS} from '@/lib/models';
import {readVoiceStudio,voiceDeliveryFor,readableVoiceDelivery,compileVoiceSpeech,VOICE_EMOTIONS,VOICE_EMOTION_NAMES,type VoiceDelivery,type VoiceStudioProject} from '@/lib/voice-direction';
import {validateVoiceDesignInput,voiceDesignEstimate,voiceWorkflowJobs,voiceDirectionPrompt} from '@/lib/voice-design';
import {VersionComparison} from './version-comparison';

const Field=({label,children}:{label:string;children:ReactNode})=><label className="block space-y-1"><span className="text-sm font-medium">{label}</span>{children}</label>;
const errorText=(e:unknown)=>e instanceof Error?e.message:'Не удалось сохранить действие.';
export type VoiceEditorProps={p:Project;itemId?:string;model:string;busy:boolean;submit:(action:string,data:Record<string,unknown>)=>Promise<void>;speechModel?:string;allowDesign?:boolean};
export function VoiceDirectionFields({value,onChange,disabled}:{value:VoiceDelivery;onChange:(v:VoiceDelivery)=>void;disabled:boolean}){
  const patch=(v:Partial<VoiceDelivery>)=>onChange({...value,...v});
  return <div className="space-y-3">
    <div className="grid gap-3 sm:grid-cols-2"><Field label="Эмоция"><select aria-label="Эмоция исполнения" className="w-full rounded border p-2 bg-background" disabled={disabled} value={value.emotion??''} onChange={e=>patch({emotion:e.target.value?e.target.value as VoiceDelivery['emotion']:undefined})}><option value="">Не задана</option>{VOICE_EMOTIONS.map(v=><option key={v} value={v}>{VOICE_EMOTION_NAMES[v]}</option>)}</select></Field>
      <Field label="Целевая длительность, сек"><Input aria-label="Целевая длительность речи" type="number" min={.2} max={600} step={.1} disabled={disabled} value={value.targetSeconds??''} onChange={e=>patch({targetSeconds:e.target.value?Number(e.target.value):undefined})}/></Field></div>
    <Field label="Актёрская задача · не произносится"><Textarea maxLength={1500} disabled={disabled} value={value.intention??''} onChange={e=>patch({intention:e.target.value})}/></Field>
    <Field label={`Темп исполнения · ${value.speed??1}×`}><input aria-label="Темп исполнения" type="range" min={.7} max={1.2} step={.01} disabled={disabled} value={value.speed??1} onChange={e=>patch({speed:Number(e.target.value)})}/></Field>
    <p className="text-sm text-muted-foreground">Длительность — ориентир. После генерации сравните фактическую запись с видеопланом; слова не обрезаются и звук не ускоряется при сборке автоматически.</p>
    <div className="space-y-2"><h4>Паузы между фрагментами</h4>{(value.pauses??[]).map((pause,n)=><div key={n} className="grid gap-2 sm:grid-cols-[1fr_100px_auto]">
      <Input aria-label={`После каких слов ${n+1}`} placeholder="Уникальные слова из реплики" value={pause.after} maxLength={300} disabled={disabled} onChange={e=>patch({pauses:value.pauses!.map((v,i)=>i===n?{...v,after:e.target.value}:v)})}/>
      <Input aria-label={`Пауза ${n+1}, сек`} type="number" min={.01} max={3} step={.05} value={pause.seconds} disabled={disabled} onChange={e=>patch({pauses:value.pauses!.map((v,i)=>i===n?{...v,seconds:Number(e.target.value)}:v)})}/>
      <Button variant="ghost" disabled={disabled} onClick={()=>patch({pauses:value.pauses!.filter((_,i)=>i!==n)})}>Убрать</Button>
    </div>)}<Button variant="outline" disabled={disabled||(value.pauses?.length??0)>=12} onClick={()=>patch({pauses:[...value.pauses??[],{after:'',seconds:.5}]})}>Добавить паузу</Button></div>
    <details><summary>Настройки ElevenLabs</summary><div className="space-y-2 mt-2">{(['stability','similarity','style'] as const).map(key=><Field label={`${key} · ${value[key]??'по умолчанию'}`} key={key}><input aria-label={key} type="range" min={0} max={1} step={.05} disabled={disabled} value={value[key]??(key==='style'?0:key==='similarity'?.75:.5)} onChange={e=>patch({[key]:Number(e.target.value)})}/></Field>)}</div></details>
  </div>;
}
/** Viewing, selecting a comparison pane and playing stored audio never invoke an LLM. */
export function VoiceDirectionEditor({p,itemId,model,busy,submit,speechModel,allowDesign=true}:VoiceEditorProps){
  const project=p as VoiceStudioProject,s=readVoiceStudio(project),item=p.items.find(i=>i.id===itemId),current=item&&chosen(item);
  const profile=s.profiles.find(v=>v.id===(itemId?s.castings?.[itemId]??s.selectedProfileId:s.selectedProfileId)&&!v.removedAt);
  const currentProvider=MODELS.find(m=>m.id===current?.model)?.provider;
  const [delivery,setDelivery]=useState<VoiceDelivery>(()=>voiceDeliveryFor(project,itemId)??{}),[working,setWorking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[instruction,setInstruction]=useState('');
  const storedDelivery=JSON.stringify(voiceDeliveryFor(project,itemId)??{});
  useEffect(()=>{setDelivery(JSON.parse(storedDelivery));},[storedDelivery,itemId]);
  const [provider,setProvider]=useState<'elevenlabs'|'minimax'>('elevenlabs'),[name,setName]=useState('Новый голос'),[description,setDescription]=useState(''),[phrase,setPhrase]=useState(''),[variants,setVariants]=useState(3),[designModel,setDesignModel]=useState<'eleven_ttv_v3'|'eleven_multilingual_ttv_v2'>('eleven_ttv_v3'),[batchId,setBatchId]=useState(()=>crypto.randomUUID());
  const locked=busy||working,execute=async(action:string,data:Record<string,unknown>,message:string)=>{setWorking(true);setError('');setNotice('');try{await submit(action,data);setNotice(message);}catch(e){setError(errorText(e));}finally{setWorking(false);}};
  let inputIssue='',estimate:string|null=null;
  try{estimate=voiceDesignEstimate(validateVoiceDesignInput({provider,name,description,previewText:phrase,model:provider==='elevenlabs'?designModel:undefined,variants:provider==='minimax'?variants:1}));}catch(e){inputIssue=errorText(e);}
  let preview='',warnings:string[]=[],compileIssue='';
  if(current?.dialogue.trim()&&profile){try{const c=compileVoiceSpeech(profile.provider,speechModel??(profile.provider==='minimax'?'speech-2.8-hd':'eleven_v3'),profile.voiceId,current.dialogue,delivery);preview=JSON.stringify(c.body,null,2);warnings=c.warnings;}catch(e){compileIssue=errorText(e);}}
  const candidates=s.candidates.filter(c=>c.itemId===itemId),jobs=voiceWorkflowJobs(p);
  return <section aria-label="Постановка голоса и создание новых голосов" className="space-y-5">
    {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    <section className="editor-surface p-5 space-y-4"><h2>Профили голосов</h2><p>Сохраните голос для повторного использования. Выбор профиля действует при новой озвучке; готовые записи сохраняют прежний голос.</p>
      {s.profiles.filter(v=>!v.removedAt).map(v=><article className="border rounded p-3 space-y-2" key={v.id}><h3>{v.name} · {v.provider}</h3><p>{v.description}</p><p className="text-xs">Voice ID: {v.voiceId}</p>{v.previewAssetId&&<audio controls preload="none" src={'/api/assets/'+v.previewAssetId}/>}<pre className="whitespace-pre-wrap text-xs">{readableVoiceDelivery(v.delivery)}</pre>
        <div className="flex flex-wrap gap-2"><Button disabled={locked} variant={v.id===s.selectedProfileId?'secondary':'outline'} onClick={()=>execute('chooseProfile',{profileId:v.id},'Профиль выбран для новой озвучки.')}>{v.id===s.selectedProfileId?'✓ Профиль выбран':'Выбрать профиль'}</Button>{itemId&&<Button disabled={locked} variant="outline" onClick={()=>execute('saveProfile',{profileId:v.id,profile:{name:v.name,description:v.description,provider:v.provider,voiceId:v.voiceId,characterId:v.characterId,delivery}},'Исполнение сохранено в профиле.')}>Сохранить текущую манеру в профиль</Button>}<Button disabled={locked} variant="ghost" onClick={()=>execute('removeProfile',{profileId:v.id},'Профиль убран из списка.')}>Удалить</Button></div></article>)}
      {!s.profiles.some(v=>!v.removedAt)&&<p>Создайте голос по описанию ниже или сохраните Voice ID текущей записи как профиль.</p>}
      {current?.voiceId&&['minimax','elevenlabs'].includes(currentProvider??'')&&<Button variant="outline" disabled={locked} onClick={()=>execute('saveProfile',{profile:{name:current.speaker||item?.title||'Голос',description:'Голос текущей записи',provider:currentProvider,voiceId:current.voiceId,delivery}},'Voice ID текущей записи сохранён в профилях.')}>Сохранить текущий Voice ID как профиль</Button>}
      {s.profiles.some(v=>v.removedAt)&&<details><summary>Удалённые профили</summary>{s.profiles.filter(v=>v.removedAt).map(v=><div key={v.id}>{v.name}<Button disabled={locked} variant="ghost" onClick={()=>execute('restoreProfile',{profileId:v.id},'Профиль восстановлен без автоматического выбора.')}>Восстановить</Button></div>)}</details>}
    </section>
    {itemId&&<section className="editor-surface p-5 space-y-4"><h2>Исполнение реплики · {item?.title}</h2>
      <Field label="Голос этого плана"><select aria-label="Голос этого плана" className="w-full rounded border p-2 bg-background" value={s.castings?.[itemId]??''} disabled={locked} onChange={e=>execute('assignProfile',{itemId,profileId:e.target.value||null},'Назначение голоса сохранено для новой озвучки этого плана. Готовая запись сохраняет прежний голос.')}><option value="">Общий голос выбранной серии</option>{s.profiles.filter(v=>!v.removedAt).map(v=><option key={v.id} value={v.id}>{v.name} · {v.provider}</option>)}</select></Field>
      {s.castings?.[itemId]&&<p className="text-sm">Назначение этого плана имеет приоритет над общим профилем пакетной озвучки. Явный профиль в строке серии может его заменить.</p>}
      {current?.dialogue&&<blockquote>{current.dialogue}</blockquote>}<VoiceDirectionFields value={delivery} onChange={setDelivery} disabled={locked}/><Button disabled={locked||!item} onClick={()=>execute('saveDelivery',{itemId,delivery},'Постановка сохранена. Создайте новую озвучку, чтобы услышать изменения.')}>Сохранить постановку реплики</Button>
      <Field label="Пожелания агенту озвучки"><Textarea value={instruction} maxLength={2000} disabled={locked} onChange={e=>setInstruction(e.target.value)}/></Field><Button variant="outline" disabled={locked||!current?.dialogue.trim()} onClick={()=>execute('proposeDelivery',{batchId:crypto.randomUUID(),itemId,model,instruction},'Агент добавлен в очередь. Предложение появится отдельно, настройки не изменены.')}>Предложить исполнение с ИИ</Button>
      <details><summary>Промпт агента до запуска</summary><pre className="whitespace-pre-wrap text-xs">{(()=>{try{return voiceDirectionPrompt(p,itemId,instruction).prompt;}catch(e){return errorText(e);}})()}</pre></details>
      {compileIssue&&<p role="alert">{compileIssue}</p>}{warnings.map((v,n)=><p className="text-sm" key={n}>{v}</p>)}{preview&&<details><summary>Параметры TTS · предпросмотр</summary><pre className="whitespace-pre-wrap text-xs">{preview}</pre></details>}
      {!!candidates.length&&<><VersionComparison versions={candidates.map(c=>{const j=jobs.find(j=>j.id===c.jobId);return {id:c.id,label:'Исполнение · '+new Date(c.created).toLocaleString('ru-RU'),text:readableVoiceDelivery(c.delivery)+'\n\n'+c.notes.join('\n'),selectable:false,metadata:{model:j?.model,created:c.created,actualCost:money(j?.actual),estimatedCost:money(j?.estimate)}};})} title="Сравнение предложений исполнения"/>{candidates.map(c=><Button key={c.id} variant="outline" disabled={locked||c.applied} onClick={()=>execute('applyDelivery',{candidateId:c.id},'Предложение применено к постановке реплики. Создайте новую озвучку, чтобы услышать изменения.')}>{c.applied?'✓ Исполнение применено':'Применить исполнение · '+new Date(c.created).toLocaleTimeString('ru-RU')}</Button>)}</>}
    </section>}
    {allowDesign&&<section className="editor-surface p-5 space-y-4"><h2>Создать новый голос по описанию</h2><div className="grid gap-3 sm:grid-cols-2"><Field label="Провайдер"><select aria-label="Провайдер Voice Design" className="w-full rounded border p-2 bg-background" value={provider} disabled={locked} onChange={e=>{setProvider(e.target.value as typeof provider);setBatchId(crypto.randomUUID());}}><option value="elevenlabs">ElevenLabs</option><option value="minimax">MiniMax</option></select></Field><Field label="Название голоса"><Input maxLength={100} value={name} disabled={locked} onChange={e=>{setName(e.target.value);setBatchId(crypto.randomUUID());}}/></Field></div>
      <Field label="Как должен звучать голос"><Textarea placeholder="Тембр, возрастное впечатление, характер, русский язык, дикция и выразительность" maxLength={1000} value={description} disabled={locked} onChange={e=>{setDescription(e.target.value);setBatchId(crypto.randomUUID());}}/></Field>
      <Field label={`Фраза для прослушивания · ${phrase.length}/${provider==='minimax'?500:1000}`}><Textarea maxLength={provider==='minimax'?500:1000} value={phrase} disabled={locked} onChange={e=>{setPhrase(e.target.value);setBatchId(crypto.randomUUID());}}/></Field>
      {provider==='elevenlabs'?<Field label="Модель создания голоса"><select className="rounded border p-2 bg-background" value={designModel} disabled={locked} onChange={e=>{setDesignModel(e.target.value as typeof designModel);setBatchId(crypto.randomUUID());}}><option value="eleven_ttv_v3">Eleven Voice Design v3</option><option value="eleven_multilingual_ttv_v2">Eleven Voice Design v2</option></select></Field>:<Field label="Количество отдельных проб MiniMax"><Input type="number" min={1} max={3} value={variants} disabled={locked} onChange={e=>{setVariants(Number(e.target.value));setBatchId(crypto.randomUUID());}}/></Field>}
      <p>{provider==='elevenlabs'?'ElevenLabs вернёт несколько вариантов одним запросом; выбранный сохраняется отдельно.':'MiniMax создаёт один голос за запрос. Все запрошенные варианты учитываются как отдельные попытки; кнопка сохранения добавляет выбранный голос в проект.'}</p><p>Оценка: {estimate===null?'уточняется по тарифу аккаунта':money((BigInt(estimate)*BigInt(provider==='minimax'?variants:1)).toString())} · фактические списания отдельно в журнале.</p>
      {inputIssue&&<p className="text-sm text-muted-foreground">{inputIssue}</p>}<Button disabled={locked||!!inputIssue} onClick={()=>execute('design',{batchId,input:{provider,name,description,previewText:phrase,model:provider==='elevenlabs'?designModel:undefined,variants:provider==='minimax'?variants:1}},'Серия добавлена в очередь. Запустите её ниже или дождитесь фонового исполнителя.')}>Создать варианты голоса</Button>
    </section>}
    {s.designs.filter(d=>!d.removedAt).slice().reverse().map(d=><section key={d.id} className="editor-surface p-5 space-y-4"><div className="flex justify-between gap-2"><h3>{d.name} · {d.provider}</h3><Button disabled={locked} variant="ghost" onClick={()=>execute('removeDesign',{designId:d.id},'Серия убрана из списка.')}>Удалить серию</Button></div><p>{d.description}</p><p>«{d.previewText}»</p><div className="grid gap-3 md:grid-cols-3">{d.previews.map((v,n)=><article className="border rounded p-3 space-y-2" key={v.id}><h4>Вариант {n+1}{d.selectedPreviewId===v.id?' · ✓':''}</h4>{v.assetId&&<audio controls preload="none" src={'/api/assets/'+v.assetId} onPlay={e=>{e.currentTarget.closest('section[aria-label]')?.querySelectorAll('audio').forEach(a=>{if(a!==e.currentTarget)a.pause();});}}/>}<Button disabled={locked||!v.assetId} variant={d.selectedPreviewId===v.id?'secondary':'outline'} onClick={()=>execute('selectPreview',{designId:d.id,previewId:v.id},'Вариант выбран для сохранения.')}>Выбрать этот голос</Button></article>)}</div>
      <Button disabled={locked||!d.selectedPreviewId||!!d.profileId||!!d.saveJobId&&jobs.some(j=>j.id===d.saveJobId&&!['failed','cancelled'].includes(j.status))} onClick={()=>execute('saveVoice',{batchId:crypto.randomUUID(),designId:d.id},d.provider==='minimax'?'Голос добавлен в профили. Выберите его для озвучки.':'Сохранение выбранного голоса добавлено в очередь.')}>{d.profileId?'✓ Голос сохранён':'Сохранить выбранный голос'}</Button>
    </section>)}
    {jobs.length>0&&<section className="editor-surface p-5 space-y-3"><h3>Попытки создания и исполнения голосов</h3><p>Неизвестный исход не повторяется автоматически. Прослушивание готовых файлов бесплатно и не создаёт новых запросов.</p>{jobs.slice().reverse().map(j=><article className="border rounded p-3 space-y-2" key={j.id}><p>{j.brief} · {j.status} · {j.actual!==null?'Списано: '+money(j.actual):'Стоимость уточняется · оценка '+money(j.estimate)}</p>{j.error&&<p role="alert">{j.error}</p>}<div className="flex flex-wrap gap-2">{['queued','saving'].includes(j.status)&&<Button disabled={locked} variant="outline" onClick={()=>execute('advance',{jobId:j.id},'Состояние попытки обновлено.')}>{j.status==='saving'?'Повторить сохранение файла':'Запустить эту попытку'}</Button>}{['queued','dispatching'].includes(j.status)&&<Button disabled={locked} variant="ghost" onClick={()=>execute('stop',{jobId:j.id},'Ожидание остановлено; оплаченный запрос не повторяется.')}>Остановить ожидание</Button>}{j.voiceWorkflow.late&&j.voiceWorkflow.savedVoiceId&&<Button disabled={locked} variant="outline" onClick={()=>execute('importSavedVoice',{jobId:j.id},'Подтверждённый провайдером голос добавлен в профили.')}>Добавить полученный голос в проект</Button>}</div><details><summary>Фактический запрос и ответ</summary><pre className="whitespace-pre-wrap text-xs">{j.prompt}</pre>{j.output?.text&&<pre className="whitespace-pre-wrap text-xs">{j.output.text}</pre>}</details></article>)}</section>}
    {s.designs.some(d=>d.removedAt)&&<details><summary>Удалённые серии голосов</summary>{s.designs.filter(d=>d.removedAt).map(d=><div key={d.id}>{d.name}<Button disabled={locked} variant="ghost" onClick={()=>execute('restoreDesign',{designId:d.id},'Серия восстановлена без новой генерации.')}>Восстановить</Button></div>)}</details>}
  </section>;
}
