import {z} from 'zod';
import type {Project,Job} from './domain';
import type {DirectorRole,DirectorRun,DirectorTask} from './directing';
import {model} from './models';
export const directorExecutionSchema=z.object({parallelModels:z.array(z.string()).max(3).optional(),fallbackModel:z.string().optional()});
export type DirectorExecution=z.infer<typeof directorExecutionSchema>;
export function validateDirectorExecution(input:unknown):DirectorExecution{const value=directorExecutionSchema.parse(input);for(const key of [...(value.parallelModels??[]),...(value.fallbackModel?[value.fallbackModel]:[])]){const m=model(key);if(m.kind!=='text'||!['openai','xai','minimax'].includes(m.provider))throw Error('Для команды и резерва выберите текстовую модель GPT, Grok или MiniMax.');}return value;}
export function taskModel(run:DirectorRun,t:DirectorTask){if(t.fallbackFromJobId)return run.execution?.fallbackModel??run.model;const pool=run.execution?.parallelModels?.length?run.execution.parallelModels:[run.model];return pool[run.tasks.filter(v=>v.sceneId&&['story','camera','art','dialogue','performance','shot-planner'].includes(v.role)).findIndex(v=>v.id===t.id)%pool.length]??run.model;}
export function fallbackEligible(job:Job,validation=false){if(job.status!=='failed')return false;const error=job.error??'';if(/safety|public figure|sexual|content.?policy|moderation|запрещ|политик|баланс|HTTP (?:400|401|402|403|404|422)/i.test(error))return false;return validation||/HTTP 429/.test(error);}
/** One reserve attempt, separate receipt/cost. Unknown paid outcomes never qualify. */
export function scheduleDirectorFallback(p:Project,run:DirectorRun,t:DirectorTask,job:Job,validation=false){if(!run.execution?.fallbackModel||run.stopped||t.fallbackFromJobId||!fallbackEligible(job,validation))return false;t.previousJobIds=[...(t.previousJobIds??[]),job.id];t.fallbackFromJobId=job.id;t.jobId=undefined;t.error=undefined;t.result=undefined;t.applied=undefined;return true;}
const optionalDirectionKeys=new Set(['framingStart','framingEnd','angle','description','composition','attention','cameraMovement','from','to','actionBeats','timing','openingHold','endingHold','revealAt','positions','screenDirection','subjectId','performance','characterId','transition','toShotId','sound','ambience','effects','music','silence','startFrame','endFrame','id','emotionalChange']);
function cleanDirection(value:any):any{if(Array.isArray(value))return value.map(cleanDirection);if(!value||typeof value!=='object')return value;const copy:any={};for(const [key,v] of Object.entries(value))if(v!==null||!optionalDirectionKeys.has(key))copy[key]=cleanDirection(v);if(typeof copy.screenDirection==='string'&&!['left-to-right','right-to-left','toward-camera','away-from-camera','static','custom'].includes(copy.screenDirection)){const raw=copy.screenDirection,normal=raw.toLowerCase().replace(/[.]/g,'').trim();const aliases:Record<string,string>={'слева направо':'left-to-right','справа налево':'right-to-left','к камере':'toward-camera','от камеры':'away-from-camera','неподвижно':'static','статично':'static'};copy.screenDirection=aliases[normal]??'custom';copy.end=(copy.end??'')+'; направление: '+raw;}return copy;}
/** Only unambiguous syntax cleanup. Unknown IDs, duplicates, missing rows and timing conflicts stay errors. */
export function normalizeDirectorAnswer(p:Project,role:DirectorRole,sceneId:string|undefined,answer:unknown):unknown{const copy=structuredClone(answer) as any;if(!copy||!Array.isArray(copy.shots))return copy;if(role==='camera'||role==='story')for(const shot of copy.shots)if(shot.direction)shot.direction=cleanDirection(shot.direction);
  // Some actor responses include neighbours marked as context. Drop only IDs
  // belonging to another known scene, never unknown/new or unrequested current shots.
  if(role==='performance'&&sceneId){const contextIds=new Set(p.directing?.scenes.filter(s=>s.id!==sceneId).flatMap(s=>s.shots.map(v=>v.id)));copy.shots=copy.shots.filter((s:any)=>!contextIds.has(s.id));}
  return copy;
}
export function compactSpecialistContext(p:Project,t:DirectorTask,base:any){if(!t.sceneId||!['story','camera','art','dialogue','performance','compress','shot-planner'].includes(t.role))return base;const scene=p.directing!.scenes.find(s=>s.id===t.sceneId)!;const ids=t.shotIds??(t.shotId?[t.shotId]:scene.shots.map(s=>s.id)),selected=scene.shots.filter(s=>ids.includes(s.id)),index=p.directing!.scenes.indexOf(scene);
  const summary=(s:any)=>s&&({id:s.id,title:s.title,purpose:s.purpose,location:s.location,stateIn:s.stateIn,stateOut:s.stateOut,turn:s.turn});
  const neighbour=(s:any)=>({id:s.id,title:s.title,duration:s.duration,story:s.story,stateIn:s.stateIn,stateOut:s.stateOut,continuityChanges:s.continuityChanges,dialogue:s.dialogue,framing:s.direction?.framingStart,transition:s.direction?.transition});
  const edge=new Set<number>();for(const shot of selected){const n=scene.shots.indexOf(shot);for(const k of [n-1,n+1])if(k>=0&&k<scene.shots.length&&!ids.includes(scene.shots[k].id))edge.add(k);}
  const stripped=(s:any)=>{const {approved,approvedFoundation,approvalVersion,imagePrompt,videoPrompt,promptBasis,...content}=s;return content;};
  // Scene specialists own only these target rows; adjacent rows are lightweight
  // context. Hero locks and relevant world information remain intact.
  return {...base,approved:base.approved.filter((v:any)=>v.stage===2||v.stage===1&&(t.role==='shot-planner'||selected.some(s=>s.cast.includes(v.character?.name??v.title)||s.characterIds?.includes(v.id)))),outline:base.outline.map(summary),previous:summary(p.directing!.scenes[index-1]),next:summary(p.directing!.scenes[index+1]),scene:{...scene,shots:selected.map(stripped)},requestedShotIds:ids,contextOnlyNeighbours:[...edge].sort((a,b)=>a-b).map(n=>neighbour(scene.shots[n])),sceneBoundaryNeighbours:[p.directing!.scenes[index-1]?.shots.at(-1),p.directing!.scenes[index+1]?.shots[0]].filter(Boolean).map(neighbour)};
}
