import {z} from 'zod';

const fact=z.string().max(1000);
const causalFields={trigger:fact,meaning:fact,emotionStart:fact,emotionEnd:fact,decision:fact,visibleEvidence:fact};
/** Optional on persisted legacy scenes; new scene generations explicitly fill it. */
export const sceneCausalLinkSchema=z.object({character:z.string().trim().min(1).max(100),expectation:fact,...causalFields}).strict();
export type SceneCausalLink=z.infer<typeof sceneCausalLinkSchema>;
export const NARRATIVE_BEAT_LABELS={setup:'Подготовка / ожидание',action:'Действие',reaction:'Реакция','action-reaction':'Действие и реакция',transition:'Переход'} as const;
export const narrativeBeatSchema=z.object({role:z.enum(['setup','action','reaction','action-reaction','transition']),character:z.string().trim().min(1).max(100).optional(),...causalFields}).strict();
export type NarrativeBeat=z.infer<typeof narrativeBeatSchema>;

export const SCENE_CAUSALITY_INSTRUCTION=' Эмоциональная причинность обязательна для новых сцен: опирайся на emotionalArcs утверждённого сценария, а при отсутствии структурированных дуг извлеки их из самого текста. Для каждого героя, чья перспектива меняется, заполни объект causalChain по полному формату ответа: character — имя; expectation — чего ждёт до события; trigger — какое видимое событие меняет ожидание; meaning — что герой теперь понимает и почему это важно лично ему; emotionStart/emotionEnd — чувство до/после; decision — как новое понимание меняет намерение; visibleEvidence — что именно зритель увидит в лице, теле и поступке. В purpose/conflict/turn и stateIn/stateOut также должна читаться эта причинность; отдельная справка не заменяет драматургию сцены. Пустой causalChain допустим только для сцены без эмоциональной перспективы персонажей. Событие → его значение для героя → изменение чувства → решение → наблюдаемое поведение. Не приписывай зрителю знание исходного произведения: значимые ожидания, сравнения и причины тревоги сначала установи экранным действием. Скрытая авторская мысль не является экранным доказательством. Для фильма без речи смысл должен читаться без рассказчика, титров и добавленного диалога. Не создавай новые сюжетные события ради схемы и не заставляй каждую сцену менять знак эмоции.';
export const SHOT_CAUSALITY_INSTRUCTION=' Разделяй физическое действие и эмоциональную реакцию. Для каждого нового или перерабатываемого плана заполни narrativeBeat по полному формату ответа: role — функция плана; character — герой, если есть; trigger — наблюдаемый повод (у реакции допустимо событие предыдущего плана); meaning — что событие значит для героя; emotionStart/emotionEnd — чувство до/после; decision — следующее намерение; visibleEvidence — наблюдаемое изменение лица, позы, взгляда или поступка. role выбери из setup, action, reaction, action-reaction, transition: setup устанавливает ожидание, action показывает причину, reaction даёт её прожить, action-reaction вмещает и причину, и реакцию, transition связывает эпизоды. В переходе без героя поля переживания могут быть пусты. Заранее оставь экранное время на исходное чувство, распознавание события и реакцию. Не заканчивай каждый план сразу после физического действия и не прячь перелом в паузе за кадром. Соседняя реакция продолжает предыдущее состояние, не повторяет уже сыгранное осознание. Экономичный монтаж сохраняет важные реакции: объединяй действие с реакцией только если оба читаются в duration. Простое одно действие совместимо с содержательным эмоциональным поворотом; не перегружай его несколькими контактами с предметами. Формальное моргание или дыхание без причины не заменяет актёрской задачи.';
export const VIEWER_CAUSALITY_REVIEW=' Проверь фильм как зритель, который впервые видит историю и не знает исходного произведения. Для каждой важной перемены проследи emotionalArcs → causalChain → direction.narrativeBeat → story/actionBeats → direction.performance: чего зритель ожидает вместе с героем; где на экране показана причина; что герой понял; какое изменение лица, позы или действия позволит это понять; какое решение следует. Если фильм без речи, мысленно убери описания, рассказчика и титры: остаётся ли понятным смысл? Поворот, существующий только в метаданных, не считается поставленным. Проверь время на распознавание и реакцию, видимость лица либо читаемость тела, соответствие реакции характеру/жанру и переход эмоционального состояния в следующий план. Не объявляй постоянное чувство ошибкой, если событие его не меняет. Отсутствие причины важного утверждённого поворота или его экранного выражения — конкретное замечание с готовым решением, а не общая похвала. Не добавляй новое событие без творческого выбора пользователя. Исправляй story/stateIn/stateOut и полную direction с сохранением камеры, narrativeBeat и performance согласованно; если нужна другая длительность или состав, предложи montageOperations. Для ошибки в структуре сцены предложи точный новый causalChain в solution: не подставляй sceneId вместо shotId в patches.';

export function readableNarrativeBeat(beat?:NarrativeBeat){
  if(!beat)return '';
  return [`Задача плана: ${NARRATIVE_BEAT_LABELS[beat.role]}${beat.character?' · '+beat.character:''}`,beat.trigger?'Повод: '+beat.trigger:'',beat.meaning?'Осознание: '+beat.meaning:'',beat.emotionStart||beat.emotionEnd?`Переживание: ${beat.emotionStart} → ${beat.emotionEnd}`:'',beat.decision?'Решение: '+beat.decision:'',beat.visibleEvidence?'На экране: '+beat.visibleEvidence:''].filter(Boolean).join('\n');
}
