import {z} from 'zod';
import type {Project} from './domain';
import {id,now} from './domain';
import {ensureDirecting,scenesBasis,signature,sceneOutline,foundation,type Scene,type DirectingShot,type DirectorRun,type DirectorTask} from './directing';
import {FRAMINGS} from './shot-direction';
import {creativeFoundationBrief} from './creative-foundation';
import {narrativeBeatSchema,SHOT_CAUSALITY_INSTRUCTION} from './emotional-dramaturgy';
import {meaningIdsSchema,storyMeaningApprovalContext,assertMeaningLinks,STORY_MEANING_INSTRUCTION} from './story-meaning';

export const PLAN_POLICIES={economy:'Экономичный',balanced:'Обычный',detailed:'Подробный'} as const;
export const planPolicySchema=z.enum(['economy','balanced','detailed']);
export type PlanPolicy=z.infer<typeof planPolicySchema>;
export const planSketchSchema=z.object({id:z.string().min(1).max(100),title:z.string().trim().min(1).max(100),duration:z.number().finite().min(.5).max(60),cast:z.array(z.string().max(100)).max(20),action:z.string().trim().min(1).max(2500),purpose:z.string().trim().min(1).max(1000),framing:z.enum(FRAMINGS),stateIn:z.string().max(2000),stateOut:z.string().max(2000),speechType:z.enum(['voiceover','character','none']),speaker:z.string().max(100),text:z.string().max(4000),transition:z.string().max(1000),narrativeBeat:narrativeBeatSchema.optional(),meaningIds:meaningIdsSchema.optional()}).refine(s=>s.speechType!=='none'||!s.text.trim(),'Для плана без речи текст пустой.').refine(s=>s.speechType!=='character'||s.cast.includes(s.speaker),'Говорящий герой должен присутствовать в плане.');
export type PlanSketch=z.infer<typeof planSketchSchema>;
export type PlanningScene={sceneId:string;policy?:PlanPolicy;cards:PlanSketch[];approved?:string;archive:{card:PlanSketch;shot?:DirectingShot;index:number;removed:string}[]};
export type ShotPlanningState={policy:PlanPolicy;scenes:PlanningScene[];proposals:{id:string;taskId:string;sceneId:string;policy:PlanPolicy;basis:string;created:string;model:string;cards:PlanSketch[]}[]};
export function sketchFromShot(s:DirectingShot):PlanSketch{return {id:s.id,title:s.title,duration:s.duration,...(s.meaningIds!==undefined?{meaningIds:[...s.meaningIds]}:{}),cast:[...s.cast],action:s.story||s.title,purpose:s.title,framing:s.direction?.framingStart??'medium',stateIn:s.stateIn,stateOut:s.stateOut,speechType:s.dialogue.speechType,speaker:s.dialogue.speaker,text:s.dialogue.text,transition:s.direction?.transition?.description??'',...(s.direction?.narrativeBeat?{narrativeBeat:structuredClone(s.direction.narrativeBeat)}:{})};}
export function planningScene(p:Project,s:Scene):PlanningScene{return p.directing?.shotPlanning?.scenes.find(v=>v.sceneId===s.id)??{sceneId:s.id,cards:s.shots.map(sketchFromShot),archive:[]};}
export function ensureShotPlanning(p:Project){const d=ensureDirecting(p);const state=d.shotPlanning??={policy:'balanced',scenes:[],proposals:[]};for(const scene of d.scenes)if(!state.scenes.some(v=>v.sceneId===scene.id))state.scenes.push(planningScene(p,scene));return state;}
export function planningInputBasis(p:Project,s:Scene){return signature(JSON.parse(JSON.stringify({outline:sceneOutline(s),script:foundation(p).filter(v=>v.stage===0),brief:creativeFoundationBrief(p.directing?.brief),...storyMeaningApprovalContext(p)})));}
export function planSetBasis(p:Project,s:Scene){return signature([planningInputBasis(p,s),planningScene(p,s).cards]);}
export function planSetApproved(p:Project,s:Scene){return !!p.directing?.shotPlanning?.scenes.find(v=>v.sceneId===s.id)?.approved&&planningScene(p,s).approved===planSetBasis(p,s)&&JSON.stringify(planningScene(p,s).cards.map(c=>c.id))===JSON.stringify(s.shots.map(c=>c.id));}
export function allPlanSetsApproved(p:Project){return !!p.directing?.scenes.length&&p.directing.scenes.every(s=>planSetApproved(p,s));}
export function assertPlanSets(p:Project,scenes:Scene[]){if(p.directing?.shotPlanning)for(const scene of scenes)if(!planSetApproved(p,scene))throw Error(`«${scene.title}»: утвердите набор на этапе «Планы сцен».`);}
export function setPlanPolicy(p:Project,policy:PlanPolicy,sceneId?:string){const state=ensureShotPlanning(p);if(sceneId){const row=state.scenes.find(v=>v.sceneId===sceneId);if(!row)throw Error('Сцена не найдена.');row.policy=policy;}else state.policy=policy;}
export function planningPolicy(p:Project,sceneId:string){const state=p.directing?.shotPlanning;return state?.scenes.find(s=>s.sceneId===sceneId)?.policy??state?.policy??'balanced';}
export function plannerInstruction(policy:PlanPolicy){return 'Ты режиссёр монтажного плана. Сначала предложи только короткий набор планов для текущей сцены, а не подробную работу специалистов. '+(policy==='economy'?'Минимум необходимых планов: объединяй простые совместимые действия; сохраняй причинность, важные реакции и раскрытия. Не превращай экономию в один перегруженный невыполнимый клип.':policy==='detailed'?'Подробное покрытие: выразительные детали, точки зрения, крупные реакции и паузы там, где это помогает сцене. Не добавляй формальные дубли и не увеличивай хронометраж только ради числа планов.':'Сбалансируй действие и реакцию, общие, средние и крупные планы. Избегай однообразия и лишних повторов.')+' Сохрани события и выбранные жанр/режиссёрские приёмы. Объясни purpose каждого плана, обеспечь монтажную причинность и разные крупности. duration — ориентир, минимум .5, максимум 60 сек. Если это тот же план, сохраняй его существующий ID; новые ID обозначь new-1 и т.д. Изменение состава будет предложением на выбор режиссёра. Верни {"shots":[{"id":"new-1","title":"...","duration":5,"cast":["имя"],"action":"что происходит","purpose":"зачем этот план","framing":"medium","stateIn":"начало","stateOut":"конец","speechType":"none","speaker":"","text":"","transition":"стык со следующим","narrativeBeat":{"role":"action-reaction","character":"имя","trigger":"наблюдаемое событие","meaning":"что оно значит для героя","emotionStart":"чувство до события","emotionEnd":"чувство после события","decision":"новое намерение","visibleEvidence":"как зритель увидит перемену"}}]}. framing выбери из wide, medium, close-up, extreme-wide, extreme-close-up, detail. speechType выбери из none, voiceover, character; для none оставь text пустым, иначе внеси только произносимые слова. Не более 40 планов; не заполняй операторскую постановку и художника.'+SHOT_CAUSALITY_INSTRUCTION+STORY_MEANING_INSTRUCTION+' Верни meaningIds у каждого плана: только ID связанных смыслов текущей сцены из storyMeaning.meanings. Каждый required-смысл сцены должен получить хотя бы один план с конкретным экранным подтверждением в narrativeBeat.visibleEvidence и action. meaningIds: [] допустим для перехода без смысловой опоры. Не помещай все смыслы или развязку сцены в первый короткий клип.'+' Перед отправкой проверь: narrativeBeat — полное отдельное поле каждой карточки shots, рядом с purpose; описание реакции в action не заменяет это поле.';}
export function savePlanningProposal(p:Project,run:DirectorRun,t:DirectorTask,result:unknown){const s=p.directing!.scenes.find(s=>s.id===t.sceneId);if(!s)throw Error('Сцена удалена.');if(t.inputContentBasis!==planningInputBasis(p,s))throw Error('Структура сцены изменилась. Создайте актуальный набор планов.');const data=z.object({shots:z.array(planSketchSchema).min(1).max(40)}).parse(result);for(const card of data.shots)assertMeaningLinks(p,card.meaningIds);if(s.causalChain?.length){const missing=data.shots.find(card=>!card.narrativeBeat);if(missing)throw Error(`«${missing.title}»: монтажный план не содержит narrativeBeat. Укажите действие/реакцию и экранное подтверждение; перебивка может быть без героя.`);}if(new Set(data.shots.map(c=>c.id)).size!==data.shots.length)throw Error('Повторяются ID планов.');const state=ensureShotPlanning(p);state.proposals.push({id:id(),taskId:t.id,sceneId:s.id,policy:run.planPolicyByScene?.[s.id]??planningPolicy(p,s.id),basis:planningInputBasis(p,s),created:now(),model:p.jobs.find(j=>j.id===t.jobId)?.model??run.model,cards:data.shots});}

/** Explicit montage edits on the detailed page update the outline too. The
 * director's montage decision is retained; it is not overwritten by old cards. */
export function syncPlanSetAfterMontage(p:Project,sceneIds:string[]){const state=p.directing?.shotPlanning;if(!state)return;for(const s of p.directing!.scenes.filter(s=>sceneIds.includes(s.id))){const row=state.scenes.find(v=>v.sceneId===s.id);if(!row)continue;const old=row.cards;for(const card of old.filter(c=>!s.shots.some(v=>v.id===c.id)))row.archive.push({card, index:old.indexOf(card),removed:now()});row.cards=s.shots.map(shot=>({...sketchFromShot(shot),purpose:old.find(v=>v.id===shot.id)?.purpose??shot.title}));row.approved=undefined;}}
function shotFromCard(card:PlanSketch,old?:DirectingShot):DirectingShot{return {...old,id:card.id,title:card.title,duration:card.duration,...(card.meaningIds!==undefined?{meaningIds:[...card.meaningIds]}:{}),cast:card.cast,characterIds:JSON.stringify(old?.cast)===JSON.stringify(card.cast)?old?.characterIds:undefined,story:card.action,stateIn:card.stateIn,stateOut:card.stateOut,cinematography:'',productionDesign:'',dialogue:{speechType:card.speechType,speaker:card.speaker,text:card.text,delivery:''},continuityChanges:'',direction:{framingStart:card.framing,...(card.narrativeBeat?{narrativeBeat:structuredClone(card.narrativeBeat)}:{}),...(old?.direction?.facialExpression!==undefined?{facialExpression:old.direction.facialExpression}:{}),...(old?.direction?.stagingMode!==undefined?{stagingMode:old.direction.stagingMode}:{})},approved:undefined,approvedFoundation:undefined,imagePrompt:undefined,videoPrompt:undefined,promptBasis:undefined};}
/** A plan set changes only after a director chooses/edits it. Paid material keeps its ID. */
export function replacePlanCards(p:Project,sceneId:string,input:PlanSketch[]){const s=p.directing!.scenes.find(s=>s.id===sceneId);if(!s)throw Error('Сцена не найдена.');const cards=z.array(planSketchSchema).min(1).max(40).parse(input).map(card=>{const previous=s.shots.find(shot=>shot.id===card.id);const next=card.meaningIds===undefined&&previous?.meaningIds!==undefined?{...card,meaningIds:[...previous.meaningIds]}:card;assertMeaningLinks(p,next.meaningIds);return next;});if(new Set(cards.map(c=>c.id)).size!==cards.length||cards.some(c=>p.directing!.scenes.some(other=>other.id!==s.id&&other.shots.some(shot=>shot.id===c.id))))throw Error('ID планов должны быть уникальными в фильме.');if(p.directing!.scenes.filter(v=>v.id!==sceneId).reduce((n,v)=>n+v.shots.length,0)+cards.length>120)throw Error('В фильме максимум 120 планов.');const state=ensureShotPlanning(p),row=state.scenes.find(v=>v.sceneId===sceneId)!;const before=row.cards,oldShots=s.shots;
  for(const card of before.filter(c=>!cards.some(v=>v.id===c.id)))row.archive.push({card:structuredClone(card),shot:structuredClone(oldShots.find(v=>v.id===card.id)),index:before.indexOf(card),removed:now()});
  s.shots=cards.map(card=>{const old=oldShots.find(v=>v.id===card.id),prior=before.find(v=>v.id===card.id);return old&&prior&&signature(prior)===signature(card)?old:shotFromCard(card,old);});
  const neighbour=(list:PlanSketch[],key:string)=>{const n=list.findIndex(c=>c.id===key);return [list[n-1]?.id,list[n+1]?.id].join('|');};
  for(const shot of s.shots)if(neighbour(before,shot.id)!==neighbour(cards,shot.id)){shot.approved=undefined;shot.promptBasis=undefined;}
  if(JSON.stringify(before.map(c=>c.id))!==JSON.stringify(cards.map(c=>c.id)))p.directing!.planOrderChanged=true;
  row.cards=structuredClone(cards);row.approved=undefined;p.directing!.editorBasis=undefined;p.directing!.acceptedRuntime=undefined;
}
export function choosePlanningProposal(p:Project,proposalId:string){const state=ensureShotPlanning(p),proposal=state.proposals.find(v=>v.id===proposalId),scene=p.directing!.scenes.find(s=>s.id===proposal?.sceneId);if(!proposal||!scene)throw Error('Вариант не найден.');if(proposal.basis!==planningInputBasis(p,scene))throw Error('Этот вариант создан для прежней структуры сцен.');const existing=new Set(planningScene(p,scene).cards.map(c=>c.id));replacePlanCards(p,scene.id,proposal.cards.map(c=>({...c,id:existing.has(c.id)?c.id:id()})));}
export function approvePlanSets(p:Project,sceneIds:string[]){if(p.directing?.scenesApproved!==scenesBasis(p))throw Error('Утвердите структуру сцен.');const state=ensureShotPlanning(p);if(!sceneIds.length||new Set(sceneIds).size!==sceneIds.length)throw Error('Выберите сцены.');for(const sceneId of sceneIds){const s=p.directing!.scenes.find(s=>s.id===sceneId),row=state.scenes.find(v=>v.sceneId===sceneId);if(!s||!row?.cards.length)throw Error('В каждой выбранной сцене должен быть хотя бы один план.');z.array(planSketchSchema).min(1).max(40).parse(row.cards);if(JSON.stringify(row.cards.map(c=>c.id))!==JSON.stringify(s.shots.map(c=>c.id)))throw Error('Состав планов изменился.');}for(const sceneId of sceneIds){const s=p.directing!.scenes.find(s=>s.id===sceneId)!;state.scenes.find(v=>v.sceneId===sceneId)!.approved=planSetBasis(p,s);}}
export function restorePlanningCard(p:Project,sceneId:string,shotId:string){const state=ensureShotPlanning(p),row=state.scenes.find(v=>v.sceneId===sceneId),entry=row?.archive.findLast(v=>v.card.id===shotId);if(!row||!entry||row.cards.some(v=>v.id===shotId))throw Error('План недоступен для восстановления.');const cards=[...row.cards];cards.splice(Math.min(entry.index,cards.length),0,entry.card);replacePlanCards(p,sceneId,cards);const scene=p.directing!.scenes.find(s=>s.id===sceneId)!;if(entry.shot)Object.assign(scene.shots.find(s=>s.id===shotId)!,entry.shot,{approved:undefined,promptBasis:undefined});row.archive=row.archive.filter(v=>v.card.id!==shotId);}
